// Code generated by ent, DO NOT EDIT.

package bonus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldUserID, v))
}

// DonorResponseID applies equality check predicate on the "donor_response_id" field. It's identical to DonorResponseIDEQ.
func DonorResponseID(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDonorResponseID, v))
}

// PartnerName applies equality check predicate on the "partner_name" field. It's identical to PartnerNameEQ.
func PartnerName(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPartnerName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDescription, v))
}

// Subcategory applies equality check predicate on the "subcategory" field. It's identical to SubcategoryEQ.
func Subcategory(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldSubcategory, v))
}

// PromoCode applies equality check predicate on the "promo_code" field. It's identical to PromoCodeEQ.
func PromoCode(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPromoCode, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldExpiresAt, v))
}

// PlatformName applies equality check predicate on the "platform_name" field. It's identical to PlatformNameEQ.
func PlatformName(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPlatformName, v))
}

// PlatformURL applies equality check predicate on the "platform_url" field. It's identical to PlatformURLEQ.
func PlatformURL(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPlatformURL, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldAssignedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldUserID))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldUserID, v))
}

// DonorResponseIDEQ applies the EQ predicate on the "donor_response_id" field.
func DonorResponseIDEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDonorResponseID, v))
}

// DonorResponseIDNEQ applies the NEQ predicate on the "donor_response_id" field.
func DonorResponseIDNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldDonorResponseID, v))
}

// DonorResponseIDIn applies the In predicate on the "donor_response_id" field.
func DonorResponseIDIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldDonorResponseID, vs...))
}

// DonorResponseIDNotIn applies the NotIn predicate on the "donor_response_id" field.
func DonorResponseIDNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldDonorResponseID, vs...))
}

// DonorResponseIDGT applies the GT predicate on the "donor_response_id" field.
func DonorResponseIDGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldDonorResponseID, v))
}

// DonorResponseIDGTE applies the GTE predicate on the "donor_response_id" field.
func DonorResponseIDGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldDonorResponseID, v))
}

// DonorResponseIDLT applies the LT predicate on the "donor_response_id" field.
func DonorResponseIDLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldDonorResponseID, v))
}

// DonorResponseIDLTE applies the LTE predicate on the "donor_response_id" field.
func DonorResponseIDLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldDonorResponseID, v))
}

// DonorResponseIDContains applies the Contains predicate on the "donor_response_id" field.
func DonorResponseIDContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldDonorResponseID, v))
}

// DonorResponseIDHasPrefix applies the HasPrefix predicate on the "donor_response_id" field.
func DonorResponseIDHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldDonorResponseID, v))
}

// DonorResponseIDHasSuffix applies the HasSuffix predicate on the "donor_response_id" field.
func DonorResponseIDHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldDonorResponseID, v))
}

// DonorResponseIDIsNil applies the IsNil predicate on the "donor_response_id" field.
func DonorResponseIDIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldDonorResponseID))
}

// DonorResponseIDNotNil applies the NotNil predicate on the "donor_response_id" field.
func DonorResponseIDNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldDonorResponseID))
}

// DonorResponseIDEqualFold applies the EqualFold predicate on the "donor_response_id" field.
func DonorResponseIDEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldDonorResponseID, v))
}

// DonorResponseIDContainsFold applies the ContainsFold predicate on the "donor_response_id" field.
func DonorResponseIDContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldDonorResponseID, v))
}

// PartnerNameEQ applies the EQ predicate on the "partner_name" field.
func PartnerNameEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPartnerName, v))
}

// PartnerNameNEQ applies the NEQ predicate on the "partner_name" field.
func PartnerNameNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldPartnerName, v))
}

// PartnerNameIn applies the In predicate on the "partner_name" field.
func PartnerNameIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldPartnerName, vs...))
}

// PartnerNameNotIn applies the NotIn predicate on the "partner_name" field.
func PartnerNameNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldPartnerName, vs...))
}

// PartnerNameGT applies the GT predicate on the "partner_name" field.
func PartnerNameGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldPartnerName, v))
}

// PartnerNameGTE applies the GTE predicate on the "partner_name" field.
func PartnerNameGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldPartnerName, v))
}

// PartnerNameLT applies the LT predicate on the "partner_name" field.
func PartnerNameLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldPartnerName, v))
}

// PartnerNameLTE applies the LTE predicate on the "partner_name" field.
func PartnerNameLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldPartnerName, v))
}

// PartnerNameContains applies the Contains predicate on the "partner_name" field.
func PartnerNameContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldPartnerName, v))
}

// PartnerNameHasPrefix applies the HasPrefix predicate on the "partner_name" field.
func PartnerNameHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldPartnerName, v))
}

// PartnerNameHasSuffix applies the HasSuffix predicate on the "partner_name" field.
func PartnerNameHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldPartnerName, v))
}

// PartnerNameEqualFold applies the EqualFold predicate on the "partner_name" field.
func PartnerNameEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldPartnerName, v))
}

// PartnerNameContainsFold applies the ContainsFold predicate on the "partner_name" field.
func PartnerNameContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldPartnerName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldDescription, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v Target) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v Target) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...Target) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...Target) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldTarget, vs...))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v Recipient) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v Recipient) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...Recipient) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...Recipient) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldRecipient, vs...))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v Category) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v Category) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...Category) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...Category) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldCategory, vs...))
}

// SubcategoryEQ applies the EQ predicate on the "subcategory" field.
func SubcategoryEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldSubcategory, v))
}

// SubcategoryNEQ applies the NEQ predicate on the "subcategory" field.
func SubcategoryNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldSubcategory, v))
}

// SubcategoryIn applies the In predicate on the "subcategory" field.
func SubcategoryIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldSubcategory, vs...))
}

// SubcategoryNotIn applies the NotIn predicate on the "subcategory" field.
func SubcategoryNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldSubcategory, vs...))
}

// SubcategoryGT applies the GT predicate on the "subcategory" field.
func SubcategoryGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldSubcategory, v))
}

// SubcategoryGTE applies the GTE predicate on the "subcategory" field.
func SubcategoryGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldSubcategory, v))
}

// SubcategoryLT applies the LT predicate on the "subcategory" field.
func SubcategoryLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldSubcategory, v))
}

// SubcategoryLTE applies the LTE predicate on the "subcategory" field.
func SubcategoryLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldSubcategory, v))
}

// SubcategoryContains applies the Contains predicate on the "subcategory" field.
func SubcategoryContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldSubcategory, v))
}

// SubcategoryHasPrefix applies the HasPrefix predicate on the "subcategory" field.
func SubcategoryHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldSubcategory, v))
}

// SubcategoryHasSuffix applies the HasSuffix predicate on the "subcategory" field.
func SubcategoryHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldSubcategory, v))
}

// SubcategoryIsNil applies the IsNil predicate on the "subcategory" field.
func SubcategoryIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldSubcategory))
}

// SubcategoryNotNil applies the NotNil predicate on the "subcategory" field.
func SubcategoryNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldSubcategory))
}

// SubcategoryEqualFold applies the EqualFold predicate on the "subcategory" field.
func SubcategoryEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldSubcategory, v))
}

// SubcategoryContainsFold applies the ContainsFold predicate on the "subcategory" field.
func SubcategoryContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldSubcategory, v))
}

// PromoCodeEQ applies the EQ predicate on the "promo_code" field.
func PromoCodeEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPromoCode, v))
}

// PromoCodeNEQ applies the NEQ predicate on the "promo_code" field.
func PromoCodeNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldPromoCode, v))
}

// PromoCodeIn applies the In predicate on the "promo_code" field.
func PromoCodeIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldPromoCode, vs...))
}

// PromoCodeNotIn applies the NotIn predicate on the "promo_code" field.
func PromoCodeNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldPromoCode, vs...))
}

// PromoCodeGT applies the GT predicate on the "promo_code" field.
func PromoCodeGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldPromoCode, v))
}

// PromoCodeGTE applies the GTE predicate on the "promo_code" field.
func PromoCodeGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldPromoCode, v))
}

// PromoCodeLT applies the LT predicate on the "promo_code" field.
func PromoCodeLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldPromoCode, v))
}

// PromoCodeLTE applies the LTE predicate on the "promo_code" field.
func PromoCodeLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldPromoCode, v))
}

// PromoCodeContains applies the Contains predicate on the "promo_code" field.
func PromoCodeContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldPromoCode, v))
}

// PromoCodeHasPrefix applies the HasPrefix predicate on the "promo_code" field.
func PromoCodeHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldPromoCode, v))
}

// PromoCodeHasSuffix applies the HasSuffix predicate on the "promo_code" field.
func PromoCodeHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldPromoCode, v))
}

// PromoCodeEqualFold applies the EqualFold predicate on the "promo_code" field.
func PromoCodeEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldPromoCode, v))
}

// PromoCodeContainsFold applies the ContainsFold predicate on the "promo_code" field.
func PromoCodeContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldPromoCode, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldExpiresAt, v))
}

// PlatformNameEQ applies the EQ predicate on the "platform_name" field.
func PlatformNameEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPlatformName, v))
}

// PlatformNameNEQ applies the NEQ predicate on the "platform_name" field.
func PlatformNameNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldPlatformName, v))
}

// PlatformNameIn applies the In predicate on the "platform_name" field.
func PlatformNameIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldPlatformName, vs...))
}

// PlatformNameNotIn applies the NotIn predicate on the "platform_name" field.
func PlatformNameNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldPlatformName, vs...))
}

// PlatformNameGT applies the GT predicate on the "platform_name" field.
func PlatformNameGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldPlatformName, v))
}

// PlatformNameGTE applies the GTE predicate on the "platform_name" field.
func PlatformNameGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldPlatformName, v))
}

// PlatformNameLT applies the LT predicate on the "platform_name" field.
func PlatformNameLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldPlatformName, v))
}

// PlatformNameLTE applies the LTE predicate on the "platform_name" field.
func PlatformNameLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldPlatformName, v))
}

// PlatformNameContains applies the Contains predicate on the "platform_name" field.
func PlatformNameContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldPlatformName, v))
}

// PlatformNameHasPrefix applies the HasPrefix predicate on the "platform_name" field.
func PlatformNameHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldPlatformName, v))
}

// PlatformNameHasSuffix applies the HasSuffix predicate on the "platform_name" field.
func PlatformNameHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldPlatformName, v))
}

// PlatformNameEqualFold applies the EqualFold predicate on the "platform_name" field.
func PlatformNameEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldPlatformName, v))
}

// PlatformNameContainsFold applies the ContainsFold predicate on the "platform_name" field.
func PlatformNameContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldPlatformName, v))
}

// PlatformURLEQ applies the EQ predicate on the "platform_url" field.
func PlatformURLEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldPlatformURL, v))
}

// PlatformURLNEQ applies the NEQ predicate on the "platform_url" field.
func PlatformURLNEQ(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldPlatformURL, v))
}

// PlatformURLIn applies the In predicate on the "platform_url" field.
func PlatformURLIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldPlatformURL, vs...))
}

// PlatformURLNotIn applies the NotIn predicate on the "platform_url" field.
func PlatformURLNotIn(vs ...string) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldPlatformURL, vs...))
}

// PlatformURLGT applies the GT predicate on the "platform_url" field.
func PlatformURLGT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldPlatformURL, v))
}

// PlatformURLGTE applies the GTE predicate on the "platform_url" field.
func PlatformURLGTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldPlatformURL, v))
}

// PlatformURLLT applies the LT predicate on the "platform_url" field.
func PlatformURLLT(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldPlatformURL, v))
}

// PlatformURLLTE applies the LTE predicate on the "platform_url" field.
func PlatformURLLTE(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldPlatformURL, v))
}

// PlatformURLContains applies the Contains predicate on the "platform_url" field.
func PlatformURLContains(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContains(FieldPlatformURL, v))
}

// PlatformURLHasPrefix applies the HasPrefix predicate on the "platform_url" field.
func PlatformURLHasPrefix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasPrefix(FieldPlatformURL, v))
}

// PlatformURLHasSuffix applies the HasSuffix predicate on the "platform_url" field.
func PlatformURLHasSuffix(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldHasSuffix(FieldPlatformURL, v))
}

// PlatformURLIsNil applies the IsNil predicate on the "platform_url" field.
func PlatformURLIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldPlatformURL))
}

// PlatformURLNotNil applies the NotNil predicate on the "platform_url" field.
func PlatformURLNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldPlatformURL))
}

// PlatformURLEqualFold applies the EqualFold predicate on the "platform_url" field.
func PlatformURLEqualFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldEqualFold(FieldPlatformURL, v))
}

// PlatformURLContainsFold applies the ContainsFold predicate on the "platform_url" field.
func PlatformURLContainsFold(v string) predicate.Bonus {
	return predicate.Bonus(sql.FieldContainsFold(FieldPlatformURL, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v Stage) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v Stage) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...Stage) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...Stage) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldStage, vs...))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.Bonus {
	return predicate.Bonus(sql.FieldLTE(FieldAssignedAt, v))
}

// AssignedAtIsNil applies the IsNil predicate on the "assigned_at" field.
func AssignedAtIsNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldIsNull(FieldAssignedAt))
}

// AssignedAtNotNil applies the NotNil predicate on the "assigned_at" field.
func AssignedAtNotNil() predicate.Bonus {
	return predicate.Bonus(sql.FieldNotNull(FieldAssignedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Bonus {
	return predicate.Bonus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Bonus {
	return predicate.Bonus(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDonorResponse applies the HasEdge predicate on the "donor_response" edge.
func HasDonorResponse() predicate.Bonus {
	return predicate.Bonus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DonorResponseTable, DonorResponseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDonorResponseWith applies the HasEdge predicate on the "donor_response" edge with a given conditions (other predicates).
func HasDonorResponseWith(preds ...predicate.DonorResponse) predicate.Bonus {
	return predicate.Bonus(func(s *sql.Selector) {
		step := newDonorResponseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bonus) predicate.Bonus {
	return predicate.Bonus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bonus) predicate.Bonus {
	return predicate.Bonus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bonus) predicate.Bonus {
	return predicate.Bonus(sql.NotPredicates(p))
}
