syntax = "proto3";

package bloodpool.v1;

message AddToSearchPoolReq {
  string ID = 1;
  string petID = 2;
  string PetType = 3;
  string bloodGroup = 4;
  repeated string bloodComponents = 5;
  float bloodVolume = 6;
  repeated int32 regions = 7;
  bool smallPetsNotifyAllowed = 8;
  int32 priorityLevel = 9;
}

message AddToSearchPoolResp {
  bool status = 1;
}

message GetPetsByCriteriaReq {
  string petType = 1;
  string bloodGroup = 2;
  repeated int32 regions = 3;
}

message PetSearchResult {
  string ID = 1;
  string petID = 2;
  string petType = 3;
  string bloodGroup = 4;
  repeated string bloodComponents = 5;
  float bloodVolume = 6;
  repeated int32 regions = 7;
  bool smallPetsNotifyAllowed = 8;
  int32 priorityLevel = 9;
}

message GetPetsByCriteriaResp {
  repeated PetSearchResult pets = 1;
}

service BloodSerchPool {
  rpc AddPet(AddToSearchPoolReq) returns (AddToSearchPoolResp);
  rpc GetPetsByCriterias(GetPetsByCriteriaReq) returns (GetPetsByCriteriaResp);
}
