services:
  backend:
    image: ghcr.io/artesipov-alt/odnoi-krovi-app/backend:dev # тег :dev
    environment:
      ENV: development # поменял
      DB_HOST: 10.0.0.129
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_DEV} # отдельная dev БД
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_SSLMODE: ${DB_SSLMODE}
      SERVER_PORT: 3000
      REDIS_HOST: redis_prod # Redis на этом же сервере
      REDIS_PORT: 6379
      S3_ENDPOINT: hb.ru-msk.vkcloud-storage.ru
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      MINIAPP_DOMAIN: https://dev.1krovi.app # поменял
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION:-ru-central1}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN_DEV} # dev токен
      MAX_BOT_TOKEN: ${MAX_BOT_TOKEN_DEV} # dev токен
    ports:
      - "3000:3000"
    networks:
      - odnoi_net
      - redis_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  max-bot:
    image: ghcr.io/artesipov-alt/odnoi-krovi-app/max-bot:dev # тег :dev
    environment:
      ENV: development # поменял
      MAX_BOT_TOKEN: ${MAX_BOT_TOKEN_DEV} # dev токен
      INTERNAL_MAX_BOT_SECRET: ${INTERNAL_MAX_BOT_SECRET}
      MINIAPP_DOMAIN: https://dev.1krovi.app # поменял
      API_BASE_URL: https://dev.1krovi.app/api # поменял
      REDIS_HOST: redis_prod # Redis на этом же сервере
      REDIS_PORT: 6379
    networks:
      - odnoi_net
      - redis_default
    restart: unless-stopped

  frontend:
    image: ghcr.io/artesipov-alt/odnoi-krovi-app/frontend:dev # тег :dev
    ports:
      - "80:80" # только 80, без 443
    volumes:
      - ./frontend/Caddyfile.dev:/etc/caddy/Caddyfile # Путь к dev
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - odnoi_net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  odnoi_net:
    driver: bridge
  redis_default:
    external: true
