services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: 10.0.0.129
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
      SERVER_PORT: 3000
      ENVIRONMENT: production
    ports:
      - "3000:3000"
    networks:
      - odnoi_net
    restart: unless-stopped
