version: "3"

env:
  ENV_FILE: .env

tasks:
  generate-api:
    desc: "Сгенерировать типы API Backend для TypeScript"
    cmds:
      - task: generate-swagger
      - openapi-generator generate -i ./backend/docs/swagger.json -g typescript-fetch -o shared/ts

  generate-swagger:
    desc: "Сгенерировать Swagger документацию"
    cmds:
      - swag init -g ./backend/cmd/server/main.go -o ./backend/docs

  # generate-proto:
  #   desc: "Сгенерировать прото-типы от микросервиса"
  #   cmds:
  #     - mkdir -p shared/go/blood-microservice
  #     - cp -a microservices/blood-microservice/buf.yaml shared/go/blood-microservice/buf.yaml
  #     - cp -a microservices/blood-microservice/buf.gen.yaml shared/go/blood-microservice/buf.gen.yaml
  #     - rm -rf shared/go/blood-microservice/api
  #     - cp -a microservices/blood-microservice/api shared/go/blood-microservice/api
  #     - task: gproto

  # gproto:
  #   internal: true
  #   dir: shared/go/blood-microservice
  #   cmds:
  #     - go mod init github.com/artesipov-alt/odnoi-krovi-app/shared/go/blood-microservice
  #     - buf generate
  #     - go mod tidy

  install:
    desc: "Установить все зависимости проекта"
    cmds:
      - task: install-backend
      - task: install-microservice
      - task: install-frontend
      - task: install-bot

  install-backend:
    desc: "Установить зависимости backend"
    dir: backend
    cmds:
      - go mod tidy

  install-microservice:
    desc: "Установить зависимости backend"
    dir: microservices/blood-microservice
    cmds:
      - go mod tidy

  install-frontend:
    desc: "Установить зависимости frontend"
    dir: frontend
    cmds:
      - bun install

  install-bot:
    desc: "Установить зависимости bot"
    dir: bot
    cmds:
      - bun install

  # Запуск в режиме разработки
  dev:
    desc: "Запустить все сервисы в режиме разработки"
    cmds:
      - task: dev-backend
      - task: dev-frontend
      - task: dev-bot

  dev-backend:
    desc: "Запустить backend в dev режиме"
    dir: backend
    cmds:
      - go run cmd/server/main.go

  dev-micoservice:
    desc: "Запустить миеросервис в dev режиме"
    dir: microservices/blood-microservice
    cmds:
      - go run cmd/microservice/main.go

  dev-frontend:
    desc: "Запустить frontend в dev режиме"
    dir: frontend
    cmds:
      - npm run dev

  dev-bot:
    desc: "Запустить bot в dev режиме"
    dir: bot
    cmds:
      - bun run dev

  # Сборка проекта
  build:
    desc: "Собрать все компоненты проекта"
    cmds:
      - task: build-backend
      - task: build-frontend
      - task: build-bot

  build-backend:
    desc: "Собрать backend"
    dir: backend
    cmds:
      - go build -o app/server cmd/server/main.go

  build-frontend:
    desc: "Собрать frontend"
    dir: frontend
    cmds:
      - rm -rf build
      - bun run build

  build-bot:
    desc: "Собрать bot"
    dir: bot
    cmds:
      - rm -rf dist
      - bun run build
