/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.3.9
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyForBloodRequestBody
 */
export interface ApplyForBloodRequestBody {
    [key: string]: any | any;
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ApplyForBloodRequestBody
     */
    readonly $schema?: string;
    /**
     * Условия донации
     * @type {Array<string>}
     * @memberof ApplyForBloodRequestBody
     */
    conditions?: Array<ApplyForBloodRequestBodyConditionsEnum>;
    /**
     * ID питомца-донора
     * @type {string}
     * @memberof ApplyForBloodRequestBody
     */
    donorId: string;
}


/**
 * @export
 */
export const ApplyForBloodRequestBodyConditionsEnum = {
    Free: 'free',
    Paid: 'paid',
    Food: 'food',
    TaxiCompensation: 'taxi_compensation'
} as const;
export type ApplyForBloodRequestBodyConditionsEnum = typeof ApplyForBloodRequestBodyConditionsEnum[keyof typeof ApplyForBloodRequestBodyConditionsEnum];


/**
 * Check if a given object implements the ApplyForBloodRequestBody interface.
 */
export function instanceOfApplyForBloodRequestBody(value: object): value is ApplyForBloodRequestBody {
    if (!('donorId' in value) || value['donorId'] === undefined) return false;
    return true;
}

export function ApplyForBloodRequestBodyFromJSON(json: any): ApplyForBloodRequestBody {
    return ApplyForBloodRequestBodyFromJSONTyped(json, false);
}

export function ApplyForBloodRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyForBloodRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'conditions': json['conditions'] == null ? undefined : json['conditions'],
        'donorId': json['donorId'],
    };
}

export function ApplyForBloodRequestBodyToJSON(json: any): ApplyForBloodRequestBody {
    return ApplyForBloodRequestBodyToJSONTyped(json, false);
}

export function ApplyForBloodRequestBodyToJSONTyped(value?: Omit<ApplyForBloodRequestBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'conditions': value['conditions'],
        'donorId': value['donorId'],
    };
}

