/* tslint:disable */
/* eslint-disable */
/**
 * 1krovi.app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BloodSearchPetResponse
 */
export interface BloodSearchPetResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    readonly $schema?: string;
    /**
     * ID запроса на поиск крови
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    id: string;
    /**
     * ID питомца, для которого создан запрос
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    petId: string;
    /**
     * Текущий статус запроса
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    status: string;
}

/**
 * Check if a given object implements the BloodSearchPetResponse interface.
 */
export function instanceOfBloodSearchPetResponse(value: object): value is BloodSearchPetResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BloodSearchPetResponseFromJSON(json: any): BloodSearchPetResponse {
    return BloodSearchPetResponseFromJSONTyped(json, false);
}

export function BloodSearchPetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodSearchPetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'id': json['id'],
        'petId': json['petId'],
        'status': json['status'],
    };
}

export function BloodSearchPetResponseToJSON(json: any): BloodSearchPetResponse {
    return BloodSearchPetResponseToJSONTyped(json, false);
}

export function BloodSearchPetResponseToJSONTyped(value?: Omit<BloodSearchPetResponse, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'petId': value['petId'],
        'status': value['status'],
    };
}

