/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 2.1.6
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BloodSearchPetResponse
 */
export interface BloodSearchPetResponse {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    readonly $schema?: string;
    /**
     * ID запроса на поиск крови
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    readonly id: string;
    /**
     * ID питомца, для которого создан запрос
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    petId: string;
    /**
     * Текущий статус запроса
     * @type {string}
     * @memberof BloodSearchPetResponse
     */
    status: BloodSearchPetResponseStatusEnum;
}


/**
 * @export
 */
export const BloodSearchPetResponseStatusEnum = {
    Active: 'active',
    Closed: 'closed',
    Draft: 'draft'
} as const;
export type BloodSearchPetResponseStatusEnum = typeof BloodSearchPetResponseStatusEnum[keyof typeof BloodSearchPetResponseStatusEnum];


/**
 * Check if a given object implements the BloodSearchPetResponse interface.
 */
export function instanceOfBloodSearchPetResponse(value: object): value is BloodSearchPetResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BloodSearchPetResponseFromJSON(json: any): BloodSearchPetResponse {
    return BloodSearchPetResponseFromJSONTyped(json, false);
}

export function BloodSearchPetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodSearchPetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'id': json['id'],
        'petId': json['petId'],
        'status': json['status'],
    };
}

export function BloodSearchPetResponseToJSON(json: any): BloodSearchPetResponse {
    return BloodSearchPetResponseToJSONTyped(json, false);
}

export function BloodSearchPetResponseToJSONTyped(value?: Omit<BloodSearchPetResponse, '$schema'|'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'petId': value['petId'],
        'status': value['status'],
    };
}

