/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.25.2
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportBonusesResult
 */
export interface ImportBonusesResult {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ImportBonusesResult
     */
    readonly $schema?: string;
    /**
     * Список сообщений об ошибках для пропущенных строк
     * @type {Array<string>}
     * @memberof ImportBonusesResult
     */
    errors?: Array<string> | null;
    /**
     * Количество успешно импортированных бонусов
     * @type {number}
     * @memberof ImportBonusesResult
     */
    imported: number;
    /**
     * Количество пропущенных строк (дубликаты или ошибки)
     * @type {number}
     * @memberof ImportBonusesResult
     */
    skipped: number;
    /**
     * Общее количество обработанных строк данных
     * @type {number}
     * @memberof ImportBonusesResult
     */
    totalRows: number;
}

/**
 * Check if a given object implements the ImportBonusesResult interface.
 */
export function instanceOfImportBonusesResult(value: object): value is ImportBonusesResult {
    if (!('imported' in value) || value['imported'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    return true;
}

export function ImportBonusesResultFromJSON(json: any): ImportBonusesResult {
    return ImportBonusesResultFromJSONTyped(json, false);
}

export function ImportBonusesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportBonusesResult {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'errors': json['errors'] == null ? undefined : json['errors'],
        'imported': json['imported'],
        'skipped': json['skipped'],
        'totalRows': json['totalRows'],
    };
}

export function ImportBonusesResultToJSON(json: any): ImportBonusesResult {
    return ImportBonusesResultToJSONTyped(json, false);
}

export function ImportBonusesResultToJSONTyped(value?: Omit<ImportBonusesResult, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'imported': value['imported'],
        'skipped': value['skipped'],
        'totalRows': value['totalRows'],
    };
}

