/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.3.11
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessengerSignInBody
 */
export interface MessengerSignInBody {
    [key: string]: any | any;
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof MessengerSignInBody
     */
    readonly $schema?: string;
    /**
     * Полное имя пользователя
     * @type {string}
     * @memberof MessengerSignInBody
     */
    fullName?: string;
    /**
     * Метаданные пользователя
     * @type {{ [key: string]: any; }}
     * @memberof MessengerSignInBody
     */
    metaData?: { [key: string]: any; };
    /**
     * ID провайдера
     * @type {string}
     * @memberof MessengerSignInBody
     */
    providerId: string;
}

/**
 * Check if a given object implements the MessengerSignInBody interface.
 */
export function instanceOfMessengerSignInBody(value: object): value is MessengerSignInBody {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function MessengerSignInBodyFromJSON(json: any): MessengerSignInBody {
    return MessengerSignInBodyFromJSONTyped(json, false);
}

export function MessengerSignInBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerSignInBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'metaData': json['metaData'] == null ? undefined : json['metaData'],
        'providerId': json['providerId'],
    };
}

export function MessengerSignInBodyToJSON(json: any): MessengerSignInBody {
    return MessengerSignInBodyToJSONTyped(json, false);
}

export function MessengerSignInBodyToJSONTyped(value?: Omit<MessengerSignInBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'fullName': value['fullName'],
        'metaData': value['metaData'],
        'providerId': value['providerId'],
    };
}

