/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.9.4
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MiniAppSignInBody
 */
export interface MiniAppSignInBody {
    [key: string]: any | any;
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof MiniAppSignInBody
     */
    readonly $schema?: string;
    /**
     * Зашифрованный токен бота для сверки
     * @type {string}
     * @memberof MiniAppSignInBody
     */
    appInitData: string;
    /**
     * Метаданные пользователя
     * @type {{ [key: string]: any; }}
     * @memberof MiniAppSignInBody
     */
    metaData?: { [key: string]: any; };
}

/**
 * Check if a given object implements the MiniAppSignInBody interface.
 */
export function instanceOfMiniAppSignInBody(value: object): value is MiniAppSignInBody {
    if (!('appInitData' in value) || value['appInitData'] === undefined) return false;
    return true;
}

export function MiniAppSignInBodyFromJSON(json: any): MiniAppSignInBody {
    return MiniAppSignInBodyFromJSONTyped(json, false);
}

export function MiniAppSignInBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiniAppSignInBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'appInitData': json['appInitData'],
        'metaData': json['metaData'] == null ? undefined : json['metaData'],
    };
}

export function MiniAppSignInBodyToJSON(json: any): MiniAppSignInBody {
    return MiniAppSignInBodyToJSONTyped(json, false);
}

export function MiniAppSignInBodyToJSONTyped(value?: Omit<MiniAppSignInBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'appInitData': value['appInitData'],
        'metaData': value['metaData'],
    };
}

