/* tslint:disable */
/* eslint-disable */
/**
 * 1krovi.app
 * API сервиса однойкрови.рф для донороcства крови и помощи животным
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Данные питомца-реципиента для пула поиска крови
 * @export
 * @interface ModelsBloodSearchPetRequest
 */
export interface ModelsBloodSearchPetRequest {
    /**
     * Необходимые компоненты крови
     * @type {Array<number>}
     * @memberof ModelsBloodSearchPetRequest
     */
    bloodComponents?: Array<number>;
    /**
     * Группа крови животного
     * @type {Array<string>}
     * @memberof ModelsBloodSearchPetRequest
     */
    bloodGroup?: Array<string>;
    /**
     * Необходимый объем крови в мл
     * @type {number}
     * @memberof ModelsBloodSearchPetRequest
     */
    bloodVolumeNeeded?: number;
    /**
     * Зарезервированный объем крови в мл
     * @type {number}
     * @memberof ModelsBloodSearchPetRequest
     */
    bloodVolumeReserved?: number;
    /**
     * Описание
     * @type {string}
     * @memberof ModelsBloodSearchPetRequest
     */
    description?: string;
    /**
     * ID питомца в системе
     * @type {string}
     * @memberof ModelsBloodSearchPetRequest
     */
    petId?: string;
    /**
     * Тип животного (dog, cat и т.д.)
     * @type {string}
     * @memberof ModelsBloodSearchPetRequest
     */
    petType?: string;
    /**
     * ID регионов для поиска доноров
     * @type {Array<number>}
     * @memberof ModelsBloodSearchPetRequest
     */
    regions?: Array<number>;
    /**
     * Разрешить уведомления для маленьких питомцев
     * @type {boolean}
     * @memberof ModelsBloodSearchPetRequest
     */
    smallPetsNotifyAllowed?: boolean;
    /**
     * Статус поиска
     * @type {string}
     * @memberof ModelsBloodSearchPetRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the ModelsBloodSearchPetRequest interface.
 */
export function instanceOfModelsBloodSearchPetRequest(value: object): value is ModelsBloodSearchPetRequest {
    return true;
}

export function ModelsBloodSearchPetRequestFromJSON(json: any): ModelsBloodSearchPetRequest {
    return ModelsBloodSearchPetRequestFromJSONTyped(json, false);
}

export function ModelsBloodSearchPetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsBloodSearchPetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bloodComponents': json['bloodComponents'] == null ? undefined : json['bloodComponents'],
        'bloodGroup': json['bloodGroup'] == null ? undefined : json['bloodGroup'],
        'bloodVolumeNeeded': json['bloodVolumeNeeded'] == null ? undefined : json['bloodVolumeNeeded'],
        'bloodVolumeReserved': json['bloodVolumeReserved'] == null ? undefined : json['bloodVolumeReserved'],
        'description': json['description'] == null ? undefined : json['description'],
        'petId': json['petId'] == null ? undefined : json['petId'],
        'petType': json['petType'] == null ? undefined : json['petType'],
        'regions': json['regions'] == null ? undefined : json['regions'],
        'smallPetsNotifyAllowed': json['smallPetsNotifyAllowed'] == null ? undefined : json['smallPetsNotifyAllowed'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ModelsBloodSearchPetRequestToJSON(json: any): ModelsBloodSearchPetRequest {
    return ModelsBloodSearchPetRequestToJSONTyped(json, false);
}

export function ModelsBloodSearchPetRequestToJSONTyped(value?: ModelsBloodSearchPetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bloodComponents': value['bloodComponents'],
        'bloodGroup': value['bloodGroup'],
        'bloodVolumeNeeded': value['bloodVolumeNeeded'],
        'bloodVolumeReserved': value['bloodVolumeReserved'],
        'description': value['description'],
        'petId': value['petId'],
        'petType': value['petType'],
        'regions': value['regions'],
        'smallPetsNotifyAllowed': value['smallPetsNotifyAllowed'],
        'status': value['status'],
    };
}

