/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.4.3
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchingDonor } from './MatchingDonor';
import {
    MatchingDonorFromJSON,
    MatchingDonorFromJSONTyped,
    MatchingDonorToJSON,
    MatchingDonorToJSONTyped,
} from './MatchingDonor';

/**
 * 
 * @export
 * @interface RecipientDetail
 */
export interface RecipientDetail {
    [key: string]: any | any;
    /**
     * Группа крови реципиента
     * @type {string}
     * @memberof RecipientDetail
     */
    bloodGroupName: string;
    /**
     * Необходимый остаток объема крови в мл
     * @type {number}
     * @memberof RecipientDetail
     */
    bloodVolumeRemaining: number;
    /**
     * ID заявки
     * @type {string}
     * @memberof RecipientDetail
     */
    id: string;
    /**
     * Список ID подходящих доноров
     * @type {Array<MatchingDonor>}
     * @memberof RecipientDetail
     */
    matchingDonors?: Array<MatchingDonor>;
    /**
     * ID питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    petId: string;
    /**
     * Имя питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    petName: string;
    /**
     * Список URL фотографий
     * @type {Array<string>}
     * @memberof RecipientDetail
     */
    photoUrls?: Array<string>;
    /**
     * Приоритетный поиск
     * @type {boolean}
     * @memberof RecipientDetail
     */
    prioritySearch: boolean;
    /**
     * Статус заявки
     * @type {string}
     * @memberof RecipientDetail
     */
    status: RecipientDetailStatusEnum;
}


/**
 * @export
 */
export const RecipientDetailStatusEnum = {
    Active: 'active',
    Closed: 'closed',
    Draft: 'draft'
} as const;
export type RecipientDetailStatusEnum = typeof RecipientDetailStatusEnum[keyof typeof RecipientDetailStatusEnum];


/**
 * Check if a given object implements the RecipientDetail interface.
 */
export function instanceOfRecipientDetail(value: object): value is RecipientDetail {
    if (!('bloodGroupName' in value) || value['bloodGroupName'] === undefined) return false;
    if (!('bloodVolumeRemaining' in value) || value['bloodVolumeRemaining'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    if (!('petName' in value) || value['petName'] === undefined) return false;
    if (!('prioritySearch' in value) || value['prioritySearch'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RecipientDetailFromJSON(json: any): RecipientDetail {
    return RecipientDetailFromJSONTyped(json, false);
}

export function RecipientDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientDetail {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'bloodGroupName': json['bloodGroupName'],
        'bloodVolumeRemaining': json['bloodVolumeRemaining'],
        'id': json['id'],
        'matchingDonors': json['matchingDonors'] == null ? undefined : ((json['matchingDonors'] as Array<any>).map(MatchingDonorFromJSON)),
        'petId': json['petId'],
        'petName': json['petName'],
        'photoUrls': json['photoUrls'] == null ? undefined : json['photoUrls'],
        'prioritySearch': json['prioritySearch'],
        'status': json['status'],
    };
}

export function RecipientDetailToJSON(json: any): RecipientDetail {
    return RecipientDetailToJSONTyped(json, false);
}

export function RecipientDetailToJSONTyped(value?: RecipientDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'bloodGroupName': value['bloodGroupName'],
        'bloodVolumeRemaining': value['bloodVolumeRemaining'],
        'id': value['id'],
        'matchingDonors': value['matchingDonors'] == null ? undefined : ((value['matchingDonors'] as Array<any>).map(MatchingDonorToJSON)),
        'petId': value['petId'],
        'petName': value['petName'],
        'photoUrls': value['photoUrls'],
        'prioritySearch': value['prioritySearch'],
        'status': value['status'],
    };
}

