/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.19.0
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedInfo } from './AdvancedInfo';
import {
    AdvancedInfoFromJSON,
    AdvancedInfoFromJSONTyped,
    AdvancedInfoToJSON,
    AdvancedInfoToJSONTyped,
} from './AdvancedInfo';
import type { MatchingDonor } from './MatchingDonor';
import {
    MatchingDonorFromJSON,
    MatchingDonorFromJSONTyped,
    MatchingDonorToJSON,
    MatchingDonorToJSONTyped,
} from './MatchingDonor';
import type { DefaultDonorPrefs } from './DefaultDonorPrefs';
import {
    DefaultDonorPrefsFromJSON,
    DefaultDonorPrefsFromJSONTyped,
    DefaultDonorPrefsToJSON,
    DefaultDonorPrefsToJSONTyped,
} from './DefaultDonorPrefs';
import type { Bonus } from './Bonus';
import {
    BonusFromJSON,
    BonusFromJSONTyped,
    BonusToJSON,
    BonusToJSONTyped,
} from './Bonus';

/**
 * 
 * @export
 * @interface RecipientDetail
 */
export interface RecipientDetail {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof RecipientDetail
     */
    readonly $schema?: string;
    /**
     * Дополнительная информация
     * @type {AdvancedInfo}
     * @memberof RecipientDetail
     */
    advancedInfo?: AdvancedInfo;
    /**
     * Доступные бонусы
     * @type {Array<Bonus>}
     * @memberof RecipientDetail
     */
    availableBonuses?: Array<Bonus> | null;
    /**
     * Группа крови реципиента
     * @type {string}
     * @memberof RecipientDetail
     */
    bloodGroupName: string;
    /**
     * Необходимый объем крови в мл
     * @type {number}
     * @memberof RecipientDetail
     */
    bloodVolumeNeeded?: number;
    /**
     * Необходимый остаток объема крови в мл
     * @type {number}
     * @memberof RecipientDetail
     */
    bloodVolumeRemaining?: number;
    /**
     * Зарезервированный объем крови в мл
     * @type {number}
     * @memberof RecipientDetail
     */
    bloodVolumeReserved: number;
    /**
     * Дата создания
     * @type {Date}
     * @memberof RecipientDetail
     */
    readonly createdAt?: Date;
    /**
     * Настройки донора по умолчанию
     * @type {DefaultDonorPrefs}
     * @memberof RecipientDetail
     */
    defaultPrefs?: DefaultDonorPrefs;
    /**
     * Дата удаления
     * @type {Date}
     * @memberof RecipientDetail
     */
    readonly deletedAt?: Date;
    /**
     * ID заявки
     * @type {string}
     * @memberof RecipientDetail
     */
    id: string;
    /**
     * Включить неизвестную группу крови
     * @type {boolean}
     * @memberof RecipientDetail
     */
    includeUnknownBloodGroup: boolean;
    /**
     * Список ID подходящих доноров
     * @type {Array<MatchingDonor>}
     * @memberof RecipientDetail
     */
    matchingDonors?: Array<MatchingDonor> | null;
    /**
     * Имя владельца
     * @type {string}
     * @memberof RecipientDetail
     */
    ownerName?: string;
    /**
     * ID питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    petId: string;
    /**
     * Имя питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    petName: string;
    /**
     * Тип питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    petType: RecipientDetailPetTypeEnum;
    /**
     * Список URL фотографий
     * @type {Array<string>}
     * @memberof RecipientDetail
     */
    photoUrls?: Array<string> | null;
    /**
     * Приоритетный поиск
     * @type {boolean}
     * @memberof RecipientDetail
     */
    prioritySearch?: boolean;
    /**
     * Привилегия питомца
     * @type {string}
     * @memberof RecipientDetail
     */
    privilege?: RecipientDetailPrivilegeEnum;
    /**
     * Список регионов
     * @type {Array<string>}
     * @memberof RecipientDetail
     */
    regions?: Array<string> | null;
    /**
     * Список искомых групп крови
     * @type {Array<string>}
     * @memberof RecipientDetail
     */
    searchingBloodNames?: Array<string> | null;
    /**
     * Разрешить уведомления для мелких питомцев
     * @type {boolean}
     * @memberof RecipientDetail
     */
    smallPetsNotifyAllowed: boolean;
    /**
     * Статус заявки
     * @type {string}
     * @memberof RecipientDetail
     */
    status: RecipientDetailStatusEnum;
    /**
     * Дата обновления
     * @type {Date}
     * @memberof RecipientDetail
     */
    readonly updatedAt?: Date;
}


/**
 * @export
 */
export const RecipientDetailPetTypeEnum = {
    Dog: 'dog',
    Cat: 'cat'
} as const;
export type RecipientDetailPetTypeEnum = typeof RecipientDetailPetTypeEnum[keyof typeof RecipientDetailPetTypeEnum];

/**
 * @export
 */
export const RecipientDetailPrivilegeEnum = {
    Artist: 'artist',
    Therapist: 'therapist',
    FormerDonor: 'former_donor',
    GuideDog: 'guide_dog',
    PrioritySearch: 'priority_search'
} as const;
export type RecipientDetailPrivilegeEnum = typeof RecipientDetailPrivilegeEnum[keyof typeof RecipientDetailPrivilegeEnum];

/**
 * @export
 */
export const RecipientDetailStatusEnum = {
    Active: 'active',
    Closed: 'closed',
    ReservedFull: 'reserved_full',
    Draft: 'draft'
} as const;
export type RecipientDetailStatusEnum = typeof RecipientDetailStatusEnum[keyof typeof RecipientDetailStatusEnum];


/**
 * Check if a given object implements the RecipientDetail interface.
 */
export function instanceOfRecipientDetail(value: object): value is RecipientDetail {
    if (!('bloodGroupName' in value) || value['bloodGroupName'] === undefined) return false;
    if (!('bloodVolumeReserved' in value) || value['bloodVolumeReserved'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('includeUnknownBloodGroup' in value) || value['includeUnknownBloodGroup'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    if (!('petName' in value) || value['petName'] === undefined) return false;
    if (!('petType' in value) || value['petType'] === undefined) return false;
    if (!('smallPetsNotifyAllowed' in value) || value['smallPetsNotifyAllowed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RecipientDetailFromJSON(json: any): RecipientDetail {
    return RecipientDetailFromJSONTyped(json, false);
}

export function RecipientDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientDetail {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'advancedInfo': json['advancedInfo'] == null ? undefined : AdvancedInfoFromJSON(json['advancedInfo']),
        'availableBonuses': json['availableBonuses'] == null ? undefined : ((json['availableBonuses'] as Array<any>).map(BonusFromJSON)),
        'bloodGroupName': json['bloodGroupName'],
        'bloodVolumeNeeded': json['bloodVolumeNeeded'] == null ? undefined : json['bloodVolumeNeeded'],
        'bloodVolumeRemaining': json['bloodVolumeRemaining'] == null ? undefined : json['bloodVolumeRemaining'],
        'bloodVolumeReserved': json['bloodVolumeReserved'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'defaultPrefs': json['defaultPrefs'] == null ? undefined : DefaultDonorPrefsFromJSON(json['defaultPrefs']),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'id': json['id'],
        'includeUnknownBloodGroup': json['includeUnknownBloodGroup'],
        'matchingDonors': json['matchingDonors'] == null ? undefined : ((json['matchingDonors'] as Array<any>).map(MatchingDonorFromJSON)),
        'ownerName': json['ownerName'] == null ? undefined : json['ownerName'],
        'petId': json['petId'],
        'petName': json['petName'],
        'petType': json['petType'],
        'photoUrls': json['photoUrls'] == null ? undefined : json['photoUrls'],
        'prioritySearch': json['prioritySearch'] == null ? undefined : json['prioritySearch'],
        'privilege': json['privilege'] == null ? undefined : json['privilege'],
        'regions': json['regions'] == null ? undefined : json['regions'],
        'searchingBloodNames': json['searchingBloodNames'] == null ? undefined : json['searchingBloodNames'],
        'smallPetsNotifyAllowed': json['smallPetsNotifyAllowed'],
        'status': json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function RecipientDetailToJSON(json: any): RecipientDetail {
    return RecipientDetailToJSONTyped(json, false);
}

export function RecipientDetailToJSONTyped(value?: Omit<RecipientDetail, '$schema'|'createdAt'|'deletedAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advancedInfo': AdvancedInfoToJSON(value['advancedInfo']),
        'availableBonuses': value['availableBonuses'] == null ? undefined : ((value['availableBonuses'] as Array<any>).map(BonusToJSON)),
        'bloodGroupName': value['bloodGroupName'],
        'bloodVolumeNeeded': value['bloodVolumeNeeded'],
        'bloodVolumeRemaining': value['bloodVolumeRemaining'],
        'bloodVolumeReserved': value['bloodVolumeReserved'],
        'defaultPrefs': DefaultDonorPrefsToJSON(value['defaultPrefs']),
        'id': value['id'],
        'includeUnknownBloodGroup': value['includeUnknownBloodGroup'],
        'matchingDonors': value['matchingDonors'] == null ? undefined : ((value['matchingDonors'] as Array<any>).map(MatchingDonorToJSON)),
        'ownerName': value['ownerName'],
        'petId': value['petId'],
        'petName': value['petName'],
        'petType': value['petType'],
        'photoUrls': value['photoUrls'],
        'prioritySearch': value['prioritySearch'],
        'privilege': value['privilege'],
        'regions': value['regions'],
        'searchingBloodNames': value['searchingBloodNames'],
        'smallPetsNotifyAllowed': value['smallPetsNotifyAllowed'],
        'status': value['status'],
    };
}

