/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.14.10
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePetResult
 */
export interface UpdatePetResult {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdatePetResult
     */
    readonly $schema?: string;
    /**
     * ID обновленного питомца
     * @type {string}
     * @memberof UpdatePetResult
     */
    id: string;
    /**
     * Дата обновления
     * @type {Date}
     * @memberof UpdatePetResult
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the UpdatePetResult interface.
 */
export function instanceOfUpdatePetResult(value: object): value is UpdatePetResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdatePetResultFromJSON(json: any): UpdatePetResult {
    return UpdatePetResultFromJSONTyped(json, false);
}

export function UpdatePetResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePetResult {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'id': json['id'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function UpdatePetResultToJSON(json: any): UpdatePetResult {
    return UpdatePetResultToJSONTyped(json, false);
}

export function UpdatePetResultToJSONTyped(value?: Omit<UpdatePetResult, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

