/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.2.0
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadItem
 */
export interface UploadItem {
    /**
     * Путь к файлу в хранилище
     * @type {string}
     * @memberof UploadItem
     */
    path: string;
    /**
     * Подписанная ссылка для загрузки файла
     * @type {string}
     * @memberof UploadItem
     */
    url: string;
}

/**
 * Check if a given object implements the UploadItem interface.
 */
export function instanceOfUploadItem(value: object): value is UploadItem {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function UploadItemFromJSON(json: any): UploadItem {
    return UploadItemFromJSONTyped(json, false);
}

export function UploadItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadItem {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'url': json['url'],
    };
}

export function UploadItemToJSON(json: any): UploadItem {
    return UploadItemToJSONTyped(json, false);
}

export function UploadItemToJSONTyped(value?: UploadItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'url': value['url'],
    };
}

