/* tslint:disable */
/* eslint-disable */
/**
 * 1krovi.app
 * API сервиса однойкрови.рф для донороcства крови и помощи животным
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UtilsErrorResponse
 */
export interface UtilsErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof UtilsErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the UtilsErrorResponse interface.
 */
export function instanceOfUtilsErrorResponse(value: object): value is UtilsErrorResponse {
    return true;
}

export function UtilsErrorResponseFromJSON(json: any): UtilsErrorResponse {
    return UtilsErrorResponseFromJSONTyped(json, false);
}

export function UtilsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtilsErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UtilsErrorResponseToJSON(json: any): UtilsErrorResponse {
    return UtilsErrorResponseToJSONTyped(json, false);
}

export function UtilsErrorResponseToJSONTyped(value?: UtilsErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

