/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.23.0
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyUserPhoneBody
 */
export interface VerifyUserPhoneBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof VerifyUserPhoneBody
     */
    readonly $schema?: string;
    /**
     * Код подтверждения из SMS
     * @type {string}
     * @memberof VerifyUserPhoneBody
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyUserPhoneBody interface.
 */
export function instanceOfVerifyUserPhoneBody(value: object): value is VerifyUserPhoneBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyUserPhoneBodyFromJSON(json: any): VerifyUserPhoneBody {
    return VerifyUserPhoneBodyFromJSONTyped(json, false);
}

export function VerifyUserPhoneBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyUserPhoneBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'code': json['code'],
    };
}

export function VerifyUserPhoneBodyToJSON(json: any): VerifyUserPhoneBody {
    return VerifyUserPhoneBodyToJSONTyped(json, false);
}

export function VerifyUserPhoneBodyToJSONTyped(value?: Omit<VerifyUserPhoneBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

