syntax = "proto3";

package bloodrequest.v1;

message BloodRequest {
  string pet_id = 1;
  string pet_type = 2;
  repeated string blood_group = 3;
  repeated int32 blood_components = 4;
  int32 blood_volume_needed = 5;
  int32 blood_volume_reserved = 6;
  repeated int32 regions = 7;
  bool small_pets_notify_allowed = 8;
  string description = 9;
  string status = 10;
}

message BloodRequestStatus {
  string pet_id = 1;
  string status = 2;
}

message GetBloodRequests {
  string pet_id = 1;
  string pet_type = 2;
  string blood_group = 3;
  repeated int32 regions = 4;
}

message BloodRequests {
  repeated BloodRequest pets = 1;
}

service BloodRequestPool {
  rpc AddPet(BloodRequest) returns (BloodRequestStatus);
  rpc GetPets(GetBloodRequests) returns (BloodRequests);
}
