// Code generated by ent, DO NOT EDIT.

package bloodgroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldContainsFold(FieldID, id))
}

// BloodGroup applies equality check predicate on the "blood_group" field. It's identical to BloodGroupEQ.
func BloodGroup(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldBloodGroup, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldDescription, v))
}

// PetTypeEQ applies the EQ predicate on the "pet_type" field.
func PetTypeEQ(v PetType) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldPetType, v))
}

// PetTypeNEQ applies the NEQ predicate on the "pet_type" field.
func PetTypeNEQ(v PetType) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNEQ(FieldPetType, v))
}

// PetTypeIn applies the In predicate on the "pet_type" field.
func PetTypeIn(vs ...PetType) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldIn(FieldPetType, vs...))
}

// PetTypeNotIn applies the NotIn predicate on the "pet_type" field.
func PetTypeNotIn(vs ...PetType) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNotIn(FieldPetType, vs...))
}

// BloodGroupEQ applies the EQ predicate on the "blood_group" field.
func BloodGroupEQ(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldBloodGroup, v))
}

// BloodGroupNEQ applies the NEQ predicate on the "blood_group" field.
func BloodGroupNEQ(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNEQ(FieldBloodGroup, v))
}

// BloodGroupIn applies the In predicate on the "blood_group" field.
func BloodGroupIn(vs ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldIn(FieldBloodGroup, vs...))
}

// BloodGroupNotIn applies the NotIn predicate on the "blood_group" field.
func BloodGroupNotIn(vs ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNotIn(FieldBloodGroup, vs...))
}

// BloodGroupGT applies the GT predicate on the "blood_group" field.
func BloodGroupGT(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGT(FieldBloodGroup, v))
}

// BloodGroupGTE applies the GTE predicate on the "blood_group" field.
func BloodGroupGTE(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGTE(FieldBloodGroup, v))
}

// BloodGroupLT applies the LT predicate on the "blood_group" field.
func BloodGroupLT(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLT(FieldBloodGroup, v))
}

// BloodGroupLTE applies the LTE predicate on the "blood_group" field.
func BloodGroupLTE(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLTE(FieldBloodGroup, v))
}

// BloodGroupContains applies the Contains predicate on the "blood_group" field.
func BloodGroupContains(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldContains(FieldBloodGroup, v))
}

// BloodGroupHasPrefix applies the HasPrefix predicate on the "blood_group" field.
func BloodGroupHasPrefix(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldHasPrefix(FieldBloodGroup, v))
}

// BloodGroupHasSuffix applies the HasSuffix predicate on the "blood_group" field.
func BloodGroupHasSuffix(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldHasSuffix(FieldBloodGroup, v))
}

// BloodGroupEqualFold applies the EqualFold predicate on the "blood_group" field.
func BloodGroupEqualFold(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEqualFold(FieldBloodGroup, v))
}

// BloodGroupContainsFold applies the ContainsFold predicate on the "blood_group" field.
func BloodGroupContainsFold(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldContainsFold(FieldBloodGroup, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BloodGroup {
	return predicate.BloodGroup(sql.FieldContainsFold(FieldDescription, v))
}

// HasPets applies the HasEdge predicate on the "pets" edge.
func HasPets() predicate.BloodGroup {
	return predicate.BloodGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PetsTable, PetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetsWith applies the HasEdge predicate on the "pets" edge with a given conditions (other predicates).
func HasPetsWith(preds ...predicate.Pet) predicate.BloodGroup {
	return predicate.BloodGroup(func(s *sql.Selector) {
		step := newPetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BloodGroup) predicate.BloodGroup {
	return predicate.BloodGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BloodGroup) predicate.BloodGroup {
	return predicate.BloodGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BloodGroup) predicate.BloodGroup {
	return predicate.BloodGroup(sql.NotPredicates(p))
}
