// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/donorpreference"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/user"
)

// DonorPreferenceUpdate is the builder for updating DonorPreference entities.
type DonorPreferenceUpdate struct {
	config
	hooks    []Hook
	mutation *DonorPreferenceMutation
}

// Where appends a list predicates to the DonorPreferenceUpdate builder.
func (_u *DonorPreferenceUpdate) Where(ps ...predicate.DonorPreference) *DonorPreferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DonorPreferenceUpdate) SetUpdatedAt(v time.Time) *DonorPreferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DonorPreferenceUpdate) SetDeletedAt(v time.Time) *DonorPreferenceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DonorPreferenceUpdate) SetNillableDeletedAt(v *time.Time) *DonorPreferenceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DonorPreferenceUpdate) ClearDeletedAt() *DonorPreferenceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPreferredLocationIds sets the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdate) SetPreferredLocationIds(v []string) *DonorPreferenceUpdate {
	_u.mutation.SetPreferredLocationIds(v)
	return _u
}

// AppendPreferredLocationIds appends value to the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdate) AppendPreferredLocationIds(v []string) *DonorPreferenceUpdate {
	_u.mutation.AppendPreferredLocationIds(v)
	return _u
}

// ClearPreferredLocationIds clears the value of the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdate) ClearPreferredLocationIds() *DonorPreferenceUpdate {
	_u.mutation.ClearPreferredLocationIds()
	return _u
}

// SetRecoveryPeriodMonths sets the "recovery_period_months" field.
func (_u *DonorPreferenceUpdate) SetRecoveryPeriodMonths(v int) *DonorPreferenceUpdate {
	_u.mutation.ResetRecoveryPeriodMonths()
	_u.mutation.SetRecoveryPeriodMonths(v)
	return _u
}

// SetNillableRecoveryPeriodMonths sets the "recovery_period_months" field if the given value is not nil.
func (_u *DonorPreferenceUpdate) SetNillableRecoveryPeriodMonths(v *int) *DonorPreferenceUpdate {
	if v != nil {
		_u.SetRecoveryPeriodMonths(*v)
	}
	return _u
}

// AddRecoveryPeriodMonths adds value to the "recovery_period_months" field.
func (_u *DonorPreferenceUpdate) AddRecoveryPeriodMonths(v int) *DonorPreferenceUpdate {
	_u.mutation.AddRecoveryPeriodMonths(v)
	return _u
}

// ClearRecoveryPeriodMonths clears the value of the "recovery_period_months" field.
func (_u *DonorPreferenceUpdate) ClearRecoveryPeriodMonths() *DonorPreferenceUpdate {
	_u.mutation.ClearRecoveryPeriodMonths()
	return _u
}

// SetCompensationType sets the "compensation_type" field.
func (_u *DonorPreferenceUpdate) SetCompensationType(v donorpreference.CompensationType) *DonorPreferenceUpdate {
	_u.mutation.SetCompensationType(v)
	return _u
}

// SetNillableCompensationType sets the "compensation_type" field if the given value is not nil.
func (_u *DonorPreferenceUpdate) SetNillableCompensationType(v *donorpreference.CompensationType) *DonorPreferenceUpdate {
	if v != nil {
		_u.SetCompensationType(*v)
	}
	return _u
}

// SetTaxiCompensation sets the "taxi_compensation" field.
func (_u *DonorPreferenceUpdate) SetTaxiCompensation(v bool) *DonorPreferenceUpdate {
	_u.mutation.SetTaxiCompensation(v)
	return _u
}

// SetNillableTaxiCompensation sets the "taxi_compensation" field if the given value is not nil.
func (_u *DonorPreferenceUpdate) SetNillableTaxiCompensation(v *bool) *DonorPreferenceUpdate {
	if v != nil {
		_u.SetTaxiCompensation(*v)
	}
	return _u
}

// SetNotificationFrequency sets the "notification_frequency" field.
func (_u *DonorPreferenceUpdate) SetNotificationFrequency(v donorpreference.NotificationFrequency) *DonorPreferenceUpdate {
	_u.mutation.SetNotificationFrequency(v)
	return _u
}

// SetNillableNotificationFrequency sets the "notification_frequency" field if the given value is not nil.
func (_u *DonorPreferenceUpdate) SetNillableNotificationFrequency(v *donorpreference.NotificationFrequency) *DonorPreferenceUpdate {
	if v != nil {
		_u.SetNotificationFrequency(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *DonorPreferenceUpdate) SetUserID(id string) *DonorPreferenceUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DonorPreferenceUpdate) SetUser(v *User) *DonorPreferenceUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DonorPreferenceMutation object of the builder.
func (_u *DonorPreferenceUpdate) Mutation() *DonorPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DonorPreferenceUpdate) ClearUser() *DonorPreferenceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DonorPreferenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DonorPreferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DonorPreferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DonorPreferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DonorPreferenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := donorpreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DonorPreferenceUpdate) check() error {
	if v, ok := _u.mutation.CompensationType(); ok {
		if err := donorpreference.CompensationTypeValidator(v); err != nil {
			return &ValidationError{Name: "compensation_type", err: fmt.Errorf(`ent: validator failed for field "DonorPreference.compensation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotificationFrequency(); ok {
		if err := donorpreference.NotificationFrequencyValidator(v); err != nil {
			return &ValidationError{Name: "notification_frequency", err: fmt.Errorf(`ent: validator failed for field "DonorPreference.notification_frequency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DonorPreference.user"`)
	}
	return nil
}

func (_u *DonorPreferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(donorpreference.Table, donorpreference.Columns, sqlgraph.NewFieldSpec(donorpreference.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(donorpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(donorpreference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(donorpreference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PreferredLocationIds(); ok {
		_spec.SetField(donorpreference.FieldPreferredLocationIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPreferredLocationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, donorpreference.FieldPreferredLocationIds, value)
		})
	}
	if _u.mutation.PreferredLocationIdsCleared() {
		_spec.ClearField(donorpreference.FieldPreferredLocationIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.RecoveryPeriodMonths(); ok {
		_spec.SetField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoveryPeriodMonths(); ok {
		_spec.AddField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt, value)
	}
	if _u.mutation.RecoveryPeriodMonthsCleared() {
		_spec.ClearField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt)
	}
	if value, ok := _u.mutation.CompensationType(); ok {
		_spec.SetField(donorpreference.FieldCompensationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TaxiCompensation(); ok {
		_spec.SetField(donorpreference.FieldTaxiCompensation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationFrequency(); ok {
		_spec.SetField(donorpreference.FieldNotificationFrequency, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   donorpreference.UserTable,
			Columns: []string{donorpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   donorpreference.UserTable,
			Columns: []string{donorpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{donorpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DonorPreferenceUpdateOne is the builder for updating a single DonorPreference entity.
type DonorPreferenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DonorPreferenceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DonorPreferenceUpdateOne) SetUpdatedAt(v time.Time) *DonorPreferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DonorPreferenceUpdateOne) SetDeletedAt(v time.Time) *DonorPreferenceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DonorPreferenceUpdateOne) SetNillableDeletedAt(v *time.Time) *DonorPreferenceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DonorPreferenceUpdateOne) ClearDeletedAt() *DonorPreferenceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPreferredLocationIds sets the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdateOne) SetPreferredLocationIds(v []string) *DonorPreferenceUpdateOne {
	_u.mutation.SetPreferredLocationIds(v)
	return _u
}

// AppendPreferredLocationIds appends value to the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdateOne) AppendPreferredLocationIds(v []string) *DonorPreferenceUpdateOne {
	_u.mutation.AppendPreferredLocationIds(v)
	return _u
}

// ClearPreferredLocationIds clears the value of the "preferred_location_ids" field.
func (_u *DonorPreferenceUpdateOne) ClearPreferredLocationIds() *DonorPreferenceUpdateOne {
	_u.mutation.ClearPreferredLocationIds()
	return _u
}

// SetRecoveryPeriodMonths sets the "recovery_period_months" field.
func (_u *DonorPreferenceUpdateOne) SetRecoveryPeriodMonths(v int) *DonorPreferenceUpdateOne {
	_u.mutation.ResetRecoveryPeriodMonths()
	_u.mutation.SetRecoveryPeriodMonths(v)
	return _u
}

// SetNillableRecoveryPeriodMonths sets the "recovery_period_months" field if the given value is not nil.
func (_u *DonorPreferenceUpdateOne) SetNillableRecoveryPeriodMonths(v *int) *DonorPreferenceUpdateOne {
	if v != nil {
		_u.SetRecoveryPeriodMonths(*v)
	}
	return _u
}

// AddRecoveryPeriodMonths adds value to the "recovery_period_months" field.
func (_u *DonorPreferenceUpdateOne) AddRecoveryPeriodMonths(v int) *DonorPreferenceUpdateOne {
	_u.mutation.AddRecoveryPeriodMonths(v)
	return _u
}

// ClearRecoveryPeriodMonths clears the value of the "recovery_period_months" field.
func (_u *DonorPreferenceUpdateOne) ClearRecoveryPeriodMonths() *DonorPreferenceUpdateOne {
	_u.mutation.ClearRecoveryPeriodMonths()
	return _u
}

// SetCompensationType sets the "compensation_type" field.
func (_u *DonorPreferenceUpdateOne) SetCompensationType(v donorpreference.CompensationType) *DonorPreferenceUpdateOne {
	_u.mutation.SetCompensationType(v)
	return _u
}

// SetNillableCompensationType sets the "compensation_type" field if the given value is not nil.
func (_u *DonorPreferenceUpdateOne) SetNillableCompensationType(v *donorpreference.CompensationType) *DonorPreferenceUpdateOne {
	if v != nil {
		_u.SetCompensationType(*v)
	}
	return _u
}

// SetTaxiCompensation sets the "taxi_compensation" field.
func (_u *DonorPreferenceUpdateOne) SetTaxiCompensation(v bool) *DonorPreferenceUpdateOne {
	_u.mutation.SetTaxiCompensation(v)
	return _u
}

// SetNillableTaxiCompensation sets the "taxi_compensation" field if the given value is not nil.
func (_u *DonorPreferenceUpdateOne) SetNillableTaxiCompensation(v *bool) *DonorPreferenceUpdateOne {
	if v != nil {
		_u.SetTaxiCompensation(*v)
	}
	return _u
}

// SetNotificationFrequency sets the "notification_frequency" field.
func (_u *DonorPreferenceUpdateOne) SetNotificationFrequency(v donorpreference.NotificationFrequency) *DonorPreferenceUpdateOne {
	_u.mutation.SetNotificationFrequency(v)
	return _u
}

// SetNillableNotificationFrequency sets the "notification_frequency" field if the given value is not nil.
func (_u *DonorPreferenceUpdateOne) SetNillableNotificationFrequency(v *donorpreference.NotificationFrequency) *DonorPreferenceUpdateOne {
	if v != nil {
		_u.SetNotificationFrequency(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *DonorPreferenceUpdateOne) SetUserID(id string) *DonorPreferenceUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DonorPreferenceUpdateOne) SetUser(v *User) *DonorPreferenceUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DonorPreferenceMutation object of the builder.
func (_u *DonorPreferenceUpdateOne) Mutation() *DonorPreferenceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DonorPreferenceUpdateOne) ClearUser() *DonorPreferenceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the DonorPreferenceUpdate builder.
func (_u *DonorPreferenceUpdateOne) Where(ps ...predicate.DonorPreference) *DonorPreferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DonorPreferenceUpdateOne) Select(field string, fields ...string) *DonorPreferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DonorPreference entity.
func (_u *DonorPreferenceUpdateOne) Save(ctx context.Context) (*DonorPreference, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DonorPreferenceUpdateOne) SaveX(ctx context.Context) *DonorPreference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DonorPreferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DonorPreferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DonorPreferenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := donorpreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DonorPreferenceUpdateOne) check() error {
	if v, ok := _u.mutation.CompensationType(); ok {
		if err := donorpreference.CompensationTypeValidator(v); err != nil {
			return &ValidationError{Name: "compensation_type", err: fmt.Errorf(`ent: validator failed for field "DonorPreference.compensation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotificationFrequency(); ok {
		if err := donorpreference.NotificationFrequencyValidator(v); err != nil {
			return &ValidationError{Name: "notification_frequency", err: fmt.Errorf(`ent: validator failed for field "DonorPreference.notification_frequency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DonorPreference.user"`)
	}
	return nil
}

func (_u *DonorPreferenceUpdateOne) sqlSave(ctx context.Context) (_node *DonorPreference, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(donorpreference.Table, donorpreference.Columns, sqlgraph.NewFieldSpec(donorpreference.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DonorPreference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, donorpreference.FieldID)
		for _, f := range fields {
			if !donorpreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != donorpreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(donorpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(donorpreference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(donorpreference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PreferredLocationIds(); ok {
		_spec.SetField(donorpreference.FieldPreferredLocationIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPreferredLocationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, donorpreference.FieldPreferredLocationIds, value)
		})
	}
	if _u.mutation.PreferredLocationIdsCleared() {
		_spec.ClearField(donorpreference.FieldPreferredLocationIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.RecoveryPeriodMonths(); ok {
		_spec.SetField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecoveryPeriodMonths(); ok {
		_spec.AddField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt, value)
	}
	if _u.mutation.RecoveryPeriodMonthsCleared() {
		_spec.ClearField(donorpreference.FieldRecoveryPeriodMonths, field.TypeInt)
	}
	if value, ok := _u.mutation.CompensationType(); ok {
		_spec.SetField(donorpreference.FieldCompensationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TaxiCompensation(); ok {
		_spec.SetField(donorpreference.FieldTaxiCompensation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationFrequency(); ok {
		_spec.SetField(donorpreference.FieldNotificationFrequency, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   donorpreference.UserTable,
			Columns: []string{donorpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   donorpreference.UserTable,
			Columns: []string{donorpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DonorPreference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{donorpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
