// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/user"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/utmhistory"
)

// UtmHistoryUpdate is the builder for updating UtmHistory entities.
type UtmHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *UtmHistoryMutation
}

// Where appends a list predicates to the UtmHistoryUpdate builder.
func (_u *UtmHistoryUpdate) Where(ps ...predicate.UtmHistory) *UtmHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UtmHistoryUpdate) SetUpdatedAt(v time.Time) *UtmHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UtmHistoryUpdate) SetDeletedAt(v time.Time) *UtmHistoryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableDeletedAt(v *time.Time) *UtmHistoryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UtmHistoryUpdate) ClearDeletedAt() *UtmHistoryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UtmHistoryUpdate) SetUserID(v string) *UtmHistoryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUserID(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUtmSource sets the "utm_source" field.
func (_u *UtmHistoryUpdate) SetUtmSource(v string) *UtmHistoryUpdate {
	_u.mutation.SetUtmSource(v)
	return _u
}

// SetNillableUtmSource sets the "utm_source" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUtmSource(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUtmSource(*v)
	}
	return _u
}

// ClearUtmSource clears the value of the "utm_source" field.
func (_u *UtmHistoryUpdate) ClearUtmSource() *UtmHistoryUpdate {
	_u.mutation.ClearUtmSource()
	return _u
}

// SetUtmMedium sets the "utm_medium" field.
func (_u *UtmHistoryUpdate) SetUtmMedium(v string) *UtmHistoryUpdate {
	_u.mutation.SetUtmMedium(v)
	return _u
}

// SetNillableUtmMedium sets the "utm_medium" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUtmMedium(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUtmMedium(*v)
	}
	return _u
}

// ClearUtmMedium clears the value of the "utm_medium" field.
func (_u *UtmHistoryUpdate) ClearUtmMedium() *UtmHistoryUpdate {
	_u.mutation.ClearUtmMedium()
	return _u
}

// SetUtmCampaign sets the "utm_campaign" field.
func (_u *UtmHistoryUpdate) SetUtmCampaign(v string) *UtmHistoryUpdate {
	_u.mutation.SetUtmCampaign(v)
	return _u
}

// SetNillableUtmCampaign sets the "utm_campaign" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUtmCampaign(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUtmCampaign(*v)
	}
	return _u
}

// ClearUtmCampaign clears the value of the "utm_campaign" field.
func (_u *UtmHistoryUpdate) ClearUtmCampaign() *UtmHistoryUpdate {
	_u.mutation.ClearUtmCampaign()
	return _u
}

// SetUtmContent sets the "utm_content" field.
func (_u *UtmHistoryUpdate) SetUtmContent(v string) *UtmHistoryUpdate {
	_u.mutation.SetUtmContent(v)
	return _u
}

// SetNillableUtmContent sets the "utm_content" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUtmContent(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUtmContent(*v)
	}
	return _u
}

// ClearUtmContent clears the value of the "utm_content" field.
func (_u *UtmHistoryUpdate) ClearUtmContent() *UtmHistoryUpdate {
	_u.mutation.ClearUtmContent()
	return _u
}

// SetUtmTerm sets the "utm_term" field.
func (_u *UtmHistoryUpdate) SetUtmTerm(v string) *UtmHistoryUpdate {
	_u.mutation.SetUtmTerm(v)
	return _u
}

// SetNillableUtmTerm sets the "utm_term" field if the given value is not nil.
func (_u *UtmHistoryUpdate) SetNillableUtmTerm(v *string) *UtmHistoryUpdate {
	if v != nil {
		_u.SetUtmTerm(*v)
	}
	return _u
}

// ClearUtmTerm clears the value of the "utm_term" field.
func (_u *UtmHistoryUpdate) ClearUtmTerm() *UtmHistoryUpdate {
	_u.mutation.ClearUtmTerm()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UtmHistoryUpdate) SetUser(v *User) *UtmHistoryUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UtmHistoryMutation object of the builder.
func (_u *UtmHistoryUpdate) Mutation() *UtmHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UtmHistoryUpdate) ClearUser() *UtmHistoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UtmHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UtmHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UtmHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UtmHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UtmHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := utmhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UtmHistoryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UtmHistory.user"`)
	}
	return nil
}

func (_u *UtmHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(utmhistory.Table, utmhistory.Columns, sqlgraph.NewFieldSpec(utmhistory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(utmhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(utmhistory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(utmhistory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UtmSource(); ok {
		_spec.SetField(utmhistory.FieldUtmSource, field.TypeString, value)
	}
	if _u.mutation.UtmSourceCleared() {
		_spec.ClearField(utmhistory.FieldUtmSource, field.TypeString)
	}
	if value, ok := _u.mutation.UtmMedium(); ok {
		_spec.SetField(utmhistory.FieldUtmMedium, field.TypeString, value)
	}
	if _u.mutation.UtmMediumCleared() {
		_spec.ClearField(utmhistory.FieldUtmMedium, field.TypeString)
	}
	if value, ok := _u.mutation.UtmCampaign(); ok {
		_spec.SetField(utmhistory.FieldUtmCampaign, field.TypeString, value)
	}
	if _u.mutation.UtmCampaignCleared() {
		_spec.ClearField(utmhistory.FieldUtmCampaign, field.TypeString)
	}
	if value, ok := _u.mutation.UtmContent(); ok {
		_spec.SetField(utmhistory.FieldUtmContent, field.TypeString, value)
	}
	if _u.mutation.UtmContentCleared() {
		_spec.ClearField(utmhistory.FieldUtmContent, field.TypeString)
	}
	if value, ok := _u.mutation.UtmTerm(); ok {
		_spec.SetField(utmhistory.FieldUtmTerm, field.TypeString, value)
	}
	if _u.mutation.UtmTermCleared() {
		_spec.ClearField(utmhistory.FieldUtmTerm, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   utmhistory.UserTable,
			Columns: []string{utmhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   utmhistory.UserTable,
			Columns: []string{utmhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{utmhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UtmHistoryUpdateOne is the builder for updating a single UtmHistory entity.
type UtmHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UtmHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UtmHistoryUpdateOne) SetUpdatedAt(v time.Time) *UtmHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UtmHistoryUpdateOne) SetDeletedAt(v time.Time) *UtmHistoryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableDeletedAt(v *time.Time) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UtmHistoryUpdateOne) ClearDeletedAt() *UtmHistoryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UtmHistoryUpdateOne) SetUserID(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUserID(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUtmSource sets the "utm_source" field.
func (_u *UtmHistoryUpdateOne) SetUtmSource(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUtmSource(v)
	return _u
}

// SetNillableUtmSource sets the "utm_source" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUtmSource(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUtmSource(*v)
	}
	return _u
}

// ClearUtmSource clears the value of the "utm_source" field.
func (_u *UtmHistoryUpdateOne) ClearUtmSource() *UtmHistoryUpdateOne {
	_u.mutation.ClearUtmSource()
	return _u
}

// SetUtmMedium sets the "utm_medium" field.
func (_u *UtmHistoryUpdateOne) SetUtmMedium(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUtmMedium(v)
	return _u
}

// SetNillableUtmMedium sets the "utm_medium" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUtmMedium(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUtmMedium(*v)
	}
	return _u
}

// ClearUtmMedium clears the value of the "utm_medium" field.
func (_u *UtmHistoryUpdateOne) ClearUtmMedium() *UtmHistoryUpdateOne {
	_u.mutation.ClearUtmMedium()
	return _u
}

// SetUtmCampaign sets the "utm_campaign" field.
func (_u *UtmHistoryUpdateOne) SetUtmCampaign(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUtmCampaign(v)
	return _u
}

// SetNillableUtmCampaign sets the "utm_campaign" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUtmCampaign(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUtmCampaign(*v)
	}
	return _u
}

// ClearUtmCampaign clears the value of the "utm_campaign" field.
func (_u *UtmHistoryUpdateOne) ClearUtmCampaign() *UtmHistoryUpdateOne {
	_u.mutation.ClearUtmCampaign()
	return _u
}

// SetUtmContent sets the "utm_content" field.
func (_u *UtmHistoryUpdateOne) SetUtmContent(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUtmContent(v)
	return _u
}

// SetNillableUtmContent sets the "utm_content" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUtmContent(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUtmContent(*v)
	}
	return _u
}

// ClearUtmContent clears the value of the "utm_content" field.
func (_u *UtmHistoryUpdateOne) ClearUtmContent() *UtmHistoryUpdateOne {
	_u.mutation.ClearUtmContent()
	return _u
}

// SetUtmTerm sets the "utm_term" field.
func (_u *UtmHistoryUpdateOne) SetUtmTerm(v string) *UtmHistoryUpdateOne {
	_u.mutation.SetUtmTerm(v)
	return _u
}

// SetNillableUtmTerm sets the "utm_term" field if the given value is not nil.
func (_u *UtmHistoryUpdateOne) SetNillableUtmTerm(v *string) *UtmHistoryUpdateOne {
	if v != nil {
		_u.SetUtmTerm(*v)
	}
	return _u
}

// ClearUtmTerm clears the value of the "utm_term" field.
func (_u *UtmHistoryUpdateOne) ClearUtmTerm() *UtmHistoryUpdateOne {
	_u.mutation.ClearUtmTerm()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UtmHistoryUpdateOne) SetUser(v *User) *UtmHistoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UtmHistoryMutation object of the builder.
func (_u *UtmHistoryUpdateOne) Mutation() *UtmHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UtmHistoryUpdateOne) ClearUser() *UtmHistoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UtmHistoryUpdate builder.
func (_u *UtmHistoryUpdateOne) Where(ps ...predicate.UtmHistory) *UtmHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UtmHistoryUpdateOne) Select(field string, fields ...string) *UtmHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UtmHistory entity.
func (_u *UtmHistoryUpdateOne) Save(ctx context.Context) (*UtmHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UtmHistoryUpdateOne) SaveX(ctx context.Context) *UtmHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UtmHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UtmHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UtmHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := utmhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UtmHistoryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UtmHistory.user"`)
	}
	return nil
}

func (_u *UtmHistoryUpdateOne) sqlSave(ctx context.Context) (_node *UtmHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(utmhistory.Table, utmhistory.Columns, sqlgraph.NewFieldSpec(utmhistory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UtmHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, utmhistory.FieldID)
		for _, f := range fields {
			if !utmhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != utmhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(utmhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(utmhistory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(utmhistory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UtmSource(); ok {
		_spec.SetField(utmhistory.FieldUtmSource, field.TypeString, value)
	}
	if _u.mutation.UtmSourceCleared() {
		_spec.ClearField(utmhistory.FieldUtmSource, field.TypeString)
	}
	if value, ok := _u.mutation.UtmMedium(); ok {
		_spec.SetField(utmhistory.FieldUtmMedium, field.TypeString, value)
	}
	if _u.mutation.UtmMediumCleared() {
		_spec.ClearField(utmhistory.FieldUtmMedium, field.TypeString)
	}
	if value, ok := _u.mutation.UtmCampaign(); ok {
		_spec.SetField(utmhistory.FieldUtmCampaign, field.TypeString, value)
	}
	if _u.mutation.UtmCampaignCleared() {
		_spec.ClearField(utmhistory.FieldUtmCampaign, field.TypeString)
	}
	if value, ok := _u.mutation.UtmContent(); ok {
		_spec.SetField(utmhistory.FieldUtmContent, field.TypeString, value)
	}
	if _u.mutation.UtmContentCleared() {
		_spec.ClearField(utmhistory.FieldUtmContent, field.TypeString)
	}
	if value, ok := _u.mutation.UtmTerm(); ok {
		_spec.SetField(utmhistory.FieldUtmTerm, field.TypeString, value)
	}
	if _u.mutation.UtmTermCleared() {
		_spec.ClearField(utmhistory.FieldUtmTerm, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   utmhistory.UserTable,
			Columns: []string{utmhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   utmhistory.UserTable,
			Columns: []string{utmhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UtmHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{utmhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
