package seeds

import (
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/bloodgroup"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/breed"
)

// BloodGroupData представляет структуру для данных группы крови
type BloodGroupData struct {
	PetType     bloodgroup.PetType
	BloodGroup  string
	Description string
}

var AllBloodGroups = []BloodGroupData{
	// Группы крови для собак
	{
		PetType:     bloodgroup.PetTypeDog,
		BloodGroup:  "DEA 1+",
		Description: "Универсальный донор для собак с положительным DEA 1+",
	},
	{
		PetType:     bloodgroup.PetTypeDog,
		BloodGroup:  "DEA 1-",
		Description: "Универсальный донор для всех собак",
	},
	{
		PetType:     bloodgroup.PetTypeDog,
		BloodGroup:  "Неизвестная",
		Description: "Неизвестная группа крови у собак",
	},
	// Группы крови для кошек
	{
		PetType:     bloodgroup.PetTypeCat,
		BloodGroup:  "A",
		Description: "Самая распространенная группа крови у кошек",
	},
	{
		PetType:     bloodgroup.PetTypeCat,
		BloodGroup:  "B",
		Description: "Часто встречается у определенных пород (британская, рекс)",
	},
	{
		PetType:     bloodgroup.PetTypeCat,
		BloodGroup:  "AB",
		Description: "Очень редкая группа крови",
	},
	{
		PetType:     bloodgroup.PetTypeCat,
		BloodGroup:  "Неизвестная",
		Description: "Неизвестная группа крови у кошек",
	},
}

// AllBloodComponents содержит все предопределенные компоненты крови
var AllBloodComponents = []string{
	"Цельная кровь",
	"Эритроцитарная масса",
	"Свежезамороженная плазма",
	"Замороженная плазма",
	"Тромбоконцентрат",
	"Обогащенная тромбоцитами плазма",
	"Криопреципитат",
	"Криосупернатант",
}

// LocationData представляет структуру для данных локации
type LocationData struct {
	ID   string
	Name string
}

// AllLocations содержит все предопределенные локации
var AllLocations = []LocationData{
	{ID: "MSK", Name: "Москва"},
	{ID: "MO", Name: "Московская область"},
}

type BreedData struct {
	ID   string
	Name string
	Type breed.Type
}

var Breeds = []BreedData{
	{ID: "MIX_DOG", Name: "МЕТИС", Type: breed.TypeDog},
	{ID: "AUS_SHP", Name: "АВСТРАЛИЙСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "AUS_KLP", Name: "АВСТРАЛИЙСКИЙ КЕЛПИ", Type: breed.TypeDog},
	{ID: "AUS_TER", Name: "АВСТРАЛИЙСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "AUS_HLR", Name: "АВСТРАЛИЙСКИЙ ХИЛЕР", Type: breed.TypeDog},
	{ID: "AUS_SIL", Name: "АВСТРАЛИЙСКИЙ ШЕЛКОВИСТЫЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "AZW", Name: "АЗАВАК", Type: breed.TypeDog},
	{ID: "AKB", Name: "АКБАШ", Type: breed.TypeDog},
	{ID: "AKI", Name: "АКИТА", Type: breed.TypeDog},
	{ID: "ALA_MAL", Name: "АЛЯСКИНСКИЙ МАЛАМУТ", Type: breed.TypeDog},
	{ID: "AME_AKI", Name: "АМЕРИКАНСКАЯ АКИТА", Type: breed.TypeDog},
	{ID: "AME_BND", Name: "АМЕРИКАНСКИЙ БАНДОГ", Type: breed.TypeDog},
	{ID: "AME_BLD", Name: "АМЕРИКАНСКИЙ БУЛЬДОГ", Type: breed.TypeDog},
	{ID: "AME_CKS", Name: "АМЕРИКАНСКИЙ КОКЕР СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "AME_STF", Name: "АМЕРИКАНСКИЙ СТАФФОРДШИРСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "AME_TFX", Name: "АМЕРИКАНСКИЙ ТОЙ ФОКС", Type: breed.TypeDog},
	{ID: "ENG_CKS", Name: "АНГЛИЙСКИЙ КОКЕР СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "ENG_PNT", Name: "АНГЛИЙСКИЙ ПОЙНТЕР", Type: breed.TypeDog},
	{ID: "ENG_SET", Name: "АНГЛИЙСКИЙ СЕТТЕР", Type: breed.TypeDog},
	{ID: "ENG_SPR", Name: "АНГЛИЙСКИЙ СПРИНГЕР СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "ENG_TTR", Name: "АНГЛИЙСКИЙ ТОЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "ANR_GNC", Name: "АНГЛО-РУССКАЯ ГОНЧАЯ", Type: breed.TypeDog},
	{ID: "APZ_ZNH", Name: "АПЕНЦЕЛЛЕР ЗЕННЕНХУНД", Type: breed.TypeDog},
	{ID: "ARG_DOG", Name: "АРГЕНТИНСКИЙ ДОГ", Type: breed.TypeDog},
	{ID: "AFG_ABR", Name: "АФГАНСКАЯ АБОРИГЕННАЯ БОРЗАЯ", Type: breed.TypeDog},
	{ID: "AFG_BRZ", Name: "АФГАНСКАЯ БОРЗАЯ", Type: breed.TypeDog},
	{ID: "AFF_PCH", Name: "АФФЕНПИНЧЕР", Type: breed.TypeDog},
	{ID: "BAV_GRN", Name: "БАВАРСКАЯ ГОРНАЯ ГОНЧАЯ", Type: breed.TypeDog},
	{ID: "BSN", Name: "БАСЕНДЖИ", Type: breed.TypeDog},
	{ID: "BST_HND", Name: "БАССЕТ ХАУНД", Type: breed.TypeDog},
	{ID: "BDL_TER", Name: "БЕДЛИНГТОН ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "BLA_SHV", Name: "БЕЛАЯ ШВЕЙЦАРСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "BEL_OVC", Name: "БЕЛЬГИЙСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "BEL_GRF", Name: "БЕЛЬГИЙСКИЙ ГРИФФОН", Type: breed.TypeDog},
	{ID: "BRN_ZNH", Name: "БЕРНСКИЙ ЗЕННЕНХУНД", Type: breed.TypeDog},
	{ID: "BVR", Name: "БИВЕР", Type: breed.TypeDog},
	{ID: "BGL", Name: "БИГЛЬ", Type: breed.TypeDog},
	{ID: "BSH_FRZ", Name: "БИШОН ФРИЗЕ", Type: breed.TypeDog},
	{ID: "BSH_HVN", Name: "БИШОН ХАВАНЕС", Type: breed.TypeDog},
	{ID: "BLD_HND", Name: "БЛАДХАУНД", Type: breed.TypeDog},
	{ID: "BLN", Name: "БОЛОНЕЗ", Type: breed.TypeDog},
	{ID: "BLS_SHV", Name: "БОЛЬШОЙ ШВЕЙЦАРСКИЙ ЗЕННЕНХУНД", Type: breed.TypeDog},
	{ID: "BRD_CLL", Name: "БОРДЕР КОЛЛИ", Type: breed.TypeDog},
	{ID: "BRD_TER", Name: "БОРДЕР ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "BRD_DOG", Name: "БОРДОСКИЙ ДОГ", Type: breed.TypeDog},
	{ID: "BRD_CLL", Name: "БОРОДАТАЯ КОЛЛИ", Type: breed.TypeDog},
	{ID: "BOS", Name: "БОСЕРОН", Type: breed.TypeDog},
	{ID: "BST_TER", Name: "БОСТОН ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "BRZ_BLD", Name: "БРАЗИЛЬСКИЙ БУЛЬДОГ (БУЛЬДОГ КАМПЕЙРО)", Type: breed.TypeDog},
	{ID: "BRZ_FIL", Name: "БРАЗИЛЬСКИЙ ФИЛА", Type: breed.TypeDog},
	{ID: "BRT_EPN", Name: "БРЕТОНСКИЙ ЭПАНЬОЛ", Type: breed.TypeDog},
	{ID: "BRI", Name: "БРИАР", Type: breed.TypeDog},
	{ID: "BRS_GRF", Name: "БРЮССЕЛЬСКИЙ ГРИФФОН", Type: breed.TypeDog},
	{ID: "BUL_KUT", Name: "БУЛЛИ КУТТА (ПАКИСТАНСКИЙ МАСТИФ)", Type: breed.TypeDog},
	{ID: "BLD_ALP", Name: "БУЛЬДОГ АЛАПАХСКИЙ ЧИСТОКРОВНЫЙ (ОТТО)", Type: breed.TypeDog},
	{ID: "BLD_ENG", Name: "БУЛЬДОГ (АНГЛИЙСКИЙ БУЛЬДОГ)", Type: breed.TypeDog},
	{ID: "BLM", Name: "БУЛЬМАСТИФ", Type: breed.TypeDog},
	{ID: "BLT_AME", Name: "БУЛЬТЕРЬЕР (АМЕРИКАНСКИЙ БУЛЛИ)", Type: breed.TypeDog},
	{ID: "BRB", Name: "БУРБУЛЬ", Type: breed.TypeDog},
	{ID: "BRT_MNG", Name: "БУРЯТ-МОНГОЛЬСКАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "BND", Name: "БЭНДОГ", Type: breed.TypeDog},
	{ID: "WCH_HND", Name: "ВАХТЕЛЬХУНД", Type: breed.TypeDog},
	{ID: "WMR", Name: "ВЕЙМАРАНЕР", Type: breed.TypeDog},
	{ID: "WLC_CRG_CRD", Name: "ВЕЛЬШ КОРГИ КАРДИГАН", Type: breed.TypeDog},
	{ID: "WLC_CRG_PMB", Name: "ВЕЛЬШ КОРГИ ПЕМБРОК", Type: breed.TypeDog},
	{ID: "WLC_TER", Name: "ВЕЛЬШ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "VNG_ZHS", Name: "ВЕНГЕРСКАЯ ЖЕСТКОШЕРСТНАЯ ЛЕГАВАЯ", Type: breed.TypeDog},
	{ID: "VNG_KRS", Name: "ВЕНГЕРСКАЯ КОРОТКОШЕРСТНАЯ ЛЕГАВАЯ", Type: breed.TypeDog},
	{ID: "WST_HIL", Name: "ВЕСТ ХАЙЛЕНД ВАЙТ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "VLP_ITL", Name: "ВОЛЬПИНО ИТАЛЬЯНО", Type: breed.TypeDog},
	{ID: "VOS_EVR", Name: "ВОСТОЧНО-ЕВРОПЕЙСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "VOS_SIB", Name: "ВОСТОЧНО-СИБИРСКАЯ ЛАЙКА", Type: breed.TypeDog},
	{ID: "WLK_SOB", Name: "ВОЛКОСОБ", Type: breed.TypeDog},
	{ID: "GUL_DNG", Name: "ГУЛЬ ДОНГ (ПАКИСТАНСКИЙ БУЛЬДОГ)", Type: breed.TypeDog},
	{ID: "GRH", Name: "ГРЕЙХАУНД", Type: breed.TypeDog},
	{ID: "DLM", Name: "ДАЛМАТИН", Type: breed.TypeDog},
	{ID: "DTS_BRH", Name: "ДАТСКИЙ БРОХОЛЬМЕР", Type: breed.TypeDog},
	{ID: "DND_DMN", Name: "ДЕНДИ ДИНМОНТ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "JCK_RSL", Name: "ДЖЕК РАССЕЛ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "DBR", Name: "ДОБЕРМАН", Type: breed.TypeDog},
	{ID: "ZAP_SIB", Name: "ЗАПАДНО-СИБИРСКАЯ ЛАЙКА", Type: breed.TypeDog},
	{ID: "ZLT_RTR", Name: "ЗОЛОТИСТЫЙ РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "IRL_WLK", Name: "ИРЛАНДСКИЙ ВОЛКОДАВ", Type: breed.TypeDog},
	{ID: "IRL_GLN", Name: "ИРЛАНДСКИЙ ГЛЕН ОФ ИМАЛ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "IRL_KRS", Name: "ИРЛАНДСКИЙ КРАСНЫЙ СЕТТЕР", Type: breed.TypeDog},
	{ID: "IRL_MYG", Name: "ИРЛАНДСКИЙ МЯГКОШЕРСТНЫЙ ПШЕНИЧНЫЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "IRL_TER", Name: "ИРЛАНДСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "ISP_BRZ", Name: "ИСПАНСКАЯ БОРЗАЯ (ГАЛТЬГО ЭСПАНЬЕЛЬ)", Type: breed.TypeDog},
	{ID: "ISP_MST", Name: "ИСПАНСКИЙ МАСТИФ", Type: breed.TypeDog},
	{ID: "ITL_BRK", Name: "ИТАЛЬЯНСКИЙ БРАКК", Type: breed.TypeDog},
	{ID: "ITL_KNC", Name: "ИТАЛЬЯНСКИЙ КАНЕ КОРСО", Type: breed.TypeDog},
	{ID: "YRK_TER", Name: "ЙОРКШИРСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "KA_DE_BO", Name: "КА ДЕ БО", Type: breed.TypeDog},
	{ID: "KVL_KNG", Name: "КАВАЛЕР КИНГ ЧАРЛЬЗ СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "KVK_OVC", Name: "КАВКАЗСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "KNR_DOG", Name: "КАНАРСКИЙ ДОГ", Type: breed.TypeDog},
	{ID: "KRN_TER", Name: "КЕРН ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "KRY_BLU", Name: "КЕРРИ БЛЮ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "KNG_CHL", Name: "КИНГ ЧАРЛЬЗ СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "KIT_HOH", Name: "КИТАЙСКАЯ ХОХЛАТАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "KLM_SPN", Name: "КЛАМБЕР СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "KLL_DLN", Name: "КОЛЛИ ДЛИННОШЕРСТНЫЙ", Type: breed.TypeDog},
	{ID: "KLL_KRT", Name: "КОЛЛИ КОРОТКОШЕРСТНЫЙ", Type: breed.TypeDog},
	{ID: "KMD", Name: "КОМОНДОР", Type: breed.TypeDog},
	{ID: "KNT_TOY", Name: "КОНТИНЕНТАЛЬНЫЙ ТОЙ СПАНИЕЛЬ (ПАПИЙОН/ФАЛЕН)", Type: breed.TypeDog},
	{ID: "KTN_DE_T", Name: "КОТОН ДЕ ТУЛЕАР", Type: breed.TypeDog},
	{ID: "KVS", Name: "КУВАС", Type: breed.TypeDog},
	{ID: "KRC_RTR", Name: "КУРЧАВОШЕРСТНЫЙ РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "LBR_RTR", Name: "ЛАБРАДОР РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "LND", Name: "ЛАНДЗИР", Type: breed.TypeDog},
	{ID: "LKL_TER", Name: "ЛЕЙКЛЕНД ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "LNB", Name: "ЛЕОНБЕРГЕР", Type: breed.TypeDog},
	{ID: "LTV_GNC", Name: "ЛИТОВСКАЯ ГОНЧАЯ", Type: breed.TypeDog},
	{ID: "LHS_APS", Name: "ЛХАССКИЙ АПСО", Type: breed.TypeDog},
	{ID: "MLA_ITL", Name: "МАЛАЯ ИТАЛЬЯНСКАЯ БОРЗАЯ (ЛЕВРЕТКА)", Type: breed.TypeDog},
	{ID: "MLA_LVN", Name: "МАЛАЯ ЛЬВИННАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "MLY_BRB", Name: "МАЛЫЙ БРАБАНСОН", Type: breed.TypeDog},
	{ID: "MLY_VND", Name: "МАЛЫЙ ВАНДЕЙСКИЙ БАССЕТ-ГРИФФОН", Type: breed.TypeDog},
	{ID: "MLT", Name: "МАЛЬТЕЗЕ", Type: breed.TypeDog},
	{ID: "MNC_TER", Name: "МАНЧЕСТЕР ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "MRM_ABR", Name: "МАРЕММО-АБРУЦКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "MST", Name: "МАСТИФ", Type: breed.TypeDog},
	{ID: "MEX_GLA_MIN", Name: "МЕКСИКАНСКАЯ ГОЛАЯ СОБАКА МИНИАТЮРНАЯ", Type: breed.TypeDog},
	{ID: "MEX_GLA_SRD", Name: "МЕКСИКАНСКАЯ ГОЛАЯ СОБАКА СРЕДНЯЯ", Type: breed.TypeDog},
	{ID: "MEX_GLA_STN", Name: "МЕКСИКАНСКАЯ ГОЛАЯ СОБАКА СТАНДАРТНАЯ", Type: breed.TypeDog},
	{ID: "MOP", Name: "МОПС", Type: breed.TypeDog},
	{ID: "MSK_STR", Name: "МОСКОВСКАЯ СТОРОЖЕВАЯ", Type: breed.TypeDog},
	{ID: "MUD", Name: "МУДИ", Type: breed.TypeDog},
	{ID: "NEP_MST", Name: "НЕАПОЛИТАНСКИЙ МАСТИФ", Type: breed.TypeDog},
	{ID: "NEM_OVC", Name: "НЕМЕЦКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "NEM_BKS", Name: "НЕМЕЦКИЙ БОКСЕР", Type: breed.TypeDog},
	{ID: "NEM_DOG", Name: "НЕМЕЦКИЙ ДОГ", Type: breed.TypeDog},
	{ID: "NEM_DRT", Name: "НЕМЕЦКИЙ ДРАТХААР", Type: breed.TypeDog},
	{ID: "NEM_KRZ", Name: "НЕМЕЦКИЙ КУРЦХААР", Type: breed.TypeDog},
	{ID: "NEM_SHP_BLS", Name: "НЕМЕЦКИЙ ШПИЦ БОЛЬШОЙ", Type: breed.TypeDog},
	{ID: "NEM_SHP_WLF", Name: "НЕМЕЦКИЙ ШПИЦ ВОЛЬФШПИЦ", Type: breed.TypeDog},
	{ID: "NEM_SHP_MLY", Name: "НЕМЕЦКИЙ ШПИЦ МАЛЫЙ", Type: breed.TypeDog},
	{ID: "NEM_SHP_MIN", Name: "НЕМЕЦКИЙ ШПИЦ МИНИАТЮРНЫЙ", Type: breed.TypeDog},
	{ID: "NEM_SHP_SRD", Name: "НЕМЕЦКИЙ ШПИЦ СРЕДНИЙ", Type: breed.TypeDog},
	{ID: "NEM_YGD", Name: "НЕМЕЦКИЙ ЯГДТЕРЬЕР", Type: breed.TypeDog},
	{ID: "NVS_RTR", Name: "НОВОШОТЛАНДСКИЙ РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "NRV_SRY", Name: "НОРВЕЖСКИЙ СЕРЫЙ ЭЛЬКХУНД", Type: breed.TypeDog},
	{ID: "NRV_CHR", Name: "НОРВЕЖСКИЙ ЧЕРНЫЙ ЭЛЬКХУНД", Type: breed.TypeDog},
	{ID: "NRV_TER", Name: "НОРВИЧ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "NRF_TER", Name: "НОРФОЛК ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "NYF", Name: "НЬЮФАУНДЛЕНД", Type: breed.TypeDog},
	{ID: "OLN_SHP", Name: "ОЛЕНЕГОННЫЙ ШПИЦ", Type: breed.TypeDog},
	{ID: "PRS_RSL", Name: "ПАРСОН РАССЕЛ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "PKN", Name: "ПЕКИНЕС", Type: breed.TypeDog},
	{ID: "PRU_GLA", Name: "ПЕРУАНСКАЯ ГОЛАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "PNC", Name: "ПИНЧЕР", Type: breed.TypeDog},
	{ID: "PRN_GRN", Name: "ПИРЕНЕЙСКАЯ ГОРНАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "PRN_OVC", Name: "ПИРЕНЕЙСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "PRN_MST", Name: "ПИРЕНЕЙСКИЙ МАСТИФ", Type: breed.TypeDog},
	{ID: "PDN_IBZ", Name: "ПОДЕНКО ИБИЦЕНКО", Type: breed.TypeDog},
	{ID: "PLS_BRZ", Name: "ПОЛЬСКАЯ БОРЗАЯ (ПОЛЬСКИЙ ХАРТ)", Type: breed.TypeDog},
	{ID: "PLS_NZN", Name: "ПОЛЬСКАЯ НИЗИННАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "PLS_PDG", Name: "ПОЛЬСКАЯ ПОДГАЛЯНСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "PRT_VDN", Name: "ПОРТУГАЛЬСКАЯ ВОДНАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "PRZ_KRS", Name: "ПРАЖСКИЙ КРЫСАРИК", Type: breed.TypeDog},
	{ID: "PRM_RTR", Name: "ПРЯМОШЕРСТНЫЙ РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "PUD_BLS", Name: "ПУДЕЛЬ БОЛЬШОЙ", Type: breed.TypeDog},
	{ID: "PUD_MLY", Name: "ПУДЕЛЬ МАЛЫЙ", Type: breed.TypeDog},
	{ID: "PUD_MIN", Name: "ПУДЕЛЬ МИНИАТЮРНЫЙ", Type: breed.TypeDog},
	{ID: "PUD_TOY", Name: "ПУДЕЛЬ ТОЙ", Type: breed.TypeDog},
	{ID: "PUL", Name: "ПУЛИ", Type: breed.TypeDog},
	{ID: "PUM", Name: "ПУМИ", Type: breed.TypeDog},
	{ID: "RZN_SHN", Name: "РИЗЕНШНАУЦЕР", Type: breed.TypeDog},
	{ID: "RDZ_RDB", Name: "РОДЕЗИЙСКИЙ РИДЖБЕК", Type: breed.TypeDog},
	{ID: "RTW", Name: "РОТВЕЙЛЕР", Type: breed.TypeDog},
	{ID: "RUS_GNC", Name: "РУССКАЯ ГОНЧАЯ", Type: breed.TypeDog},
	{ID: "RUS_PSV", Name: "РУССКАЯ ПСОВАЯ БОРЗАЯ", Type: breed.TypeDog},
	{ID: "RUS_CVT", Name: "РУССКАЯ ЦВЕТНАЯ БОЛОНКА", Type: breed.TypeDog},
	{ID: "RUS_OHO", Name: "РУССКИЙ ОХОТНИЧИЙ СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "RUS_TOY_GS", Name: "РУССКИЙ ТОЙ Г-Ш", Type: breed.TypeDog},
	{ID: "RUS_TOY_DS", Name: "РУССКИЙ ТОЙ Д-Ш", Type: breed.TypeDog},
	{ID: "RUS_CHR", Name: "РУССКИЙ ЧЕРНЫЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "RUS_EVR", Name: "РУССКО ЕВРОПЕЙСКАЯ ЛАЙКА", Type: breed.TypeDog},
	{ID: "SLK", Name: "САЛЮКИ", Type: breed.TypeDog},
	{ID: "SMD_SOB", Name: "САМОЕДСКАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "SNB", Name: "СЕНБЕРНАР", Type: breed.TypeDog},
	{ID: "SET_GRD", Name: "СЕТТЕР ГОРДОН", Type: breed.TypeDog},
	{ID: "SBA", Name: "СИБА", Type: breed.TypeDog},
	{ID: "SIB_HSK", Name: "СИБИРСКИЙ ХАСКИ", Type: breed.TypeDog},
	{ID: "SLH_TER", Name: "СИЛИХЕМ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "SKY_TER", Name: "СКАЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "SKT_TER", Name: "СКОТЧ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "SLV_CHV", Name: "СЛОВАЦКИЙ ЧУВАЧ", Type: breed.TypeDog},
	{ID: "SRD_AZI", Name: "СРЕДНЕАЗИАТСКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "STR_ANG", Name: "СТАРОАНГЛИЙСКАЯ ОВЧАРКА (БОБТЕЙЛ)", Type: breed.TypeDog},
	{ID: "STF_BLT", Name: "СТАФФОРДШИРСКИЙ БУЛЬТЕРЬЕР", Type: breed.TypeDog},
	{ID: "SSS_SPN", Name: "СУССЕКС СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "SHP", Name: "СХИПЕРКЕ", Type: breed.TypeDog},
	{ID: "TAZ", Name: "ТАЗЫ", Type: breed.TypeDog},
	{ID: "TYG", Name: "ТАЙГАН", Type: breed.TypeDog},
	{ID: "TYK_RDB", Name: "ТАЙСКИЙ РИДЖБЕК", Type: breed.TypeDog},
	{ID: "TXS_KRL", Name: "ТАКСА КРОЛИЧЬЯ", Type: breed.TypeDog},
	{ID: "TXS_MIN", Name: "ТАКСА МИНИАТЮРНАЯ", Type: breed.TypeDog},
	{ID: "TXS_STN", Name: "ТАКСА СТАНДАРТНАЯ", Type: breed.TypeDog},
	{ID: "TBT_MST", Name: "ТИБЕТСКИЙ МАСТИФ", Type: breed.TypeDog},
	{ID: "TBT_SPN", Name: "ТИБЕТСКИЙ СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "TBT_TER", Name: "ТИБЕТСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "TOS", Name: "ТОСА", Type: breed.TypeDog},
	{ID: "WPT", Name: "УИППЕТ", Type: breed.TypeDog},
	{ID: "FRN_SOB", Name: "ФАРАОНОВА СОБАКА", Type: breed.TypeDog},
	{ID: "FLD_SPN", Name: "ФИЛД СПАНИЕЛЬ", Type: breed.TypeDog},
	{ID: "FIN_LFH", Name: "ФИНСКИЙ ЛАУФХУНД", Type: breed.TypeDog},
	{ID: "FIN_SHP", Name: "ФИНСКИЙ ШПИЦ", Type: breed.TypeDog},
	{ID: "FLN_BVY", Name: "ФЛАНДРСКИЙ БУВЬЕ", Type: breed.TypeDog},
	{ID: "FXT_GLD", Name: "ФОКСТЕРЬЕР ГЛАДКОШЕРСТНЫЙ", Type: breed.TypeDog},
	{ID: "FXT_ZHS", Name: "ФОКСТЕРЬЕР ЖЕСТКОШЕРСТНЫЙ", Type: breed.TypeDog},
	{ID: "FRN_BRK_GSK", Name: "ФРАНЦУЗСКИЙ БРАКК ГАСКОНСКИЙ", Type: breed.TypeDog},
	{ID: "FRN_BRK_PRN", Name: "ФРАНЦУЗСКИЙ БРАКК ПИРЕНЕЙСКИЙ", Type: breed.TypeDog},
	{ID: "FRN_BLD", Name: "ФРАНЦУЗСКИЙ БУЛЬДОГ", Type: breed.TypeDog},
	{ID: "HNN_SOB", Name: "ХАНААНСКАЯ СОБАКА", Type: breed.TypeDog},
	{ID: "HVW", Name: "ХОВАВАРТ", Type: breed.TypeDog},
	{ID: "HRT_BRZ", Name: "ХОРТАЯ БОРЗАЯ", Type: breed.TypeDog},
	{ID: "ZVR_PNC", Name: "ЦВЕРГПИНЧЕР", Type: breed.TypeDog},
	{ID: "ZVR_SHN", Name: "ЦВЕРГШНАУЦЕР", Type: breed.TypeDog},
	{ID: "CHW_CHW", Name: "ЧАУ ЧАУ", Type: breed.TypeDog},
	{ID: "CHS_BEY", Name: "ЧЕСАПИК БЭЙ РЕТРИВЕР", Type: breed.TypeDog},
	{ID: "CHH_WLF", Name: "ЧЕХОСЛОВАЦКАЯ ВОЛЧЬЯ СОБАКА", Type: breed.TypeDog},
	{ID: "CHH_TER", Name: "ЧЕШСКИЙ ТЕРЬЕР", Type: breed.TypeDog},
	{ID: "CHR_ETN", Name: "ЧИРНЕКО ДЕЛЬ ЭТНА", Type: breed.TypeDog},
	{ID: "CHH", Name: "ЧИХУАХУА", Type: breed.TypeDog},
	{ID: "CHK_EZD", Name: "ЧУКОТСКАЯ ЕЗДОВАЯ", Type: breed.TypeDog},
	{ID: "SHR_PEY", Name: "ШАР ПЕЙ", Type: breed.TypeDog},
	{ID: "SHL", Name: "ШЕЛТИ", Type: breed.TypeDog},
	{ID: "SHI_TZU", Name: "ШИ ТЦУ", Type: breed.TypeDog},
	{ID: "SHN", Name: "ШНАУЦЕР", Type: breed.TypeDog},
	{ID: "SHT_BRZ", Name: "ШОТЛАНДСКАЯ БОРЗАЯ (ДИРХАУНД)", Type: breed.TypeDog},
	{ID: "NTL_ZNH", Name: "ЭНТЛЕБУХЕР ЗЕННЕНХУНД", Type: breed.TypeDog},
	{ID: "ERD_TER", Name: "ЭРДЕЛЬТЕРЬЕР", Type: breed.TypeDog},
	{ID: "EST_GNC", Name: "ЭСТОНСКАЯ ГОНЧАЯ", Type: breed.TypeDog},
	{ID: "YZH_RUS", Name: "ЮЖНОРУССКАЯ ОВЧАРКА", Type: breed.TypeDog},
	{ID: "YKT_LYK", Name: "ЯКУТСКАЯ ЛАЙКА", Type: breed.TypeDog},
	{ID: "YPN_HIN", Name: "ЯПОНСКИЙ ХИН", Type: breed.TypeDog},
	{ID: "YPN_SHP", Name: "ЯПОНСКИЙ ШПИЦ", Type: breed.TypeDog},
	{ID: "MIX_CAT", Name: "МЕТИС", Type: breed.TypeCat},
	{ID: "ABY", Name: "АБИССИНСКАЯ", Type: breed.TypeCat},
	{ID: "AUS_DMC", Name: "АВСТРАЛИЙСКАЯ ДЫМЧАТАЯ (МИСТ)", Type: breed.TypeCat},
	{ID: "AZI_TBB", Name: "АЗИАТСКАЯ (ТАББИ/ДЫМЧАТАЯ)", Type: breed.TypeCat},
	{ID: "AME_ZHS", Name: "АМЕРИКАНСКАЯ ЖЕСТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "AME_KRS", Name: "АМЕРИКАНСКАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "AME_BBT", Name: "АМЕРИКАНСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "AME_KRL", Name: "АМЕРИКАНСКИЙ КЕРЛ", Type: breed.TypeCat},
	{ID: "AME_KRL_DLN", Name: "АМЕРИКАНСКИЙ КЕРЛ ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "ANT_KRS", Name: "АНАТОЛИЙСКАЯ (ТУРЕЦКАЯ КОРОТКОШЕРСТНАЯ)", Type: breed.TypeCat},
	{ID: "ARB_MAU", Name: "АРАВИЙСКАЯ МАУ", Type: breed.TypeCat},
	{ID: "BLN", Name: "БАЛИНЕЗИЙСКАЯ (БАЛИНЕЗ)", Type: breed.TypeCat},
	{ID: "BNG", Name: "БЕНГАЛЬСКАЯ", Type: breed.TypeCat},
	{ID: "BRM_SVC", Name: "БИРМАНСКАЯ (СВЯЩЕННАЯ БИРМА)", Type: breed.TypeCat},
	{ID: "BMB", Name: "БОМБЕЙСКАЯ", Type: breed.TypeCat},
	{ID: "BRZ_KRS", Name: "БРАЗИЛЬСКАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "BRT_DLN", Name: "БРИТАНСКАЯ ДЛИННОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "BRT_KRS", Name: "БРИТАНСКАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "BRM_BRM", Name: "БУРМЕЗСКАЯ (БУРМАНСКАЯ)", Type: breed.TypeCat},
	{ID: "BRM", Name: "БУРМИЛЛА", Type: breed.TypeCat},
	{ID: "HVN_BRN", Name: "ГАВАНА БРАУН", Type: breed.TypeCat},
	{ID: "GRM_RX", Name: "ГЕРМАН РЕКС (НЕМЕЦКИЙ РЕКС)", Type: breed.TypeCat},
	{ID: "DVN_RX", Name: "ДЕВОН РЕКС", Type: breed.TypeCat},
	{ID: "DNS_SFX", Name: "ДОНСКОЙ СФИНКС", Type: breed.TypeCat},
	{ID: "EVR_KRS", Name: "ЕВРОПЕЙСКАЯ КОРОТКОШЕРСТНАЯ (КЕЛЬТСКАЯ)", Type: breed.TypeCat},
	{ID: "EGP_MAU", Name: "ЕГИПЕТСКАЯ МАУ", Type: breed.TypeCat},
	{ID: "YRK", Name: "ЙОРКСКАЯ (ЙОРК)", Type: breed.TypeCat},
	{ID: "KLF_SYA", Name: "КАЛИФОРНИЙСКАЯ СИЯЮЩАЯ", Type: breed.TypeCat},
	{ID: "KNA", Name: "КАНААНИ (ХАНААНСКАЯ)", Type: breed.TypeCat},
	{ID: "KND_SFX", Name: "КАНАДСКИЙ СФИНКС", Type: breed.TypeCat},
	{ID: "KRL_BBT", Name: "КАРЕЛЬСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "KRL_BBT_KRS", Name: "КАРЕЛЬСКИЙ БОБТЕЙЛ КОРОТКОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "KMR", Name: "КИМРИК", Type: breed.TypeCat},
	{ID: "KRT", Name: "КОРАТ", Type: breed.TypeCat},
	{ID: "KRN_RX", Name: "КОРНИШ-РЕКС", Type: breed.TypeCat},
	{ID: "KRL_BBT_2", Name: "КУРИЛЬСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "KRL_BBT_KRS_2", Name: "КУРИЛЬСКИЙ БОБТЕЙЛ КОРОТКОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "LPR_DLN", Name: "ЛАПЕРМ ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "MNC_DLN", Name: "МАНЧКИН ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "MNC_KRS", Name: "МАНЧКИН КОРОТКОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "MYN_KN", Name: "МЕЙН-КУН", Type: breed.TypeCat},
	{ID: "MKG_BBT", Name: "МЕКОНГСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "MNK", Name: "МЭНКС (МАНКС/МЭНСКАЯ)", Type: breed.TypeCat},
	{ID: "NVS_MSK", Name: "НЕВСКАЯ МАСКАРАДНАЯ", Type: breed.TypeCat},
	{ID: "NBL", Name: "НИБЕЛУНГ", Type: breed.TypeCat},
	{ID: "NRV_LSN", Name: "НОРВЕЖСКАЯ ЛЕСНАЯ", Type: breed.TypeCat},
	{ID: "ORN_KRS", Name: "ОРИЕНТАЛЬНАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "ORN_PLD", Name: "ОРИЕНТАЛЬНАЯ ПОЛУДЛИННОШЕРСТНАЯ (МАНДАРИН)", Type: breed.TypeCat},
	{ID: "OCK", Name: "ОЦИКЕТ", Type: breed.TypeCat},
	{ID: "PRS_GML", Name: "ПЕРСИДСКИЕ (ГИМАЛАЙСКИЕ)", Type: breed.TypeCat},
	{ID: "PTR_BLD", Name: "ПЕТЕРБОЛД (ПЕТЕРБУРГСКИЙ СФИНКС)", Type: breed.TypeCat},
	{ID: "RGM", Name: "РАГАМАФФИН", Type: breed.TypeCat},
	{ID: "RUS_GLB", Name: "РУССКАЯ ГОЛУБАЯ", Type: breed.TypeCat},
	{ID: "RGD", Name: "РЭГДОЛЛ", Type: breed.TypeCat},
	{ID: "SYS_DLN", Name: "СЕЙШЕЛЬСКАЯ ДЛИННОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "SYS_KRS", Name: "СЕЙШЕЛЬСКАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "SLK_RX_KRS", Name: "СЕЛКИРК РЕКС КОРОТКОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "SLK_RX_DLN", Name: "СЕЛКИРК-РЕКС ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "SIA", Name: "СИАМСКАЯ", Type: breed.TypeCat},
	{ID: "SIB", Name: "СИБИРСКАЯ", Type: breed.TypeCat},
	{ID: "SNG", Name: "СИНГАПУРСКАЯ (СИНГАПУРА)", Type: breed.TypeCat},
	{ID: "SKT_FLD", Name: "СКОТТИШ-ФОЛД (ШОТЛАНДСКАЯ ВИСЛОУХАЯ)", Type: breed.TypeCat},
	{ID: "SKT_FLD_DLN", Name: "СКОТТИШ-ФОЛД ДЛИННОШЕРСТНЫЙ (ХАЙЛЕНД ФОЛД)", Type: breed.TypeCat},
	{ID: "SNW_SHU", Name: "СНОУ-ШУ", Type: breed.TypeCat},
	{ID: "SKK", Name: "СОКОКЕ", Type: breed.TypeCat},
	{ID: "SML", Name: "СОМАЛИЙСКАЯ (СОМАЛИ)", Type: breed.TypeCat},
	{ID: "TYK", Name: "ТАЙСКАЯ", Type: breed.TypeCat},
	{ID: "TYK_BBT", Name: "ТАЙСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "TFF", Name: "ТИФФАНИ (АЗИАТСКАЯ ДЛИННОШЕРСТНАЯ/МАХАГОН/ШАНТИЛИ)", Type: breed.TypeCat},
	{ID: "TNK", Name: "ТОНКИНСКАЯ", Type: breed.TypeCat},
	{ID: "TRK_ANG", Name: "ТУРЕЦКАЯ АНГОРА", Type: breed.TypeCat},
	{ID: "TRK_VAN", Name: "ТУРЕЦКАЯ ВАН", Type: breed.TypeCat},
	{ID: "URL_RX_DLN", Name: "УРАЛЬСКИЙ РЕКС ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "URL_RX_KRS", Name: "УРАЛЬСКИЙ РЕКС КОРОТКОШЕРСТНЫЙ", Type: breed.TypeCat},
	{ID: "ZYL", Name: "ЦЕЙЛОНСКАЯ", Type: breed.TypeCat},
	{ID: "CHR_KRT", Name: "ШАРТРЕЗ (КАРТЕЗИАНСКАЯ)", Type: breed.TypeCat},
	{ID: "EXZ_KRS", Name: "ЭКЗОТИЧЕСКАЯ КОРОТКОШЕРСТНАЯ", Type: breed.TypeCat},
	{ID: "YVN", Name: "ЯВАНЕЗИЙСКАЯ", Type: breed.TypeCat},
	{ID: "YPN_BBT", Name: "ЯПОНСКИЙ БОБТЕЙЛ", Type: breed.TypeCat},
	{ID: "YPN_BBT_DLN", Name: "ЯПОНСКИЙ БОБТЕЙЛ ДЛИННОШЕРСТНЫЙ", Type: breed.TypeCat},
}
