// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/bloodsearchrequest"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/internal"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/predicate"
)

// BloodSearchRequestDelete is the builder for deleting a BloodSearchRequest entity.
type BloodSearchRequestDelete struct {
	config
	hooks    []Hook
	mutation *BloodSearchRequestMutation
}

// Where appends a list predicates to the BloodSearchRequestDelete builder.
func (_d *BloodSearchRequestDelete) Where(ps ...predicate.BloodSearchRequest) *BloodSearchRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BloodSearchRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BloodSearchRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BloodSearchRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bloodsearchrequest.Table, sqlgraph.NewFieldSpec(bloodsearchrequest.FieldID, field.TypeString))
	_spec.Node.Schema = _d.schemaConfig.BloodSearchRequest
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BloodSearchRequestDeleteOne is the builder for deleting a single BloodSearchRequest entity.
type BloodSearchRequestDeleteOne struct {
	_d *BloodSearchRequestDelete
}

// Where appends a list predicates to the BloodSearchRequestDelete builder.
func (_d *BloodSearchRequestDeleteOne) Where(ps ...predicate.BloodSearchRequest) *BloodSearchRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BloodSearchRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bloodsearchrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BloodSearchRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
