// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/bloodgroup"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pet"
)

// BloodGroupCreate is the builder for creating a BloodGroup entity.
type BloodGroupCreate struct {
	config
	mutation *BloodGroupMutation
	hooks    []Hook
}

// SetPetType sets the "pet_type" field.
func (_c *BloodGroupCreate) SetPetType(v bloodgroup.PetType) *BloodGroupCreate {
	_c.mutation.SetPetType(v)
	return _c
}

// SetBloodGroup sets the "blood_group" field.
func (_c *BloodGroupCreate) SetBloodGroup(v string) *BloodGroupCreate {
	_c.mutation.SetBloodGroup(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BloodGroupCreate) SetDescription(v string) *BloodGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BloodGroupCreate) SetNillableDescription(v *string) *BloodGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BloodGroupCreate) SetID(v string) *BloodGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddPetIDs adds the "pets" edge to the Pet entity by IDs.
func (_c *BloodGroupCreate) AddPetIDs(ids ...string) *BloodGroupCreate {
	_c.mutation.AddPetIDs(ids...)
	return _c
}

// AddPets adds the "pets" edges to the Pet entity.
func (_c *BloodGroupCreate) AddPets(v ...*Pet) *BloodGroupCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPetIDs(ids...)
}

// Mutation returns the BloodGroupMutation object of the builder.
func (_c *BloodGroupCreate) Mutation() *BloodGroupMutation {
	return _c.mutation
}

// Save creates the BloodGroup in the database.
func (_c *BloodGroupCreate) Save(ctx context.Context) (*BloodGroup, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BloodGroupCreate) SaveX(ctx context.Context) *BloodGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BloodGroupCreate) check() error {
	if _, ok := _c.mutation.PetType(); !ok {
		return &ValidationError{Name: "pet_type", err: errors.New(`ent: missing required field "BloodGroup.pet_type"`)}
	}
	if v, ok := _c.mutation.PetType(); ok {
		if err := bloodgroup.PetTypeValidator(v); err != nil {
			return &ValidationError{Name: "pet_type", err: fmt.Errorf(`ent: validator failed for field "BloodGroup.pet_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BloodGroup(); !ok {
		return &ValidationError{Name: "blood_group", err: errors.New(`ent: missing required field "BloodGroup.blood_group"`)}
	}
	if v, ok := _c.mutation.BloodGroup(); ok {
		if err := bloodgroup.BloodGroupValidator(v); err != nil {
			return &ValidationError{Name: "blood_group", err: fmt.Errorf(`ent: validator failed for field "BloodGroup.blood_group": %w`, err)}
		}
	}
	return nil
}

func (_c *BloodGroupCreate) sqlSave(ctx context.Context) (*BloodGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BloodGroup.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BloodGroupCreate) createSpec() (*BloodGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &BloodGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bloodgroup.Table, sqlgraph.NewFieldSpec(bloodgroup.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PetType(); ok {
		_spec.SetField(bloodgroup.FieldPetType, field.TypeEnum, value)
		_node.PetType = value
	}
	if value, ok := _c.mutation.BloodGroup(); ok {
		_spec.SetField(bloodgroup.FieldBloodGroup, field.TypeString, value)
		_node.BloodGroup = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(bloodgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.PetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bloodgroup.PetsTable,
			Columns: []string{bloodgroup.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BloodGroupCreateBulk is the builder for creating many BloodGroup entities in bulk.
type BloodGroupCreateBulk struct {
	config
	err      error
	builders []*BloodGroupCreate
}

// Save creates the BloodGroup entities in the database.
func (_c *BloodGroupCreateBulk) Save(ctx context.Context) ([]*BloodGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BloodGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BloodGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BloodGroupCreateBulk) SaveX(ctx context.Context) []*BloodGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
