// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/artesipov-alt/odnoi-krovi-app/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/bloodcomponent"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/bloodgroup"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/bloodsearchrequest"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/breed"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/donorresponse"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/location"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pet"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/petanalysis"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/petbonus"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pethealth"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pettreatment"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BloodComponent is the client for interacting with the BloodComponent builders.
	BloodComponent *BloodComponentClient
	// BloodGroup is the client for interacting with the BloodGroup builders.
	BloodGroup *BloodGroupClient
	// BloodSearchRequest is the client for interacting with the BloodSearchRequest builders.
	BloodSearchRequest *BloodSearchRequestClient
	// Breed is the client for interacting with the Breed builders.
	Breed *BreedClient
	// DonorResponse is the client for interacting with the DonorResponse builders.
	DonorResponse *DonorResponseClient
	// Location is the client for interacting with the Location builders.
	Location *LocationClient
	// Pet is the client for interacting with the Pet builders.
	Pet *PetClient
	// PetAnalysis is the client for interacting with the PetAnalysis builders.
	PetAnalysis *PetAnalysisClient
	// PetBonus is the client for interacting with the PetBonus builders.
	PetBonus *PetBonusClient
	// PetHealth is the client for interacting with the PetHealth builders.
	PetHealth *PetHealthClient
	// PetTreatment is the client for interacting with the PetTreatment builders.
	PetTreatment *PetTreatmentClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BloodComponent = NewBloodComponentClient(c.config)
	c.BloodGroup = NewBloodGroupClient(c.config)
	c.BloodSearchRequest = NewBloodSearchRequestClient(c.config)
	c.Breed = NewBreedClient(c.config)
	c.DonorResponse = NewDonorResponseClient(c.config)
	c.Location = NewLocationClient(c.config)
	c.Pet = NewPetClient(c.config)
	c.PetAnalysis = NewPetAnalysisClient(c.config)
	c.PetBonus = NewPetBonusClient(c.config)
	c.PetHealth = NewPetHealthClient(c.config)
	c.PetTreatment = NewPetTreatmentClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		BloodComponent:     NewBloodComponentClient(cfg),
		BloodGroup:         NewBloodGroupClient(cfg),
		BloodSearchRequest: NewBloodSearchRequestClient(cfg),
		Breed:              NewBreedClient(cfg),
		DonorResponse:      NewDonorResponseClient(cfg),
		Location:           NewLocationClient(cfg),
		Pet:                NewPetClient(cfg),
		PetAnalysis:        NewPetAnalysisClient(cfg),
		PetBonus:           NewPetBonusClient(cfg),
		PetHealth:          NewPetHealthClient(cfg),
		PetTreatment:       NewPetTreatmentClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		BloodComponent:     NewBloodComponentClient(cfg),
		BloodGroup:         NewBloodGroupClient(cfg),
		BloodSearchRequest: NewBloodSearchRequestClient(cfg),
		Breed:              NewBreedClient(cfg),
		DonorResponse:      NewDonorResponseClient(cfg),
		Location:           NewLocationClient(cfg),
		Pet:                NewPetClient(cfg),
		PetAnalysis:        NewPetAnalysisClient(cfg),
		PetBonus:           NewPetBonusClient(cfg),
		PetHealth:          NewPetHealthClient(cfg),
		PetTreatment:       NewPetTreatmentClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BloodComponent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BloodComponent, c.BloodGroup, c.BloodSearchRequest, c.Breed, c.DonorResponse,
		c.Location, c.Pet, c.PetAnalysis, c.PetBonus, c.PetHealth, c.PetTreatment,
		c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BloodComponent, c.BloodGroup, c.BloodSearchRequest, c.Breed, c.DonorResponse,
		c.Location, c.Pet, c.PetAnalysis, c.PetBonus, c.PetHealth, c.PetTreatment,
		c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BloodComponentMutation:
		return c.BloodComponent.mutate(ctx, m)
	case *BloodGroupMutation:
		return c.BloodGroup.mutate(ctx, m)
	case *BloodSearchRequestMutation:
		return c.BloodSearchRequest.mutate(ctx, m)
	case *BreedMutation:
		return c.Breed.mutate(ctx, m)
	case *DonorResponseMutation:
		return c.DonorResponse.mutate(ctx, m)
	case *LocationMutation:
		return c.Location.mutate(ctx, m)
	case *PetMutation:
		return c.Pet.mutate(ctx, m)
	case *PetAnalysisMutation:
		return c.PetAnalysis.mutate(ctx, m)
	case *PetBonusMutation:
		return c.PetBonus.mutate(ctx, m)
	case *PetHealthMutation:
		return c.PetHealth.mutate(ctx, m)
	case *PetTreatmentMutation:
		return c.PetTreatment.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BloodComponentClient is a client for the BloodComponent schema.
type BloodComponentClient struct {
	config
}

// NewBloodComponentClient returns a client for the BloodComponent from the given config.
func NewBloodComponentClient(c config) *BloodComponentClient {
	return &BloodComponentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bloodcomponent.Hooks(f(g(h())))`.
func (c *BloodComponentClient) Use(hooks ...Hook) {
	c.hooks.BloodComponent = append(c.hooks.BloodComponent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bloodcomponent.Intercept(f(g(h())))`.
func (c *BloodComponentClient) Intercept(interceptors ...Interceptor) {
	c.inters.BloodComponent = append(c.inters.BloodComponent, interceptors...)
}

// Create returns a builder for creating a BloodComponent entity.
func (c *BloodComponentClient) Create() *BloodComponentCreate {
	mutation := newBloodComponentMutation(c.config, OpCreate)
	return &BloodComponentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BloodComponent entities.
func (c *BloodComponentClient) CreateBulk(builders ...*BloodComponentCreate) *BloodComponentCreateBulk {
	return &BloodComponentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BloodComponentClient) MapCreateBulk(slice any, setFunc func(*BloodComponentCreate, int)) *BloodComponentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BloodComponentCreateBulk{err: fmt.Errorf("calling to BloodComponentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BloodComponentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BloodComponentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BloodComponent.
func (c *BloodComponentClient) Update() *BloodComponentUpdate {
	mutation := newBloodComponentMutation(c.config, OpUpdate)
	return &BloodComponentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BloodComponentClient) UpdateOne(_m *BloodComponent) *BloodComponentUpdateOne {
	mutation := newBloodComponentMutation(c.config, OpUpdateOne, withBloodComponent(_m))
	return &BloodComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BloodComponentClient) UpdateOneID(id string) *BloodComponentUpdateOne {
	mutation := newBloodComponentMutation(c.config, OpUpdateOne, withBloodComponentID(id))
	return &BloodComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BloodComponent.
func (c *BloodComponentClient) Delete() *BloodComponentDelete {
	mutation := newBloodComponentMutation(c.config, OpDelete)
	return &BloodComponentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BloodComponentClient) DeleteOne(_m *BloodComponent) *BloodComponentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BloodComponentClient) DeleteOneID(id string) *BloodComponentDeleteOne {
	builder := c.Delete().Where(bloodcomponent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BloodComponentDeleteOne{builder}
}

// Query returns a query builder for BloodComponent.
func (c *BloodComponentClient) Query() *BloodComponentQuery {
	return &BloodComponentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBloodComponent},
		inters: c.Interceptors(),
	}
}

// Get returns a BloodComponent entity by its id.
func (c *BloodComponentClient) Get(ctx context.Context, id string) (*BloodComponent, error) {
	return c.Query().Where(bloodcomponent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BloodComponentClient) GetX(ctx context.Context, id string) *BloodComponent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BloodComponentClient) Hooks() []Hook {
	return c.hooks.BloodComponent
}

// Interceptors returns the client interceptors.
func (c *BloodComponentClient) Interceptors() []Interceptor {
	return c.inters.BloodComponent
}

func (c *BloodComponentClient) mutate(ctx context.Context, m *BloodComponentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BloodComponentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BloodComponentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BloodComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BloodComponentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BloodComponent mutation op: %q", m.Op())
	}
}

// BloodGroupClient is a client for the BloodGroup schema.
type BloodGroupClient struct {
	config
}

// NewBloodGroupClient returns a client for the BloodGroup from the given config.
func NewBloodGroupClient(c config) *BloodGroupClient {
	return &BloodGroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bloodgroup.Hooks(f(g(h())))`.
func (c *BloodGroupClient) Use(hooks ...Hook) {
	c.hooks.BloodGroup = append(c.hooks.BloodGroup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bloodgroup.Intercept(f(g(h())))`.
func (c *BloodGroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.BloodGroup = append(c.inters.BloodGroup, interceptors...)
}

// Create returns a builder for creating a BloodGroup entity.
func (c *BloodGroupClient) Create() *BloodGroupCreate {
	mutation := newBloodGroupMutation(c.config, OpCreate)
	return &BloodGroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BloodGroup entities.
func (c *BloodGroupClient) CreateBulk(builders ...*BloodGroupCreate) *BloodGroupCreateBulk {
	return &BloodGroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BloodGroupClient) MapCreateBulk(slice any, setFunc func(*BloodGroupCreate, int)) *BloodGroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BloodGroupCreateBulk{err: fmt.Errorf("calling to BloodGroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BloodGroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BloodGroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BloodGroup.
func (c *BloodGroupClient) Update() *BloodGroupUpdate {
	mutation := newBloodGroupMutation(c.config, OpUpdate)
	return &BloodGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BloodGroupClient) UpdateOne(_m *BloodGroup) *BloodGroupUpdateOne {
	mutation := newBloodGroupMutation(c.config, OpUpdateOne, withBloodGroup(_m))
	return &BloodGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BloodGroupClient) UpdateOneID(id string) *BloodGroupUpdateOne {
	mutation := newBloodGroupMutation(c.config, OpUpdateOne, withBloodGroupID(id))
	return &BloodGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BloodGroup.
func (c *BloodGroupClient) Delete() *BloodGroupDelete {
	mutation := newBloodGroupMutation(c.config, OpDelete)
	return &BloodGroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BloodGroupClient) DeleteOne(_m *BloodGroup) *BloodGroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BloodGroupClient) DeleteOneID(id string) *BloodGroupDeleteOne {
	builder := c.Delete().Where(bloodgroup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BloodGroupDeleteOne{builder}
}

// Query returns a query builder for BloodGroup.
func (c *BloodGroupClient) Query() *BloodGroupQuery {
	return &BloodGroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBloodGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a BloodGroup entity by its id.
func (c *BloodGroupClient) Get(ctx context.Context, id string) (*BloodGroup, error) {
	return c.Query().Where(bloodgroup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BloodGroupClient) GetX(ctx context.Context, id string) *BloodGroup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPets queries the pets edge of a BloodGroup.
func (c *BloodGroupClient) QueryPets(_m *BloodGroup) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bloodgroup.Table, bloodgroup.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bloodgroup.PetsTable, bloodgroup.PetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BloodGroupClient) Hooks() []Hook {
	return c.hooks.BloodGroup
}

// Interceptors returns the client interceptors.
func (c *BloodGroupClient) Interceptors() []Interceptor {
	return c.inters.BloodGroup
}

func (c *BloodGroupClient) mutate(ctx context.Context, m *BloodGroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BloodGroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BloodGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BloodGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BloodGroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BloodGroup mutation op: %q", m.Op())
	}
}

// BloodSearchRequestClient is a client for the BloodSearchRequest schema.
type BloodSearchRequestClient struct {
	config
}

// NewBloodSearchRequestClient returns a client for the BloodSearchRequest from the given config.
func NewBloodSearchRequestClient(c config) *BloodSearchRequestClient {
	return &BloodSearchRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bloodsearchrequest.Hooks(f(g(h())))`.
func (c *BloodSearchRequestClient) Use(hooks ...Hook) {
	c.hooks.BloodSearchRequest = append(c.hooks.BloodSearchRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bloodsearchrequest.Intercept(f(g(h())))`.
func (c *BloodSearchRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.BloodSearchRequest = append(c.inters.BloodSearchRequest, interceptors...)
}

// Create returns a builder for creating a BloodSearchRequest entity.
func (c *BloodSearchRequestClient) Create() *BloodSearchRequestCreate {
	mutation := newBloodSearchRequestMutation(c.config, OpCreate)
	return &BloodSearchRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BloodSearchRequest entities.
func (c *BloodSearchRequestClient) CreateBulk(builders ...*BloodSearchRequestCreate) *BloodSearchRequestCreateBulk {
	return &BloodSearchRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BloodSearchRequestClient) MapCreateBulk(slice any, setFunc func(*BloodSearchRequestCreate, int)) *BloodSearchRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BloodSearchRequestCreateBulk{err: fmt.Errorf("calling to BloodSearchRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BloodSearchRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BloodSearchRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BloodSearchRequest.
func (c *BloodSearchRequestClient) Update() *BloodSearchRequestUpdate {
	mutation := newBloodSearchRequestMutation(c.config, OpUpdate)
	return &BloodSearchRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BloodSearchRequestClient) UpdateOne(_m *BloodSearchRequest) *BloodSearchRequestUpdateOne {
	mutation := newBloodSearchRequestMutation(c.config, OpUpdateOne, withBloodSearchRequest(_m))
	return &BloodSearchRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BloodSearchRequestClient) UpdateOneID(id string) *BloodSearchRequestUpdateOne {
	mutation := newBloodSearchRequestMutation(c.config, OpUpdateOne, withBloodSearchRequestID(id))
	return &BloodSearchRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BloodSearchRequest.
func (c *BloodSearchRequestClient) Delete() *BloodSearchRequestDelete {
	mutation := newBloodSearchRequestMutation(c.config, OpDelete)
	return &BloodSearchRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BloodSearchRequestClient) DeleteOne(_m *BloodSearchRequest) *BloodSearchRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BloodSearchRequestClient) DeleteOneID(id string) *BloodSearchRequestDeleteOne {
	builder := c.Delete().Where(bloodsearchrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BloodSearchRequestDeleteOne{builder}
}

// Query returns a query builder for BloodSearchRequest.
func (c *BloodSearchRequestClient) Query() *BloodSearchRequestQuery {
	return &BloodSearchRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBloodSearchRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a BloodSearchRequest entity by its id.
func (c *BloodSearchRequestClient) Get(ctx context.Context, id string) (*BloodSearchRequest, error) {
	return c.Query().Where(bloodsearchrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BloodSearchRequestClient) GetX(ctx context.Context, id string) *BloodSearchRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPet queries the pet edge of a BloodSearchRequest.
func (c *BloodSearchRequestClient) QueryPet(_m *BloodSearchRequest) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bloodsearchrequest.Table, bloodsearchrequest.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, bloodsearchrequest.PetTable, bloodsearchrequest.PetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryResponses queries the responses edge of a BloodSearchRequest.
func (c *BloodSearchRequestClient) QueryResponses(_m *BloodSearchRequest) *DonorResponseQuery {
	query := (&DonorResponseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bloodsearchrequest.Table, bloodsearchrequest.FieldID, id),
			sqlgraph.To(donorresponse.Table, donorresponse.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bloodsearchrequest.ResponsesTable, bloodsearchrequest.ResponsesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BloodSearchRequestClient) Hooks() []Hook {
	return c.hooks.BloodSearchRequest
}

// Interceptors returns the client interceptors.
func (c *BloodSearchRequestClient) Interceptors() []Interceptor {
	inters := c.inters.BloodSearchRequest
	return append(inters[:len(inters):len(inters)], bloodsearchrequest.Interceptors[:]...)
}

func (c *BloodSearchRequestClient) mutate(ctx context.Context, m *BloodSearchRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BloodSearchRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BloodSearchRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BloodSearchRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BloodSearchRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BloodSearchRequest mutation op: %q", m.Op())
	}
}

// BreedClient is a client for the Breed schema.
type BreedClient struct {
	config
}

// NewBreedClient returns a client for the Breed from the given config.
func NewBreedClient(c config) *BreedClient {
	return &BreedClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `breed.Hooks(f(g(h())))`.
func (c *BreedClient) Use(hooks ...Hook) {
	c.hooks.Breed = append(c.hooks.Breed, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `breed.Intercept(f(g(h())))`.
func (c *BreedClient) Intercept(interceptors ...Interceptor) {
	c.inters.Breed = append(c.inters.Breed, interceptors...)
}

// Create returns a builder for creating a Breed entity.
func (c *BreedClient) Create() *BreedCreate {
	mutation := newBreedMutation(c.config, OpCreate)
	return &BreedCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Breed entities.
func (c *BreedClient) CreateBulk(builders ...*BreedCreate) *BreedCreateBulk {
	return &BreedCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BreedClient) MapCreateBulk(slice any, setFunc func(*BreedCreate, int)) *BreedCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BreedCreateBulk{err: fmt.Errorf("calling to BreedClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BreedCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BreedCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Breed.
func (c *BreedClient) Update() *BreedUpdate {
	mutation := newBreedMutation(c.config, OpUpdate)
	return &BreedUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BreedClient) UpdateOne(_m *Breed) *BreedUpdateOne {
	mutation := newBreedMutation(c.config, OpUpdateOne, withBreed(_m))
	return &BreedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BreedClient) UpdateOneID(id string) *BreedUpdateOne {
	mutation := newBreedMutation(c.config, OpUpdateOne, withBreedID(id))
	return &BreedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Breed.
func (c *BreedClient) Delete() *BreedDelete {
	mutation := newBreedMutation(c.config, OpDelete)
	return &BreedDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BreedClient) DeleteOne(_m *Breed) *BreedDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BreedClient) DeleteOneID(id string) *BreedDeleteOne {
	builder := c.Delete().Where(breed.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BreedDeleteOne{builder}
}

// Query returns a query builder for Breed.
func (c *BreedClient) Query() *BreedQuery {
	return &BreedQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBreed},
		inters: c.Interceptors(),
	}
}

// Get returns a Breed entity by its id.
func (c *BreedClient) Get(ctx context.Context, id string) (*Breed, error) {
	return c.Query().Where(breed.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BreedClient) GetX(ctx context.Context, id string) *Breed {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPets queries the pets edge of a Breed.
func (c *BreedClient) QueryPets(_m *Breed) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(breed.Table, breed.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, breed.PetsTable, breed.PetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BreedClient) Hooks() []Hook {
	return c.hooks.Breed
}

// Interceptors returns the client interceptors.
func (c *BreedClient) Interceptors() []Interceptor {
	return c.inters.Breed
}

func (c *BreedClient) mutate(ctx context.Context, m *BreedMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BreedCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BreedUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BreedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BreedDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Breed mutation op: %q", m.Op())
	}
}

// DonorResponseClient is a client for the DonorResponse schema.
type DonorResponseClient struct {
	config
}

// NewDonorResponseClient returns a client for the DonorResponse from the given config.
func NewDonorResponseClient(c config) *DonorResponseClient {
	return &DonorResponseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `donorresponse.Hooks(f(g(h())))`.
func (c *DonorResponseClient) Use(hooks ...Hook) {
	c.hooks.DonorResponse = append(c.hooks.DonorResponse, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `donorresponse.Intercept(f(g(h())))`.
func (c *DonorResponseClient) Intercept(interceptors ...Interceptor) {
	c.inters.DonorResponse = append(c.inters.DonorResponse, interceptors...)
}

// Create returns a builder for creating a DonorResponse entity.
func (c *DonorResponseClient) Create() *DonorResponseCreate {
	mutation := newDonorResponseMutation(c.config, OpCreate)
	return &DonorResponseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DonorResponse entities.
func (c *DonorResponseClient) CreateBulk(builders ...*DonorResponseCreate) *DonorResponseCreateBulk {
	return &DonorResponseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DonorResponseClient) MapCreateBulk(slice any, setFunc func(*DonorResponseCreate, int)) *DonorResponseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DonorResponseCreateBulk{err: fmt.Errorf("calling to DonorResponseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DonorResponseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DonorResponseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DonorResponse.
func (c *DonorResponseClient) Update() *DonorResponseUpdate {
	mutation := newDonorResponseMutation(c.config, OpUpdate)
	return &DonorResponseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DonorResponseClient) UpdateOne(_m *DonorResponse) *DonorResponseUpdateOne {
	mutation := newDonorResponseMutation(c.config, OpUpdateOne, withDonorResponse(_m))
	return &DonorResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DonorResponseClient) UpdateOneID(id string) *DonorResponseUpdateOne {
	mutation := newDonorResponseMutation(c.config, OpUpdateOne, withDonorResponseID(id))
	return &DonorResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DonorResponse.
func (c *DonorResponseClient) Delete() *DonorResponseDelete {
	mutation := newDonorResponseMutation(c.config, OpDelete)
	return &DonorResponseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DonorResponseClient) DeleteOne(_m *DonorResponse) *DonorResponseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DonorResponseClient) DeleteOneID(id string) *DonorResponseDeleteOne {
	builder := c.Delete().Where(donorresponse.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DonorResponseDeleteOne{builder}
}

// Query returns a query builder for DonorResponse.
func (c *DonorResponseClient) Query() *DonorResponseQuery {
	return &DonorResponseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDonorResponse},
		inters: c.Interceptors(),
	}
}

// Get returns a DonorResponse entity by its id.
func (c *DonorResponseClient) Get(ctx context.Context, id string) (*DonorResponse, error) {
	return c.Query().Where(donorresponse.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DonorResponseClient) GetX(ctx context.Context, id string) *DonorResponse {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRequest queries the request edge of a DonorResponse.
func (c *DonorResponseClient) QueryRequest(_m *DonorResponse) *BloodSearchRequestQuery {
	query := (&BloodSearchRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(donorresponse.Table, donorresponse.FieldID, id),
			sqlgraph.To(bloodsearchrequest.Table, bloodsearchrequest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, donorresponse.RequestTable, donorresponse.RequestColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDonor queries the donor edge of a DonorResponse.
func (c *DonorResponseClient) QueryDonor(_m *DonorResponse) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(donorresponse.Table, donorresponse.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, donorresponse.DonorTable, donorresponse.DonorColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DonorResponseClient) Hooks() []Hook {
	return c.hooks.DonorResponse
}

// Interceptors returns the client interceptors.
func (c *DonorResponseClient) Interceptors() []Interceptor {
	inters := c.inters.DonorResponse
	return append(inters[:len(inters):len(inters)], donorresponse.Interceptors[:]...)
}

func (c *DonorResponseClient) mutate(ctx context.Context, m *DonorResponseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DonorResponseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DonorResponseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DonorResponseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DonorResponseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DonorResponse mutation op: %q", m.Op())
	}
}

// LocationClient is a client for the Location schema.
type LocationClient struct {
	config
}

// NewLocationClient returns a client for the Location from the given config.
func NewLocationClient(c config) *LocationClient {
	return &LocationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `location.Hooks(f(g(h())))`.
func (c *LocationClient) Use(hooks ...Hook) {
	c.hooks.Location = append(c.hooks.Location, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `location.Intercept(f(g(h())))`.
func (c *LocationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Location = append(c.inters.Location, interceptors...)
}

// Create returns a builder for creating a Location entity.
func (c *LocationClient) Create() *LocationCreate {
	mutation := newLocationMutation(c.config, OpCreate)
	return &LocationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Location entities.
func (c *LocationClient) CreateBulk(builders ...*LocationCreate) *LocationCreateBulk {
	return &LocationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LocationClient) MapCreateBulk(slice any, setFunc func(*LocationCreate, int)) *LocationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LocationCreateBulk{err: fmt.Errorf("calling to LocationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LocationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LocationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Location.
func (c *LocationClient) Update() *LocationUpdate {
	mutation := newLocationMutation(c.config, OpUpdate)
	return &LocationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LocationClient) UpdateOne(_m *Location) *LocationUpdateOne {
	mutation := newLocationMutation(c.config, OpUpdateOne, withLocation(_m))
	return &LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LocationClient) UpdateOneID(id string) *LocationUpdateOne {
	mutation := newLocationMutation(c.config, OpUpdateOne, withLocationID(id))
	return &LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Location.
func (c *LocationClient) Delete() *LocationDelete {
	mutation := newLocationMutation(c.config, OpDelete)
	return &LocationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LocationClient) DeleteOne(_m *Location) *LocationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LocationClient) DeleteOneID(id string) *LocationDeleteOne {
	builder := c.Delete().Where(location.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LocationDeleteOne{builder}
}

// Query returns a query builder for Location.
func (c *LocationClient) Query() *LocationQuery {
	return &LocationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLocation},
		inters: c.Interceptors(),
	}
}

// Get returns a Location entity by its id.
func (c *LocationClient) Get(ctx context.Context, id string) (*Location, error) {
	return c.Query().Where(location.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LocationClient) GetX(ctx context.Context, id string) *Location {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Location.
func (c *LocationClient) QueryUsers(_m *Location) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(location.Table, location.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, location.UsersTable, location.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LocationClient) Hooks() []Hook {
	return c.hooks.Location
}

// Interceptors returns the client interceptors.
func (c *LocationClient) Interceptors() []Interceptor {
	return c.inters.Location
}

func (c *LocationClient) mutate(ctx context.Context, m *LocationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LocationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LocationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LocationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LocationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Location mutation op: %q", m.Op())
	}
}

// PetClient is a client for the Pet schema.
type PetClient struct {
	config
}

// NewPetClient returns a client for the Pet from the given config.
func NewPetClient(c config) *PetClient {
	return &PetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pet.Hooks(f(g(h())))`.
func (c *PetClient) Use(hooks ...Hook) {
	c.hooks.Pet = append(c.hooks.Pet, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pet.Intercept(f(g(h())))`.
func (c *PetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pet = append(c.inters.Pet, interceptors...)
}

// Create returns a builder for creating a Pet entity.
func (c *PetClient) Create() *PetCreate {
	mutation := newPetMutation(c.config, OpCreate)
	return &PetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pet entities.
func (c *PetClient) CreateBulk(builders ...*PetCreate) *PetCreateBulk {
	return &PetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetClient) MapCreateBulk(slice any, setFunc func(*PetCreate, int)) *PetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetCreateBulk{err: fmt.Errorf("calling to PetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pet.
func (c *PetClient) Update() *PetUpdate {
	mutation := newPetMutation(c.config, OpUpdate)
	return &PetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetClient) UpdateOne(_m *Pet) *PetUpdateOne {
	mutation := newPetMutation(c.config, OpUpdateOne, withPet(_m))
	return &PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetClient) UpdateOneID(id string) *PetUpdateOne {
	mutation := newPetMutation(c.config, OpUpdateOne, withPetID(id))
	return &PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pet.
func (c *PetClient) Delete() *PetDelete {
	mutation := newPetMutation(c.config, OpDelete)
	return &PetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetClient) DeleteOne(_m *Pet) *PetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetClient) DeleteOneID(id string) *PetDeleteOne {
	builder := c.Delete().Where(pet.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetDeleteOne{builder}
}

// Query returns a query builder for Pet.
func (c *PetClient) Query() *PetQuery {
	return &PetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePet},
		inters: c.Interceptors(),
	}
}

// Get returns a Pet entity by its id.
func (c *PetClient) Get(ctx context.Context, id string) (*Pet, error) {
	return c.Query().Where(pet.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetClient) GetX(ctx context.Context, id string) *Pet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Pet.
func (c *PetClient) QueryOwner(_m *Pet) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pet.OwnerTable, pet.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryHealth queries the health edge of a Pet.
func (c *PetClient) QueryHealth(_m *Pet) *PetHealthQuery {
	query := (&PetHealthClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(pethealth.Table, pethealth.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, pet.HealthTable, pet.HealthColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTreatments queries the treatments edge of a Pet.
func (c *PetClient) QueryTreatments(_m *Pet) *PetTreatmentQuery {
	query := (&PetTreatmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(pettreatment.Table, pettreatment.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, pet.TreatmentsTable, pet.TreatmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAnalyses queries the analyses edge of a Pet.
func (c *PetClient) QueryAnalyses(_m *Pet) *PetAnalysisQuery {
	query := (&PetAnalysisClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(petanalysis.Table, petanalysis.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, pet.AnalysesTable, pet.AnalysesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBonuses queries the bonuses edge of a Pet.
func (c *PetClient) QueryBonuses(_m *Pet) *PetBonusQuery {
	query := (&PetBonusClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(petbonus.Table, petbonus.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, pet.BonusesTable, pet.BonusesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBreedRef queries the breed_ref edge of a Pet.
func (c *PetClient) QueryBreedRef(_m *Pet) *BreedQuery {
	query := (&BreedClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(breed.Table, breed.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pet.BreedRefTable, pet.BreedRefColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBloodGroupRef queries the blood_group_ref edge of a Pet.
func (c *PetClient) QueryBloodGroupRef(_m *Pet) *BloodGroupQuery {
	query := (&BloodGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(bloodgroup.Table, bloodgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pet.BloodGroupRefTable, pet.BloodGroupRefColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDonations queries the donations edge of a Pet.
func (c *PetClient) QueryDonations(_m *Pet) *DonorResponseQuery {
	query := (&DonorResponseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(donorresponse.Table, donorresponse.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, pet.DonationsTable, pet.DonationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBloodSearchRequest queries the blood_search_request edge of a Pet.
func (c *PetClient) QueryBloodSearchRequest(_m *Pet) *BloodSearchRequestQuery {
	query := (&BloodSearchRequestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pet.Table, pet.FieldID, id),
			sqlgraph.To(bloodsearchrequest.Table, bloodsearchrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, pet.BloodSearchRequestTable, pet.BloodSearchRequestColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetClient) Hooks() []Hook {
	return c.hooks.Pet
}

// Interceptors returns the client interceptors.
func (c *PetClient) Interceptors() []Interceptor {
	inters := c.inters.Pet
	return append(inters[:len(inters):len(inters)], pet.Interceptors[:]...)
}

func (c *PetClient) mutate(ctx context.Context, m *PetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pet mutation op: %q", m.Op())
	}
}

// PetAnalysisClient is a client for the PetAnalysis schema.
type PetAnalysisClient struct {
	config
}

// NewPetAnalysisClient returns a client for the PetAnalysis from the given config.
func NewPetAnalysisClient(c config) *PetAnalysisClient {
	return &PetAnalysisClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `petanalysis.Hooks(f(g(h())))`.
func (c *PetAnalysisClient) Use(hooks ...Hook) {
	c.hooks.PetAnalysis = append(c.hooks.PetAnalysis, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `petanalysis.Intercept(f(g(h())))`.
func (c *PetAnalysisClient) Intercept(interceptors ...Interceptor) {
	c.inters.PetAnalysis = append(c.inters.PetAnalysis, interceptors...)
}

// Create returns a builder for creating a PetAnalysis entity.
func (c *PetAnalysisClient) Create() *PetAnalysisCreate {
	mutation := newPetAnalysisMutation(c.config, OpCreate)
	return &PetAnalysisCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PetAnalysis entities.
func (c *PetAnalysisClient) CreateBulk(builders ...*PetAnalysisCreate) *PetAnalysisCreateBulk {
	return &PetAnalysisCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetAnalysisClient) MapCreateBulk(slice any, setFunc func(*PetAnalysisCreate, int)) *PetAnalysisCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetAnalysisCreateBulk{err: fmt.Errorf("calling to PetAnalysisClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetAnalysisCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetAnalysisCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PetAnalysis.
func (c *PetAnalysisClient) Update() *PetAnalysisUpdate {
	mutation := newPetAnalysisMutation(c.config, OpUpdate)
	return &PetAnalysisUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetAnalysisClient) UpdateOne(_m *PetAnalysis) *PetAnalysisUpdateOne {
	mutation := newPetAnalysisMutation(c.config, OpUpdateOne, withPetAnalysis(_m))
	return &PetAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetAnalysisClient) UpdateOneID(id string) *PetAnalysisUpdateOne {
	mutation := newPetAnalysisMutation(c.config, OpUpdateOne, withPetAnalysisID(id))
	return &PetAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PetAnalysis.
func (c *PetAnalysisClient) Delete() *PetAnalysisDelete {
	mutation := newPetAnalysisMutation(c.config, OpDelete)
	return &PetAnalysisDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetAnalysisClient) DeleteOne(_m *PetAnalysis) *PetAnalysisDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetAnalysisClient) DeleteOneID(id string) *PetAnalysisDeleteOne {
	builder := c.Delete().Where(petanalysis.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetAnalysisDeleteOne{builder}
}

// Query returns a query builder for PetAnalysis.
func (c *PetAnalysisClient) Query() *PetAnalysisQuery {
	return &PetAnalysisQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePetAnalysis},
		inters: c.Interceptors(),
	}
}

// Get returns a PetAnalysis entity by its id.
func (c *PetAnalysisClient) Get(ctx context.Context, id string) (*PetAnalysis, error) {
	return c.Query().Where(petanalysis.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetAnalysisClient) GetX(ctx context.Context, id string) *PetAnalysis {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a PetAnalysis.
func (c *PetAnalysisClient) QueryOwner(_m *PetAnalysis) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(petanalysis.Table, petanalysis.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, petanalysis.OwnerTable, petanalysis.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetAnalysisClient) Hooks() []Hook {
	return c.hooks.PetAnalysis
}

// Interceptors returns the client interceptors.
func (c *PetAnalysisClient) Interceptors() []Interceptor {
	inters := c.inters.PetAnalysis
	return append(inters[:len(inters):len(inters)], petanalysis.Interceptors[:]...)
}

func (c *PetAnalysisClient) mutate(ctx context.Context, m *PetAnalysisMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetAnalysisCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetAnalysisUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetAnalysisDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PetAnalysis mutation op: %q", m.Op())
	}
}

// PetBonusClient is a client for the PetBonus schema.
type PetBonusClient struct {
	config
}

// NewPetBonusClient returns a client for the PetBonus from the given config.
func NewPetBonusClient(c config) *PetBonusClient {
	return &PetBonusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `petbonus.Hooks(f(g(h())))`.
func (c *PetBonusClient) Use(hooks ...Hook) {
	c.hooks.PetBonus = append(c.hooks.PetBonus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `petbonus.Intercept(f(g(h())))`.
func (c *PetBonusClient) Intercept(interceptors ...Interceptor) {
	c.inters.PetBonus = append(c.inters.PetBonus, interceptors...)
}

// Create returns a builder for creating a PetBonus entity.
func (c *PetBonusClient) Create() *PetBonusCreate {
	mutation := newPetBonusMutation(c.config, OpCreate)
	return &PetBonusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PetBonus entities.
func (c *PetBonusClient) CreateBulk(builders ...*PetBonusCreate) *PetBonusCreateBulk {
	return &PetBonusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetBonusClient) MapCreateBulk(slice any, setFunc func(*PetBonusCreate, int)) *PetBonusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetBonusCreateBulk{err: fmt.Errorf("calling to PetBonusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetBonusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetBonusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PetBonus.
func (c *PetBonusClient) Update() *PetBonusUpdate {
	mutation := newPetBonusMutation(c.config, OpUpdate)
	return &PetBonusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetBonusClient) UpdateOne(_m *PetBonus) *PetBonusUpdateOne {
	mutation := newPetBonusMutation(c.config, OpUpdateOne, withPetBonus(_m))
	return &PetBonusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetBonusClient) UpdateOneID(id string) *PetBonusUpdateOne {
	mutation := newPetBonusMutation(c.config, OpUpdateOne, withPetBonusID(id))
	return &PetBonusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PetBonus.
func (c *PetBonusClient) Delete() *PetBonusDelete {
	mutation := newPetBonusMutation(c.config, OpDelete)
	return &PetBonusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetBonusClient) DeleteOne(_m *PetBonus) *PetBonusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetBonusClient) DeleteOneID(id string) *PetBonusDeleteOne {
	builder := c.Delete().Where(petbonus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetBonusDeleteOne{builder}
}

// Query returns a query builder for PetBonus.
func (c *PetBonusClient) Query() *PetBonusQuery {
	return &PetBonusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePetBonus},
		inters: c.Interceptors(),
	}
}

// Get returns a PetBonus entity by its id.
func (c *PetBonusClient) Get(ctx context.Context, id string) (*PetBonus, error) {
	return c.Query().Where(petbonus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetBonusClient) GetX(ctx context.Context, id string) *PetBonus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a PetBonus.
func (c *PetBonusClient) QueryOwner(_m *PetBonus) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(petbonus.Table, petbonus.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, petbonus.OwnerTable, petbonus.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetBonusClient) Hooks() []Hook {
	return c.hooks.PetBonus
}

// Interceptors returns the client interceptors.
func (c *PetBonusClient) Interceptors() []Interceptor {
	inters := c.inters.PetBonus
	return append(inters[:len(inters):len(inters)], petbonus.Interceptors[:]...)
}

func (c *PetBonusClient) mutate(ctx context.Context, m *PetBonusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetBonusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetBonusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetBonusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetBonusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PetBonus mutation op: %q", m.Op())
	}
}

// PetHealthClient is a client for the PetHealth schema.
type PetHealthClient struct {
	config
}

// NewPetHealthClient returns a client for the PetHealth from the given config.
func NewPetHealthClient(c config) *PetHealthClient {
	return &PetHealthClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pethealth.Hooks(f(g(h())))`.
func (c *PetHealthClient) Use(hooks ...Hook) {
	c.hooks.PetHealth = append(c.hooks.PetHealth, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pethealth.Intercept(f(g(h())))`.
func (c *PetHealthClient) Intercept(interceptors ...Interceptor) {
	c.inters.PetHealth = append(c.inters.PetHealth, interceptors...)
}

// Create returns a builder for creating a PetHealth entity.
func (c *PetHealthClient) Create() *PetHealthCreate {
	mutation := newPetHealthMutation(c.config, OpCreate)
	return &PetHealthCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PetHealth entities.
func (c *PetHealthClient) CreateBulk(builders ...*PetHealthCreate) *PetHealthCreateBulk {
	return &PetHealthCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetHealthClient) MapCreateBulk(slice any, setFunc func(*PetHealthCreate, int)) *PetHealthCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetHealthCreateBulk{err: fmt.Errorf("calling to PetHealthClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetHealthCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetHealthCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PetHealth.
func (c *PetHealthClient) Update() *PetHealthUpdate {
	mutation := newPetHealthMutation(c.config, OpUpdate)
	return &PetHealthUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetHealthClient) UpdateOne(_m *PetHealth) *PetHealthUpdateOne {
	mutation := newPetHealthMutation(c.config, OpUpdateOne, withPetHealth(_m))
	return &PetHealthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetHealthClient) UpdateOneID(id string) *PetHealthUpdateOne {
	mutation := newPetHealthMutation(c.config, OpUpdateOne, withPetHealthID(id))
	return &PetHealthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PetHealth.
func (c *PetHealthClient) Delete() *PetHealthDelete {
	mutation := newPetHealthMutation(c.config, OpDelete)
	return &PetHealthDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetHealthClient) DeleteOne(_m *PetHealth) *PetHealthDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetHealthClient) DeleteOneID(id string) *PetHealthDeleteOne {
	builder := c.Delete().Where(pethealth.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetHealthDeleteOne{builder}
}

// Query returns a query builder for PetHealth.
func (c *PetHealthClient) Query() *PetHealthQuery {
	return &PetHealthQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePetHealth},
		inters: c.Interceptors(),
	}
}

// Get returns a PetHealth entity by its id.
func (c *PetHealthClient) Get(ctx context.Context, id string) (*PetHealth, error) {
	return c.Query().Where(pethealth.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetHealthClient) GetX(ctx context.Context, id string) *PetHealth {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a PetHealth.
func (c *PetHealthClient) QueryOwner(_m *PetHealth) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pethealth.Table, pethealth.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, pethealth.OwnerTable, pethealth.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetHealthClient) Hooks() []Hook {
	return c.hooks.PetHealth
}

// Interceptors returns the client interceptors.
func (c *PetHealthClient) Interceptors() []Interceptor {
	inters := c.inters.PetHealth
	return append(inters[:len(inters):len(inters)], pethealth.Interceptors[:]...)
}

func (c *PetHealthClient) mutate(ctx context.Context, m *PetHealthMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetHealthCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetHealthUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetHealthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetHealthDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PetHealth mutation op: %q", m.Op())
	}
}

// PetTreatmentClient is a client for the PetTreatment schema.
type PetTreatmentClient struct {
	config
}

// NewPetTreatmentClient returns a client for the PetTreatment from the given config.
func NewPetTreatmentClient(c config) *PetTreatmentClient {
	return &PetTreatmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pettreatment.Hooks(f(g(h())))`.
func (c *PetTreatmentClient) Use(hooks ...Hook) {
	c.hooks.PetTreatment = append(c.hooks.PetTreatment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pettreatment.Intercept(f(g(h())))`.
func (c *PetTreatmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.PetTreatment = append(c.inters.PetTreatment, interceptors...)
}

// Create returns a builder for creating a PetTreatment entity.
func (c *PetTreatmentClient) Create() *PetTreatmentCreate {
	mutation := newPetTreatmentMutation(c.config, OpCreate)
	return &PetTreatmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PetTreatment entities.
func (c *PetTreatmentClient) CreateBulk(builders ...*PetTreatmentCreate) *PetTreatmentCreateBulk {
	return &PetTreatmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PetTreatmentClient) MapCreateBulk(slice any, setFunc func(*PetTreatmentCreate, int)) *PetTreatmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PetTreatmentCreateBulk{err: fmt.Errorf("calling to PetTreatmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PetTreatmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PetTreatmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PetTreatment.
func (c *PetTreatmentClient) Update() *PetTreatmentUpdate {
	mutation := newPetTreatmentMutation(c.config, OpUpdate)
	return &PetTreatmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PetTreatmentClient) UpdateOne(_m *PetTreatment) *PetTreatmentUpdateOne {
	mutation := newPetTreatmentMutation(c.config, OpUpdateOne, withPetTreatment(_m))
	return &PetTreatmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PetTreatmentClient) UpdateOneID(id string) *PetTreatmentUpdateOne {
	mutation := newPetTreatmentMutation(c.config, OpUpdateOne, withPetTreatmentID(id))
	return &PetTreatmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PetTreatment.
func (c *PetTreatmentClient) Delete() *PetTreatmentDelete {
	mutation := newPetTreatmentMutation(c.config, OpDelete)
	return &PetTreatmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PetTreatmentClient) DeleteOne(_m *PetTreatment) *PetTreatmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PetTreatmentClient) DeleteOneID(id string) *PetTreatmentDeleteOne {
	builder := c.Delete().Where(pettreatment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PetTreatmentDeleteOne{builder}
}

// Query returns a query builder for PetTreatment.
func (c *PetTreatmentClient) Query() *PetTreatmentQuery {
	return &PetTreatmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePetTreatment},
		inters: c.Interceptors(),
	}
}

// Get returns a PetTreatment entity by its id.
func (c *PetTreatmentClient) Get(ctx context.Context, id string) (*PetTreatment, error) {
	return c.Query().Where(pettreatment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PetTreatmentClient) GetX(ctx context.Context, id string) *PetTreatment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a PetTreatment.
func (c *PetTreatmentClient) QueryOwner(_m *PetTreatment) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pettreatment.Table, pettreatment.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, pettreatment.OwnerTable, pettreatment.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PetTreatmentClient) Hooks() []Hook {
	return c.hooks.PetTreatment
}

// Interceptors returns the client interceptors.
func (c *PetTreatmentClient) Interceptors() []Interceptor {
	inters := c.inters.PetTreatment
	return append(inters[:len(inters):len(inters)], pettreatment.Interceptors[:]...)
}

func (c *PetTreatmentClient) mutate(ctx context.Context, m *PetTreatmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PetTreatmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PetTreatmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PetTreatmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PetTreatmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PetTreatment mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPets queries the pets edge of a User.
func (c *UserClient) QueryPets(_m *User) *PetQuery {
	query := (&PetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(pet.Table, pet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PetsTable, user.PetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLocation queries the location edge of a User.
func (c *UserClient) QueryLocation(_m *User) *LocationQuery {
	query := (&LocationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.LocationTable, user.LocationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	inters := c.inters.User
	return append(inters[:len(inters):len(inters)], user.Interceptors[:]...)
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BloodComponent, BloodGroup, BloodSearchRequest, Breed, DonorResponse, Location,
		Pet, PetAnalysis, PetBonus, PetHealth, PetTreatment, User []ent.Hook
	}
	inters struct {
		BloodComponent, BloodGroup, BloodSearchRequest, Breed, DonorResponse, Location,
		Pet, PetAnalysis, PetBonus, PetHealth, PetTreatment, User []ent.Interceptor
	}
)
