// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pet"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/pethealth"
)

// PetHealth is the model entity for the PetHealth schema.
type PetHealth struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ReproductiveStatus holds the value of the "reproductive_status" field.
	ReproductiveStatus pethealth.ReproductiveStatus `json:"reproductiveStatus"`
	// HealthStatus holds the value of the "health_status" field.
	HealthStatus pethealth.HealthStatus `json:"healthStatus"`
	// LastDonation holds the value of the "last_donation" field.
	LastDonation *time.Time `json:"lastDonation"`
	// Transfused holds the value of the "transfused" field.
	Transfused bool `json:"transfused"`
	// Medications holds the value of the "medications" field.
	Medications string `json:"medications"`
	// SurgicalInterventions holds the value of the "surgical_interventions" field.
	SurgicalInterventions string `json:"surgicalInterventions"`
	// PetID holds the value of the "pet_id" field.
	PetID string `json:"petId"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PetHealthQuery when eager-loading is set.
	Edges        PetHealthEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PetHealthEdges holds the relations/edges for other nodes in the graph.
type PetHealthEdges struct {
	// Pet holds the value of the pet edge.
	Pet *Pet `json:"pet,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PetOrErr returns the Pet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PetHealthEdges) PetOrErr() (*Pet, error) {
	if e.Pet != nil {
		return e.Pet, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: pet.Label}
	}
	return nil, &NotLoadedError{edge: "pet"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PetHealth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pethealth.FieldTransfused:
			values[i] = new(sql.NullBool)
		case pethealth.FieldID:
			values[i] = new(sql.NullInt64)
		case pethealth.FieldReproductiveStatus, pethealth.FieldHealthStatus, pethealth.FieldMedications, pethealth.FieldSurgicalInterventions, pethealth.FieldPetID:
			values[i] = new(sql.NullString)
		case pethealth.FieldLastDonation:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PetHealth fields.
func (_m *PetHealth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pethealth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pethealth.FieldReproductiveStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reproductive_status", values[i])
			} else if value.Valid {
				_m.ReproductiveStatus = pethealth.ReproductiveStatus(value.String)
			}
		case pethealth.FieldHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_status", values[i])
			} else if value.Valid {
				_m.HealthStatus = pethealth.HealthStatus(value.String)
			}
		case pethealth.FieldLastDonation:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_donation", values[i])
			} else if value.Valid {
				_m.LastDonation = new(time.Time)
				*_m.LastDonation = value.Time
			}
		case pethealth.FieldTransfused:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field transfused", values[i])
			} else if value.Valid {
				_m.Transfused = value.Bool
			}
		case pethealth.FieldMedications:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field medications", values[i])
			} else if value.Valid {
				_m.Medications = value.String
			}
		case pethealth.FieldSurgicalInterventions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field surgical_interventions", values[i])
			} else if value.Valid {
				_m.SurgicalInterventions = value.String
			}
		case pethealth.FieldPetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pet_id", values[i])
			} else if value.Valid {
				_m.PetID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PetHealth.
// This includes values selected through modifiers, order, etc.
func (_m *PetHealth) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPet queries the "pet" edge of the PetHealth entity.
func (_m *PetHealth) QueryPet() *PetQuery {
	return NewPetHealthClient(_m.config).QueryPet(_m)
}

// Update returns a builder for updating this PetHealth.
// Note that you need to call PetHealth.Unwrap() before calling this method if this PetHealth
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PetHealth) Update() *PetHealthUpdateOne {
	return NewPetHealthClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PetHealth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PetHealth) Unwrap() *PetHealth {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PetHealth is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PetHealth) String() string {
	var builder strings.Builder
	builder.WriteString("PetHealth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reproductive_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReproductiveStatus))
	builder.WriteString(", ")
	builder.WriteString("health_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthStatus))
	builder.WriteString(", ")
	if v := _m.LastDonation; v != nil {
		builder.WriteString("last_donation=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("transfused=")
	builder.WriteString(fmt.Sprintf("%v", _m.Transfused))
	builder.WriteString(", ")
	builder.WriteString("medications=")
	builder.WriteString(_m.Medications)
	builder.WriteString(", ")
	builder.WriteString("surgical_interventions=")
	builder.WriteString(_m.SurgicalInterventions)
	builder.WriteString(", ")
	builder.WriteString("pet_id=")
	builder.WriteString(_m.PetID)
	builder.WriteByte(')')
	return builder.String()
}

// PetHealths is a parsable slice of PetHealth.
type PetHealths []*PetHealth
