/* tslint:disable */
/* eslint-disable */
/**
 * однойкрови.рф
 * API сервиса однойкрови.рф для донороcства крови и помощи животным
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsVetClinic } from './ModelsVetClinic';
import {
    ModelsVetClinicFromJSON,
    ModelsVetClinicFromJSONTyped,
    ModelsVetClinicToJSON,
    ModelsVetClinicToJSONTyped,
} from './ModelsVetClinic';

/**
 * 
 * @export
 * @interface ServicesVetClinicProfile
 */
export interface ServicesVetClinicProfile {
    /**
     * 
     * @type {ModelsVetClinic}
     * @memberof ServicesVetClinicProfile
     */
    clinic?: ModelsVetClinic;
}

/**
 * Check if a given object implements the ServicesVetClinicProfile interface.
 */
export function instanceOfServicesVetClinicProfile(value: object): value is ServicesVetClinicProfile {
    return true;
}

export function ServicesVetClinicProfileFromJSON(json: any): ServicesVetClinicProfile {
    return ServicesVetClinicProfileFromJSONTyped(json, false);
}

export function ServicesVetClinicProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesVetClinicProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'clinic': json['clinic'] == null ? undefined : ModelsVetClinicFromJSON(json['clinic']),
    };
}

export function ServicesVetClinicProfileToJSON(json: any): ServicesVetClinicProfile {
    return ServicesVetClinicProfileToJSONTyped(json, false);
}

export function ServicesVetClinicProfileToJSONTyped(value?: ServicesVetClinicProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clinic': ModelsVetClinicToJSON(value['clinic']),
    };
}

