/* tslint:disable */
/* eslint-disable */
/**
 * однойкрови.рф
 * API сервиса однойкрови.рф для донороcства крови и помощи животным
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsBloodStockStatus } from './ModelsBloodStockStatus';
import {
    ModelsBloodStockStatusFromJSON,
    ModelsBloodStockStatusFromJSONTyped,
    ModelsBloodStockStatusToJSON,
    ModelsBloodStockStatusToJSONTyped,
} from './ModelsBloodStockStatus';
import type { ModelsPetType } from './ModelsPetType';
import {
    ModelsPetTypeFromJSON,
    ModelsPetTypeFromJSONTyped,
    ModelsPetTypeToJSON,
    ModelsPetTypeToJSONTyped,
} from './ModelsPetType';

/**
 * 
 * @export
 * @interface ServicesBloodStockCreate
 */
export interface ServicesBloodStockCreate {
    /**
     * 
     * @type {number}
     * @memberof ServicesBloodStockCreate
     */
    bloodTypeId: number;
    /**
     * 
     * @type {number}
     * @memberof ServicesBloodStockCreate
     */
    clinicId?: number;
    /**
     * формат: "2024-12-31"
     * @type {string}
     * @memberof ServicesBloodStockCreate
     */
    expirationDate?: string;
    /**
     * 
     * @type {ModelsPetType}
     * @memberof ServicesBloodStockCreate
     */
    petType: ModelsPetType;
    /**
     * 
     * @type {ModelsBloodStockStatus}
     * @memberof ServicesBloodStockCreate
     */
    status?: ModelsBloodStockStatus;
    /**
     * 
     * @type {number}
     * @memberof ServicesBloodStockCreate
     */
    volumeMl?: number;
}



/**
 * Check if a given object implements the ServicesBloodStockCreate interface.
 */
export function instanceOfServicesBloodStockCreate(value: object): value is ServicesBloodStockCreate {
    if (!('bloodTypeId' in value) || value['bloodTypeId'] === undefined) return false;
    if (!('petType' in value) || value['petType'] === undefined) return false;
    return true;
}

export function ServicesBloodStockCreateFromJSON(json: any): ServicesBloodStockCreate {
    return ServicesBloodStockCreateFromJSONTyped(json, false);
}

export function ServicesBloodStockCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesBloodStockCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'bloodTypeId': json['bloodTypeId'],
        'clinicId': json['clinicId'] == null ? undefined : json['clinicId'],
        'expirationDate': json['expirationDate'] == null ? undefined : json['expirationDate'],
        'petType': ModelsPetTypeFromJSON(json['petType']),
        'status': json['status'] == null ? undefined : ModelsBloodStockStatusFromJSON(json['status']),
        'volumeMl': json['volumeMl'] == null ? undefined : json['volumeMl'],
    };
}

export function ServicesBloodStockCreateToJSON(json: any): ServicesBloodStockCreate {
    return ServicesBloodStockCreateToJSONTyped(json, false);
}

export function ServicesBloodStockCreateToJSONTyped(value?: ServicesBloodStockCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bloodTypeId': value['bloodTypeId'],
        'clinicId': value['clinicId'],
        'expirationDate': value['expirationDate'],
        'petType': ModelsPetTypeToJSON(value['petType']),
        'status': ModelsBloodStockStatusToJSON(value['status']),
        'volumeMl': value['volumeMl'],
    };
}

