syntax = "proto3";

package bloodsearch.v1;

message PetRow {
  string pet_id = 1;
  string pet_type = 2;
  string blood_group = 3;
  repeated string blood_components = 4;
  float blood_volume = 5;
  repeated int32 regions = 6;
  bool small_pets_notify_allowed = 7;
  string status = 8;
}

message PetRowStatus {
  int64 row_id = 1;
  string status = 2;
}

message GetPetRows {
  string pet_type = 1;
  string blood_group = 2;
  repeated int32 regions = 3;
}

message PetRows {
  repeated PetRow pets = 1;
}

service BloodSearchPool {
  rpc AddPet(PetRow) returns (PetRowStatus);
  rpc GetPets(GetPetRows) returns (PetRows);
}
