// Code generated by ent, DO NOT EDIT.

package bloodsearchrequest

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bloodsearchrequest type in the database.
	Label = "blood_search_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldPetID holds the string denoting the pet_id field in the database.
	FieldPetID = "pet_id"
	// FieldBloodVolumeNeeded holds the string denoting the blood_volume_needed field in the database.
	FieldBloodVolumeNeeded = "blood_volume_needed"
	// FieldBloodVolumeReserved holds the string denoting the blood_volume_reserved field in the database.
	FieldBloodVolumeReserved = "blood_volume_reserved"
	// FieldRegions holds the string denoting the regions field in the database.
	FieldRegions = "regions"
	// FieldSmallPetsNotifyAllowed holds the string denoting the small_pets_notify_allowed field in the database.
	FieldSmallPetsNotifyAllowed = "small_pets_notify_allowed"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPhotoUrls holds the string denoting the photo_urls field in the database.
	FieldPhotoUrls = "photo_urls"
	// FieldBloodGroupNames holds the string denoting the blood_group_names field in the database.
	FieldBloodGroupNames = "blood_group_names"
	// FieldBloodComponentIds holds the string denoting the blood_component_ids field in the database.
	FieldBloodComponentIds = "blood_component_ids"
	// EdgePet holds the string denoting the pet edge name in mutations.
	EdgePet = "pet"
	// Table holds the table name of the bloodsearchrequest in the database.
	Table = "blood_requests"
	// PetTable is the table that holds the pet relation/edge.
	PetTable = "blood_requests"
	// PetInverseTable is the table name for the Pet entity.
	// It exists in this package in order to avoid circular dependency with the "pet" package.
	PetInverseTable = "pets"
	// PetColumn is the table column denoting the pet relation/edge.
	PetColumn = "pet_id"
)

// Columns holds all SQL columns for bloodsearchrequest fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldPetID,
	FieldBloodVolumeNeeded,
	FieldBloodVolumeReserved,
	FieldRegions,
	FieldSmallPetsNotifyAllowed,
	FieldStatus,
	FieldDescription,
	FieldPhotoUrls,
	FieldBloodGroupNames,
	FieldBloodComponentIds,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/artesipov-alt/odnoi-krovi-app/ent/runtime"
var (
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBloodVolumeReserved holds the default value on creation for the "blood_volume_reserved" field.
	DefaultBloodVolumeReserved int32
	// DefaultSmallPetsNotifyAllowed holds the default value on creation for the "small_pets_notify_allowed" field.
	DefaultSmallPetsNotifyAllowed bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive Status = "active"
	StatusClosed Status = "closed"
	StatusDraft  Status = "draft"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusClosed, StatusDraft:
		return nil
	default:
		return fmt.Errorf("bloodsearchrequest: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BloodSearchRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByPetID orders the results by the pet_id field.
func ByPetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPetID, opts...).ToFunc()
}

// ByBloodVolumeNeeded orders the results by the blood_volume_needed field.
func ByBloodVolumeNeeded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBloodVolumeNeeded, opts...).ToFunc()
}

// ByBloodVolumeReserved orders the results by the blood_volume_reserved field.
func ByBloodVolumeReserved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBloodVolumeReserved, opts...).ToFunc()
}

// BySmallPetsNotifyAllowed orders the results by the small_pets_notify_allowed field.
func BySmallPetsNotifyAllowed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSmallPetsNotifyAllowed, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPetField orders the results by pet field.
func ByPetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPetStep(), sql.OrderByField(field, opts...))
	}
}
func newPetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PetTable, PetColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
