// Code generated by ent, DO NOT EDIT.

package pethealth

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldID, id))
}

// LastDonation applies equality check predicate on the "last_donation" field. It's identical to LastDonationEQ.
func LastDonation(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldLastDonation, v))
}

// Transfused applies equality check predicate on the "transfused" field. It's identical to TransfusedEQ.
func Transfused(v bool) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldTransfused, v))
}

// Medications applies equality check predicate on the "medications" field. It's identical to MedicationsEQ.
func Medications(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldMedications, v))
}

// SurgicalInterventions applies equality check predicate on the "surgical_interventions" field. It's identical to SurgicalInterventionsEQ.
func SurgicalInterventions(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldSurgicalInterventions, v))
}

// PetID applies equality check predicate on the "pet_id" field. It's identical to PetIDEQ.
func PetID(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldPetID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldDeletedAt, v))
}

// ReproductiveStatusEQ applies the EQ predicate on the "reproductive_status" field.
func ReproductiveStatusEQ(v ReproductiveStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldReproductiveStatus, v))
}

// ReproductiveStatusNEQ applies the NEQ predicate on the "reproductive_status" field.
func ReproductiveStatusNEQ(v ReproductiveStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldReproductiveStatus, v))
}

// ReproductiveStatusIn applies the In predicate on the "reproductive_status" field.
func ReproductiveStatusIn(vs ...ReproductiveStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldReproductiveStatus, vs...))
}

// ReproductiveStatusNotIn applies the NotIn predicate on the "reproductive_status" field.
func ReproductiveStatusNotIn(vs ...ReproductiveStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldReproductiveStatus, vs...))
}

// ReproductiveStatusIsNil applies the IsNil predicate on the "reproductive_status" field.
func ReproductiveStatusIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldReproductiveStatus))
}

// ReproductiveStatusNotNil applies the NotNil predicate on the "reproductive_status" field.
func ReproductiveStatusNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldReproductiveStatus))
}

// HealthStatusEQ applies the EQ predicate on the "health_status" field.
func HealthStatusEQ(v HealthStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldHealthStatus, v))
}

// HealthStatusNEQ applies the NEQ predicate on the "health_status" field.
func HealthStatusNEQ(v HealthStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldHealthStatus, v))
}

// HealthStatusIn applies the In predicate on the "health_status" field.
func HealthStatusIn(vs ...HealthStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldHealthStatus, vs...))
}

// HealthStatusNotIn applies the NotIn predicate on the "health_status" field.
func HealthStatusNotIn(vs ...HealthStatus) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldHealthStatus, vs...))
}

// HealthStatusIsNil applies the IsNil predicate on the "health_status" field.
func HealthStatusIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldHealthStatus))
}

// HealthStatusNotNil applies the NotNil predicate on the "health_status" field.
func HealthStatusNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldHealthStatus))
}

// LastDonationEQ applies the EQ predicate on the "last_donation" field.
func LastDonationEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldLastDonation, v))
}

// LastDonationNEQ applies the NEQ predicate on the "last_donation" field.
func LastDonationNEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldLastDonation, v))
}

// LastDonationIn applies the In predicate on the "last_donation" field.
func LastDonationIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldLastDonation, vs...))
}

// LastDonationNotIn applies the NotIn predicate on the "last_donation" field.
func LastDonationNotIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldLastDonation, vs...))
}

// LastDonationGT applies the GT predicate on the "last_donation" field.
func LastDonationGT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldLastDonation, v))
}

// LastDonationGTE applies the GTE predicate on the "last_donation" field.
func LastDonationGTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldLastDonation, v))
}

// LastDonationLT applies the LT predicate on the "last_donation" field.
func LastDonationLT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldLastDonation, v))
}

// LastDonationLTE applies the LTE predicate on the "last_donation" field.
func LastDonationLTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldLastDonation, v))
}

// LastDonationIsNil applies the IsNil predicate on the "last_donation" field.
func LastDonationIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldLastDonation))
}

// LastDonationNotNil applies the NotNil predicate on the "last_donation" field.
func LastDonationNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldLastDonation))
}

// TransfusedEQ applies the EQ predicate on the "transfused" field.
func TransfusedEQ(v bool) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldTransfused, v))
}

// TransfusedNEQ applies the NEQ predicate on the "transfused" field.
func TransfusedNEQ(v bool) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldTransfused, v))
}

// TransfusedIsNil applies the IsNil predicate on the "transfused" field.
func TransfusedIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldTransfused))
}

// TransfusedNotNil applies the NotNil predicate on the "transfused" field.
func TransfusedNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldTransfused))
}

// MedicationsEQ applies the EQ predicate on the "medications" field.
func MedicationsEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldMedications, v))
}

// MedicationsNEQ applies the NEQ predicate on the "medications" field.
func MedicationsNEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldMedications, v))
}

// MedicationsIn applies the In predicate on the "medications" field.
func MedicationsIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldMedications, vs...))
}

// MedicationsNotIn applies the NotIn predicate on the "medications" field.
func MedicationsNotIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldMedications, vs...))
}

// MedicationsGT applies the GT predicate on the "medications" field.
func MedicationsGT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldMedications, v))
}

// MedicationsGTE applies the GTE predicate on the "medications" field.
func MedicationsGTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldMedications, v))
}

// MedicationsLT applies the LT predicate on the "medications" field.
func MedicationsLT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldMedications, v))
}

// MedicationsLTE applies the LTE predicate on the "medications" field.
func MedicationsLTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldMedications, v))
}

// MedicationsContains applies the Contains predicate on the "medications" field.
func MedicationsContains(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContains(FieldMedications, v))
}

// MedicationsHasPrefix applies the HasPrefix predicate on the "medications" field.
func MedicationsHasPrefix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasPrefix(FieldMedications, v))
}

// MedicationsHasSuffix applies the HasSuffix predicate on the "medications" field.
func MedicationsHasSuffix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasSuffix(FieldMedications, v))
}

// MedicationsIsNil applies the IsNil predicate on the "medications" field.
func MedicationsIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldMedications))
}

// MedicationsNotNil applies the NotNil predicate on the "medications" field.
func MedicationsNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldMedications))
}

// MedicationsEqualFold applies the EqualFold predicate on the "medications" field.
func MedicationsEqualFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEqualFold(FieldMedications, v))
}

// MedicationsContainsFold applies the ContainsFold predicate on the "medications" field.
func MedicationsContainsFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContainsFold(FieldMedications, v))
}

// SurgicalInterventionsEQ applies the EQ predicate on the "surgical_interventions" field.
func SurgicalInterventionsEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsNEQ applies the NEQ predicate on the "surgical_interventions" field.
func SurgicalInterventionsNEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsIn applies the In predicate on the "surgical_interventions" field.
func SurgicalInterventionsIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldSurgicalInterventions, vs...))
}

// SurgicalInterventionsNotIn applies the NotIn predicate on the "surgical_interventions" field.
func SurgicalInterventionsNotIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldSurgicalInterventions, vs...))
}

// SurgicalInterventionsGT applies the GT predicate on the "surgical_interventions" field.
func SurgicalInterventionsGT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsGTE applies the GTE predicate on the "surgical_interventions" field.
func SurgicalInterventionsGTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsLT applies the LT predicate on the "surgical_interventions" field.
func SurgicalInterventionsLT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsLTE applies the LTE predicate on the "surgical_interventions" field.
func SurgicalInterventionsLTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsContains applies the Contains predicate on the "surgical_interventions" field.
func SurgicalInterventionsContains(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContains(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsHasPrefix applies the HasPrefix predicate on the "surgical_interventions" field.
func SurgicalInterventionsHasPrefix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasPrefix(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsHasSuffix applies the HasSuffix predicate on the "surgical_interventions" field.
func SurgicalInterventionsHasSuffix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasSuffix(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsIsNil applies the IsNil predicate on the "surgical_interventions" field.
func SurgicalInterventionsIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldSurgicalInterventions))
}

// SurgicalInterventionsNotNil applies the NotNil predicate on the "surgical_interventions" field.
func SurgicalInterventionsNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldSurgicalInterventions))
}

// SurgicalInterventionsEqualFold applies the EqualFold predicate on the "surgical_interventions" field.
func SurgicalInterventionsEqualFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEqualFold(FieldSurgicalInterventions, v))
}

// SurgicalInterventionsContainsFold applies the ContainsFold predicate on the "surgical_interventions" field.
func SurgicalInterventionsContainsFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContainsFold(FieldSurgicalInterventions, v))
}

// PetIDEQ applies the EQ predicate on the "pet_id" field.
func PetIDEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldPetID, v))
}

// PetIDNEQ applies the NEQ predicate on the "pet_id" field.
func PetIDNEQ(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldPetID, v))
}

// PetIDIn applies the In predicate on the "pet_id" field.
func PetIDIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldPetID, vs...))
}

// PetIDNotIn applies the NotIn predicate on the "pet_id" field.
func PetIDNotIn(vs ...string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldPetID, vs...))
}

// PetIDGT applies the GT predicate on the "pet_id" field.
func PetIDGT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldPetID, v))
}

// PetIDGTE applies the GTE predicate on the "pet_id" field.
func PetIDGTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldPetID, v))
}

// PetIDLT applies the LT predicate on the "pet_id" field.
func PetIDLT(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldPetID, v))
}

// PetIDLTE applies the LTE predicate on the "pet_id" field.
func PetIDLTE(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldPetID, v))
}

// PetIDContains applies the Contains predicate on the "pet_id" field.
func PetIDContains(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContains(FieldPetID, v))
}

// PetIDHasPrefix applies the HasPrefix predicate on the "pet_id" field.
func PetIDHasPrefix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasPrefix(FieldPetID, v))
}

// PetIDHasSuffix applies the HasSuffix predicate on the "pet_id" field.
func PetIDHasSuffix(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldHasSuffix(FieldPetID, v))
}

// PetIDIsNil applies the IsNil predicate on the "pet_id" field.
func PetIDIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldPetID))
}

// PetIDNotNil applies the NotNil predicate on the "pet_id" field.
func PetIDNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldPetID))
}

// PetIDEqualFold applies the EqualFold predicate on the "pet_id" field.
func PetIDEqualFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEqualFold(FieldPetID, v))
}

// PetIDContainsFold applies the ContainsFold predicate on the "pet_id" field.
func PetIDContainsFold(v string) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldContainsFold(FieldPetID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PetHealth {
	return predicate.PetHealth(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PetHealth {
	return predicate.PetHealth(sql.FieldNotNull(FieldDeletedAt))
}

// HasPet applies the HasEdge predicate on the "pet" edge.
func HasPet() predicate.PetHealth {
	return predicate.PetHealth(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PetTable, PetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetWith applies the HasEdge predicate on the "pet" edge with a given conditions (other predicates).
func HasPetWith(preds ...predicate.Pet) predicate.PetHealth {
	return predicate.PetHealth(func(s *sql.Selector) {
		step := newPetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PetHealth) predicate.PetHealth {
	return predicate.PetHealth(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PetHealth) predicate.PetHealth {
	return predicate.PetHealth(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PetHealth) predicate.PetHealth {
	return predicate.PetHealth(sql.NotPredicates(p))
}
