// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDeletedAt, v))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFullName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// Verified applies equality check predicate on the "verified" field. It's identical to VerifiedEQ.
func Verified(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerified, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerifiedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// OrganizationName applies equality check predicate on the "organization_name" field. It's identical to OrganizationNameEQ.
func OrganizationName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOrganizationName, v))
}

// ConsentPd applies equality check predicate on the "consent_pd" field. It's identical to ConsentPdEQ.
func ConsentPd(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldConsentPd, v))
}

// AllowGeo applies equality check predicate on the "allow_geo" field. It's identical to AllowGeoEQ.
func AllowGeo(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAllowGeo, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLocationID, v))
}

// OriginSource applies equality check predicate on the "origin_source" field. It's identical to OriginSourceEQ.
func OriginSource(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOriginSource, v))
}

// PrioritySearchCount applies equality check predicate on the "priority_search_count" field. It's identical to PrioritySearchCountEQ.
func PrioritySearchCount(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrioritySearchCount, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldDeletedAt))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameIsNil applies the IsNil predicate on the "full_name" field.
func FullNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFullName))
}

// FullNameNotNil applies the NotNil predicate on the "full_name" field.
func FullNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFullName))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldFullName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPhone, v))
}

// VerifiedEQ applies the EQ predicate on the "verified" field.
func VerifiedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerified, v))
}

// VerifiedNEQ applies the NEQ predicate on the "verified" field.
func VerifiedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldVerified, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldVerifiedAt))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// OrganizationNameEQ applies the EQ predicate on the "organization_name" field.
func OrganizationNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOrganizationName, v))
}

// OrganizationNameNEQ applies the NEQ predicate on the "organization_name" field.
func OrganizationNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOrganizationName, v))
}

// OrganizationNameIn applies the In predicate on the "organization_name" field.
func OrganizationNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOrganizationName, vs...))
}

// OrganizationNameNotIn applies the NotIn predicate on the "organization_name" field.
func OrganizationNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOrganizationName, vs...))
}

// OrganizationNameGT applies the GT predicate on the "organization_name" field.
func OrganizationNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOrganizationName, v))
}

// OrganizationNameGTE applies the GTE predicate on the "organization_name" field.
func OrganizationNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOrganizationName, v))
}

// OrganizationNameLT applies the LT predicate on the "organization_name" field.
func OrganizationNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOrganizationName, v))
}

// OrganizationNameLTE applies the LTE predicate on the "organization_name" field.
func OrganizationNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOrganizationName, v))
}

// OrganizationNameContains applies the Contains predicate on the "organization_name" field.
func OrganizationNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOrganizationName, v))
}

// OrganizationNameHasPrefix applies the HasPrefix predicate on the "organization_name" field.
func OrganizationNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOrganizationName, v))
}

// OrganizationNameHasSuffix applies the HasSuffix predicate on the "organization_name" field.
func OrganizationNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOrganizationName, v))
}

// OrganizationNameIsNil applies the IsNil predicate on the "organization_name" field.
func OrganizationNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOrganizationName))
}

// OrganizationNameNotNil applies the NotNil predicate on the "organization_name" field.
func OrganizationNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOrganizationName))
}

// OrganizationNameEqualFold applies the EqualFold predicate on the "organization_name" field.
func OrganizationNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOrganizationName, v))
}

// OrganizationNameContainsFold applies the ContainsFold predicate on the "organization_name" field.
func OrganizationNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOrganizationName, v))
}

// ConsentPdEQ applies the EQ predicate on the "consent_pd" field.
func ConsentPdEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldConsentPd, v))
}

// ConsentPdNEQ applies the NEQ predicate on the "consent_pd" field.
func ConsentPdNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldConsentPd, v))
}

// OnBoardingIsNil applies the IsNil predicate on the "on_boarding" field.
func OnBoardingIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOnBoarding))
}

// OnBoardingNotNil applies the NotNil predicate on the "on_boarding" field.
func OnBoardingNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOnBoarding))
}

// AllowGeoEQ applies the EQ predicate on the "allow_geo" field.
func AllowGeoEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAllowGeo, v))
}

// AllowGeoNEQ applies the NEQ predicate on the "allow_geo" field.
func AllowGeoNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAllowGeo, v))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLocationID, vs...))
}

// LocationIDGT applies the GT predicate on the "location_id" field.
func LocationIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLocationID, v))
}

// LocationIDGTE applies the GTE predicate on the "location_id" field.
func LocationIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLocationID, v))
}

// LocationIDLT applies the LT predicate on the "location_id" field.
func LocationIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLocationID, v))
}

// LocationIDLTE applies the LTE predicate on the "location_id" field.
func LocationIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLocationID, v))
}

// LocationIDContains applies the Contains predicate on the "location_id" field.
func LocationIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLocationID, v))
}

// LocationIDHasPrefix applies the HasPrefix predicate on the "location_id" field.
func LocationIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLocationID, v))
}

// LocationIDHasSuffix applies the HasSuffix predicate on the "location_id" field.
func LocationIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLocationID, v))
}

// LocationIDIsNil applies the IsNil predicate on the "location_id" field.
func LocationIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLocationID))
}

// LocationIDNotNil applies the NotNil predicate on the "location_id" field.
func LocationIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLocationID))
}

// LocationIDEqualFold applies the EqualFold predicate on the "location_id" field.
func LocationIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLocationID, v))
}

// LocationIDContainsFold applies the ContainsFold predicate on the "location_id" field.
func LocationIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLocationID, v))
}

// PhotoUrlsIsNil applies the IsNil predicate on the "photo_urls" field.
func PhotoUrlsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPhotoUrls))
}

// PhotoUrlsNotNil applies the NotNil predicate on the "photo_urls" field.
func PhotoUrlsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPhotoUrls))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.User {
	return predicate.User(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRole, vs...))
}

// OriginSourceEQ applies the EQ predicate on the "origin_source" field.
func OriginSourceEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOriginSource, v))
}

// OriginSourceNEQ applies the NEQ predicate on the "origin_source" field.
func OriginSourceNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOriginSource, v))
}

// OriginSourceIn applies the In predicate on the "origin_source" field.
func OriginSourceIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOriginSource, vs...))
}

// OriginSourceNotIn applies the NotIn predicate on the "origin_source" field.
func OriginSourceNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOriginSource, vs...))
}

// OriginSourceGT applies the GT predicate on the "origin_source" field.
func OriginSourceGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOriginSource, v))
}

// OriginSourceGTE applies the GTE predicate on the "origin_source" field.
func OriginSourceGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOriginSource, v))
}

// OriginSourceLT applies the LT predicate on the "origin_source" field.
func OriginSourceLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOriginSource, v))
}

// OriginSourceLTE applies the LTE predicate on the "origin_source" field.
func OriginSourceLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOriginSource, v))
}

// OriginSourceContains applies the Contains predicate on the "origin_source" field.
func OriginSourceContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOriginSource, v))
}

// OriginSourceHasPrefix applies the HasPrefix predicate on the "origin_source" field.
func OriginSourceHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOriginSource, v))
}

// OriginSourceHasSuffix applies the HasSuffix predicate on the "origin_source" field.
func OriginSourceHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOriginSource, v))
}

// OriginSourceIsNil applies the IsNil predicate on the "origin_source" field.
func OriginSourceIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldOriginSource))
}

// OriginSourceNotNil applies the NotNil predicate on the "origin_source" field.
func OriginSourceNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldOriginSource))
}

// OriginSourceEqualFold applies the EqualFold predicate on the "origin_source" field.
func OriginSourceEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOriginSource, v))
}

// OriginSourceContainsFold applies the ContainsFold predicate on the "origin_source" field.
func OriginSourceContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOriginSource, v))
}

// PrioritySearchCountEQ applies the EQ predicate on the "priority_search_count" field.
func PrioritySearchCountEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPrioritySearchCount, v))
}

// PrioritySearchCountNEQ applies the NEQ predicate on the "priority_search_count" field.
func PrioritySearchCountNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPrioritySearchCount, v))
}

// PrioritySearchCountIn applies the In predicate on the "priority_search_count" field.
func PrioritySearchCountIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldPrioritySearchCount, vs...))
}

// PrioritySearchCountNotIn applies the NotIn predicate on the "priority_search_count" field.
func PrioritySearchCountNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPrioritySearchCount, vs...))
}

// PrioritySearchCountGT applies the GT predicate on the "priority_search_count" field.
func PrioritySearchCountGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldPrioritySearchCount, v))
}

// PrioritySearchCountGTE applies the GTE predicate on the "priority_search_count" field.
func PrioritySearchCountGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPrioritySearchCount, v))
}

// PrioritySearchCountLT applies the LT predicate on the "priority_search_count" field.
func PrioritySearchCountLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldPrioritySearchCount, v))
}

// PrioritySearchCountLTE applies the LTE predicate on the "priority_search_count" field.
func PrioritySearchCountLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPrioritySearchCount, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldLastSeenAt))
}

// HasPets applies the HasEdge predicate on the "pets" edge.
func HasPets() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PetsTable, PetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPetsWith applies the HasEdge predicate on the "pets" edge with a given conditions (other predicates).
func HasPetsWith(preds ...predicate.Pet) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDonorPreference applies the HasEdge predicate on the "donor_preference" edge.
func HasDonorPreference() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, DonorPreferenceTable, DonorPreferenceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDonorPreferenceWith applies the HasEdge predicate on the "donor_preference" edge with a given conditions (other predicates).
func HasDonorPreferenceWith(preds ...predicate.DonorPreference) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newDonorPreferenceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdentities applies the HasEdge predicate on the "identities" edge.
func HasIdentities() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IdentitiesTable, IdentitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdentitiesWith applies the HasEdge predicate on the "identities" edge with a given conditions (other predicates).
func HasIdentitiesWith(preds ...predicate.UserIdentity) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newIdentitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUtmHistories applies the HasEdge predicate on the "utm_histories" edge.
func HasUtmHistories() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UtmHistoriesTable, UtmHistoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUtmHistoriesWith applies the HasEdge predicate on the "utm_histories" edge with a given conditions (other predicates).
func HasUtmHistoriesWith(preds ...predicate.UtmHistory) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newUtmHistoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBonuses applies the HasEdge predicate on the "bonuses" edge.
func HasBonuses() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BonusesTable, BonusesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBonusesWith applies the HasEdge predicate on the "bonuses" edge with a given conditions (other predicates).
func HasBonusesWith(preds ...predicate.Bonus) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBonusesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
