/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppError,
  BloodSearchFilterRequest,
  BloodSearchPetRequest,
  BloodSearchPetResponse,
  ConfirmUploadRequest,
  DonorApplicationCreate,
  DonorApplicationResponse,
  MessageBody,
  UpdateBloodRequestDTO,
  UploadURLResponseBody,
} from '../models/index';
import {
    AppErrorFromJSON,
    AppErrorToJSON,
    BloodSearchFilterRequestFromJSON,
    BloodSearchFilterRequestToJSON,
    BloodSearchPetRequestFromJSON,
    BloodSearchPetRequestToJSON,
    BloodSearchPetResponseFromJSON,
    BloodSearchPetResponseToJSON,
    ConfirmUploadRequestFromJSON,
    ConfirmUploadRequestToJSON,
    DonorApplicationCreateFromJSON,
    DonorApplicationCreateToJSON,
    DonorApplicationResponseFromJSON,
    DonorApplicationResponseToJSON,
    MessageBodyFromJSON,
    MessageBodyToJSON,
    UpdateBloodRequestDTOFromJSON,
    UpdateBloodRequestDTOToJSON,
    UploadURLResponseBodyFromJSON,
    UploadURLResponseBodyToJSON,
} from '../models/index';

export interface AddPetToBloodRequestPoolRequest {
    bloodSearchPetRequest: Omit<BloodSearchPetRequest, '$schema'|'createdAt'|'deletedAt'|'updatedAt'>;
}

export interface ApplyForBloodRequestRequest {
    id: string;
    donorApplicationCreate: Omit<DonorApplicationCreate, '$schema'>;
}

export interface ConfirmUploadOperationRequest {
    confirmUploadRequest: Omit<ConfirmUploadRequest, '$schema'>;
}

export interface DeleteBloodRequestRequest {
    id: string;
}

export interface GetBloodRequestByIdRequest {
    id: string;
}

export interface GetBloodRequestByPetIdRequest {
    id: string;
}

export interface GetPetsFromBloodRequestPoolRequest {
    bloodSearchFilterRequest: Omit<BloodSearchFilterRequest, '$schema'>;
}

export interface GetPresignedUrlRequest {
    id: string;
    photosCount?: number;
    forPetAvatar?: boolean;
    forUserAvatar?: boolean;
    forBloodReq?: boolean;
}

export interface UpdateBloodRequestRequest {
    id: string;
    updateBloodRequestDTO: Omit<UpdateBloodRequestDTO, '$schema'>;
}

/**
 * 
 */
export class BloodRequestV1Api extends runtime.BaseAPI {

    /**
     * Создает новую заявку на поиск крови для питомца
     * Добавить питомца в пул поиска крови
     */
    async addPetToBloodRequestPoolRaw(requestParameters: AddPetToBloodRequestPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodSearchPetResponse>> {
        if (requestParameters['bloodSearchPetRequest'] == null) {
            throw new runtime.RequiredError(
                'bloodSearchPetRequest',
                'Required parameter "bloodSearchPetRequest" was null or undefined when calling addPetToBloodRequestPool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/blood-request/pool`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BloodSearchPetRequestToJSON(requestParameters['bloodSearchPetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodSearchPetResponseFromJSON(jsonValue));
    }

    /**
     * Создает новую заявку на поиск крови для питомца
     * Добавить питомца в пул поиска крови
     */
    async addPetToBloodRequestPool(requestParameters: AddPetToBloodRequestPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodSearchPetResponse> {
        const response = await this.addPetToBloodRequestPoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Позволяет донору откликнуться на существующую заявку на поиск крови.
     * Откликнуться на заявку на поиск крови
     */
    async applyForBloodRequestRaw(requestParameters: ApplyForBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DonorApplicationResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applyForBloodRequest().'
            );
        }

        if (requestParameters['donorApplicationCreate'] == null) {
            throw new runtime.RequiredError(
                'donorApplicationCreate',
                'Required parameter "donorApplicationCreate" was null or undefined when calling applyForBloodRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/blood-request/apply/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DonorApplicationCreateToJSON(requestParameters['donorApplicationCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DonorApplicationResponseFromJSON(jsonValue));
    }

    /**
     * Позволяет донору откликнуться на существующую заявку на поиск крови.
     * Откликнуться на заявку на поиск крови
     */
    async applyForBloodRequest(requestParameters: ApplyForBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DonorApplicationResponse> {
        const response = await this.applyForBloodRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUploadRaw(requestParameters: ConfirmUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageBody>> {
        if (requestParameters['confirmUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmUploadRequest',
                'Required parameter "confirmUploadRequest" was null or undefined when calling confirmUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/uploads/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmUploadRequestToJSON(requestParameters['confirmUploadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageBodyFromJSON(jsonValue));
    }

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUpload(requestParameters: ConfirmUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageBody> {
        const response = await this.confirmUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаляет заявку на поиск крови (soft delete)
     * Удалить заявку
     */
    async deleteBloodRequestRaw(requestParameters: DeleteBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBloodRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/blood-request/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageBodyFromJSON(jsonValue));
    }

    /**
     * Удаляет заявку на поиск крови (soft delete)
     * Удалить заявку
     */
    async deleteBloodRequest(requestParameters: DeleteBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageBody> {
        const response = await this.deleteBloodRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает информацию о конкретной заявке
     * Получить заявку по ID
     */
    async getBloodRequestByIdRaw(requestParameters: GetBloodRequestByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodSearchPetRequest>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBloodRequestById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/blood-request/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodSearchPetRequestFromJSON(jsonValue));
    }

    /**
     * Возвращает информацию о конкретной заявке
     * Получить заявку по ID
     */
    async getBloodRequestById(requestParameters: GetBloodRequestByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodSearchPetRequest> {
        const response = await this.getBloodRequestByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает информацию о конкретной заявке
     * Получить заявку по ID питомца
     */
    async getBloodRequestByPetIdRaw(requestParameters: GetBloodRequestByPetIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodSearchPetRequest>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBloodRequestByPetId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/blood-request/pet/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodSearchPetRequestFromJSON(jsonValue));
    }

    /**
     * Возвращает информацию о конкретной заявке
     * Получить заявку по ID питомца
     */
    async getBloodRequestByPetId(requestParameters: GetBloodRequestByPetIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodSearchPetRequest> {
        const response = await this.getBloodRequestByPetIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список заявок по фильтрам
     * Получить список заявок на поиск крови
     */
    async getPetsFromBloodRequestPoolRaw(requestParameters: GetPetsFromBloodRequestPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BloodSearchPetRequest>>> {
        if (requestParameters['bloodSearchFilterRequest'] == null) {
            throw new runtime.RequiredError(
                'bloodSearchFilterRequest',
                'Required parameter "bloodSearchFilterRequest" was null or undefined when calling getPetsFromBloodRequestPool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/blood-request/pool/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BloodSearchFilterRequestToJSON(requestParameters['bloodSearchFilterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BloodSearchPetRequestFromJSON));
    }

    /**
     * Возвращает список заявок по фильтрам
     * Получить список заявок на поиск крови
     */
    async getPetsFromBloodRequestPool(requestParameters: GetPetsFromBloodRequestPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BloodSearchPetRequest>> {
        const response = await this.getPetsFromBloodRequestPoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrlRaw(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadURLResponseBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPresignedUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['photosCount'] != null) {
            queryParameters['photos_count'] = requestParameters['photosCount'];
        }

        if (requestParameters['forPetAvatar'] != null) {
            queryParameters['for_pet_avatar'] = requestParameters['forPetAvatar'];
        }

        if (requestParameters['forUserAvatar'] != null) {
            queryParameters['for_user_avatar'] = requestParameters['forUserAvatar'];
        }

        if (requestParameters['forBloodReq'] != null) {
            queryParameters['for_blood_req'] = requestParameters['forBloodReq'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/uploads/presign/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadURLResponseBodyFromJSON(jsonValue));
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrl(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadURLResponseBody> {
        const response = await this.getPresignedUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Частично обновляет информацию о существующей заявке на поиск крови.
     * Обновить заявку на поиск крови
     */
    async updateBloodRequestRaw(requestParameters: UpdateBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodSearchPetRequest>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBloodRequest().'
            );
        }

        if (requestParameters['updateBloodRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'updateBloodRequestDTO',
                'Required parameter "updateBloodRequestDTO" was null or undefined when calling updateBloodRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/blood-request/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBloodRequestDTOToJSON(requestParameters['updateBloodRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodSearchPetRequestFromJSON(jsonValue));
    }

    /**
     * Частично обновляет информацию о существующей заявке на поиск крови.
     * Обновить заявку на поиск крови
     */
    async updateBloodRequest(requestParameters: UpdateBloodRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodSearchPetRequest> {
        const response = await this.updateBloodRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
