/* tslint:disable */
/* eslint-disable */
/**
 * 1krovi.app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppError,
  MessageBody,
  UsersDeletedBody,
} from '../models/index';
import {
    AppErrorFromJSON,
    AppErrorToJSON,
    MessageBodyFromJSON,
    MessageBodyToJSON,
    UsersDeletedBodyFromJSON,
    UsersDeletedBodyToJSON,
} from '../models/index';

export interface ResetUserRequest {
    id: string;
}

export interface RestoreUserRequest {
    id: string;
}

/**
 * 
 */
export class DevApi extends runtime.BaseAPI {

    /**
     * Возвращает список всех мягко удаленных пользователей
     * Получение всех удаленных пользователей
     */
    async getDeletedUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersDeletedBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/user/deleted-users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersDeletedBodyFromJSON(jsonValue));
    }

    /**
     * Возвращает список всех мягко удаленных пользователей
     * Получение всех удаленных пользователей
     */
    async getDeletedUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersDeletedBody> {
        const response = await this.getDeletedUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Сбрасывает пользователя к заводским настройкам на этапе команды старт от бота
     * Сброс пользователя к начальным настройкам
     */
    async resetUserRaw(requestParameters: ResetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resetUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/user/reset-user/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageBodyFromJSON(jsonValue));
    }

    /**
     * Сбрасывает пользователя к заводским настройкам на этапе команды старт от бота
     * Сброс пользователя к начальным настройкам
     */
    async resetUser(requestParameters: ResetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageBody> {
        const response = await this.resetUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Восстанавливает мягко удаленного пользователя, устанавливая deleted_at в NULL
     * Восстановление удаленного пользователя
     */
    async restoreUserRaw(requestParameters: RestoreUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling restoreUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/user/restore-user/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageBodyFromJSON(jsonValue));
    }

    /**
     * Восстанавливает мягко удаленного пользователя, устанавливая deleted_at в NULL
     * Восстановление удаленного пользователя
     */
    async restoreUser(requestParameters: RestoreUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageBody> {
        const response = await this.restoreUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
