/* tslint:disable */
/* eslint-disable */
/**
 * 1krovi.app
 * API сервиса однойкрови.рф для донороcства крови и помощи животным
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlersReferenceResponse,
  HandlersReferenceResponseDB,
  ModelsBloodSearchFilterRequest,
  ModelsBloodSearchPetRequest,
  ModelsBloodSearchPetResponse,
  ModelsBloodSearchPetsResponse,
  ModelsPet,
  ServicesPetCreate,
  ServicesPetUpdate,
  UtilsErrorResponse,
  UtilsSuccessResponse,
} from '../models/index';
import {
    HandlersReferenceResponseFromJSON,
    HandlersReferenceResponseToJSON,
    HandlersReferenceResponseDBFromJSON,
    HandlersReferenceResponseDBToJSON,
    ModelsBloodSearchFilterRequestFromJSON,
    ModelsBloodSearchFilterRequestToJSON,
    ModelsBloodSearchPetRequestFromJSON,
    ModelsBloodSearchPetRequestToJSON,
    ModelsBloodSearchPetResponseFromJSON,
    ModelsBloodSearchPetResponseToJSON,
    ModelsBloodSearchPetsResponseFromJSON,
    ModelsBloodSearchPetsResponseToJSON,
    ModelsPetFromJSON,
    ModelsPetToJSON,
    ServicesPetCreateFromJSON,
    ServicesPetCreateToJSON,
    ServicesPetUpdateFromJSON,
    ServicesPetUpdateToJSON,
    UtilsErrorResponseFromJSON,
    UtilsErrorResponseToJSON,
    UtilsSuccessResponseFromJSON,
    UtilsSuccessResponseToJSON,
} from '../models/index';

export interface PetsBloodRequestPoolPostRequest {
    request: ModelsBloodSearchPetRequest;
}

export interface PetsBloodRequestPoolSearchPostRequest {
    request: ModelsBloodSearchFilterRequest;
}

export interface PetsIdDeleteRequest {
    id: string;
}

export interface PetsIdGetRequest {
    id: string;
    withHealth?: boolean;
    withTreatments?: boolean;
    withAnalysis?: boolean;
    withBonuses?: boolean;
    withAll?: boolean;
}

export interface PetsIdPutRequest {
    id: string;
    request: ServicesPetUpdate;
}

export interface PetsUploadAvatarConfirmPathPostRequest {
    path: string;
}

export interface PetsUploadAvatarIdGetRequest {
    id: string;
}

export interface PetsUserUserIdGetRequest {
    userId: string;
    withHealth?: boolean;
    withTreatments?: boolean;
    withAnalysis?: boolean;
    withBonuses?: boolean;
    withAll?: boolean;
}

export interface PetsUserUserIdPostRequest {
    userId: string;
    request: ServicesPetCreate;
}

export interface ReferenceBloodGroupsPetTypeGetRequest {
    petType: string;
}

export interface ReferenceBreedsByTypeGetRequest {
    petType: string;
}

/**
 * 
 */
export class PetsApi extends runtime.BaseAPI {

    /**
     * Добавляет питомца-реципиента в пул поиска крови
     * Добавить питомца в пул поиска крови
     */
    async petsBloodRequestPoolPostRaw(requestParameters: PetsBloodRequestPoolPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsBloodSearchPetResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling petsBloodRequestPoolPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pets/blood-request/pool`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsBloodSearchPetRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsBloodSearchPetResponseFromJSON(jsonValue));
    }

    /**
     * Добавляет питомца-реципиента в пул поиска крови
     * Добавить питомца в пул поиска крови
     */
    async petsBloodRequestPoolPost(requestParameters: PetsBloodRequestPoolPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsBloodSearchPetResponse> {
        const response = await this.petsBloodRequestPoolPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список питомцев-реципиентов по фильтрам
     * Получить питомцев из пула поиска крови
     */
    async petsBloodRequestPoolSearchPostRaw(requestParameters: PetsBloodRequestPoolSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsBloodSearchPetsResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling petsBloodRequestPoolSearchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pets/blood-request/pool/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsBloodSearchFilterRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsBloodSearchPetsResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает список питомцев-реципиентов по фильтрам
     * Получить питомцев из пула поиска крови
     */
    async petsBloodRequestPoolSearchPost(requestParameters: PetsBloodRequestPoolSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsBloodSearchPetsResponse> {
        const response = await this.petsBloodRequestPoolSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаляет питомца из системы
     * Удаление питомца по ID
     */
    async petsIdDeleteRaw(requestParameters: PetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UtilsSuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling petsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UtilsSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Удаляет питомца из системы
     * Удаление питомца по ID
     */
    async petsIdDelete(requestParameters: PetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UtilsSuccessResponse> {
        const response = await this.petsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает информацию о питомце по его идентификатору
     * Получение питомца по ID
     */
    async petsIdGetRaw(requestParameters: PetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsPet>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling petsIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withHealth'] != null) {
            queryParameters['with_health'] = requestParameters['withHealth'];
        }

        if (requestParameters['withTreatments'] != null) {
            queryParameters['with_treatments'] = requestParameters['withTreatments'];
        }

        if (requestParameters['withAnalysis'] != null) {
            queryParameters['with_analysis'] = requestParameters['withAnalysis'];
        }

        if (requestParameters['withBonuses'] != null) {
            queryParameters['with_bonuses'] = requestParameters['withBonuses'];
        }

        if (requestParameters['withAll'] != null) {
            queryParameters['with_all'] = requestParameters['withAll'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsPetFromJSON(jsonValue));
    }

    /**
     * Возвращает информацию о питомце по его идентификатору
     * Получение питомца по ID
     */
    async petsIdGet(requestParameters: PetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsPet> {
        const response = await this.petsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновляет информацию о питомце
     * Обновление данных питомца
     */
    async petsIdPutRaw(requestParameters: PetsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UtilsSuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling petsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling petsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServicesPetUpdateToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UtilsSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Обновляет информацию о питомце
     * Обновление данных питомца
     */
    async petsIdPut(requestParameters: PetsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UtilsSuccessResponse> {
        const response = await this.petsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Подтверждает загрузку аватарки питомца, делает её публичной и возвращает публичную ссылку
     * Подтверждение загрузки аватарки питомца
     */
    async petsUploadAvatarConfirmPathPostRaw(requestParameters: PetsUploadAvatarConfirmPathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling petsUploadAvatarConfirmPathPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/upload/avatar/confirm/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Подтверждает загрузку аватарки питомца, делает её публичной и возвращает публичную ссылку
     * Подтверждение загрузки аватарки питомца
     */
    async petsUploadAvatarConfirmPathPost(requestParameters: PetsUploadAvatarConfirmPathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.petsUploadAvatarConfirmPathPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии питомца по ID
     * Получить ссылку для загрузки фотографии питомца
     */
    async petsUploadAvatarIdGetRaw(requestParameters: PetsUploadAvatarIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling petsUploadAvatarIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/upload/avatar/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии питомца по ID
     * Получить ссылку для загрузки фотографии питомца
     */
    async petsUploadAvatarIdGet(requestParameters: PetsUploadAvatarIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.petsUploadAvatarIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает всех питомцев конкретного пользователя
     * Получение питомцев пользователя
     */
    async petsUserUserIdGetRaw(requestParameters: PetsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsPet>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling petsUserUserIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withHealth'] != null) {
            queryParameters['with_health'] = requestParameters['withHealth'];
        }

        if (requestParameters['withTreatments'] != null) {
            queryParameters['with_treatments'] = requestParameters['withTreatments'];
        }

        if (requestParameters['withAnalysis'] != null) {
            queryParameters['with_analysis'] = requestParameters['withAnalysis'];
        }

        if (requestParameters['withBonuses'] != null) {
            queryParameters['with_bonuses'] = requestParameters['withBonuses'];
        }

        if (requestParameters['withAll'] != null) {
            queryParameters['with_all'] = requestParameters['withAll'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsPetFromJSON));
    }

    /**
     * Возвращает всех питомцев конкретного пользователя
     * Получение питомцев пользователя
     */
    async petsUserUserIdGet(requestParameters: PetsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsPet>> {
        const response = await this.petsUserUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создает нового питомца для пользователя
     * Создание нового питомца
     */
    async petsUserUserIdPostRaw(requestParameters: PetsUserUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsPet>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling petsUserUserIdPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling petsUserUserIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pets/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServicesPetCreateToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsPetFromJSON(jsonValue));
    }

    /**
     * Создает нового питомца для пользователя
     * Создание нового питомца
     */
    async petsUserUserIdPost(requestParameters: PetsUserUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsPet> {
        const response = await this.petsUserUserIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список компонентов крови животных для выбора на фронтенде
     * Получение компонентов крови животных
     */
    async referenceBloodComponentsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/blood-components`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает список компонентов крови животных для выбора на фронтенде
     * Получение компонентов крови животных
     */
    async referenceBloodComponentsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceBloodComponentsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список групп крови животных для выбора на фронтенде
     * Получение групп крови животных по типу животного
     */
    async referenceBloodGroupsPetTypeGetRaw(requestParameters: ReferenceBloodGroupsPetTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponseDB>> {
        if (requestParameters['petType'] == null) {
            throw new runtime.RequiredError(
                'petType',
                'Required parameter "petType" was null or undefined when calling referenceBloodGroupsPetTypeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/blood-groups/{pet_type}`;
        urlPath = urlPath.replace(`{${"pet_type"}}`, encodeURIComponent(String(requestParameters['petType'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseDBFromJSON(jsonValue));
    }

    /**
     * Возвращает список групп крови животных для выбора на фронтенде
     * Получение групп крови животных по типу животного
     */
    async referenceBloodGroupsPetTypeGet(requestParameters: ReferenceBloodGroupsPetTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponseDB> {
        const response = await this.referenceBloodGroupsPetTypeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список пород животных для указанного типа животного для выбора на фронтенде
     * Получение пород животных по типу
     */
    async referenceBreedsByTypeGetRaw(requestParameters: ReferenceBreedsByTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        if (requestParameters['petType'] == null) {
            throw new runtime.RequiredError(
                'petType',
                'Required parameter "petType" was null or undefined when calling referenceBreedsByTypeGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['petType'] != null) {
            queryParameters['petType'] = requestParameters['petType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/breeds-by-type`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает список пород животных для указанного типа животного для выбора на фронтенде
     * Получение пород животных по типу
     */
    async referenceBreedsByTypeGet(requestParameters: ReferenceBreedsByTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceBreedsByTypeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает список всех пород животных в базе для выбора на фронтенде
     * Получение всех пород животных
     */
    async referenceBreedsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/breeds`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает список всех пород животных в базе для выбора на фронтенде
     * Получение всех пород животных
     */
    async referenceBreedsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceBreedsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные значения пола для выбора на фронтенде
     * Получение всех значений пола
     */
    async referenceGendersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/genders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные значения пола для выбора на фронтенде
     * Получение всех значений пола
     */
    async referenceGendersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceGendersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные статусы здоровья для выбора на фронтенде
     * Получение всех статусов здоровья
     */
    async referenceHealthStatusesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/health-statuses`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные статусы здоровья для выбора на фронтенде
     * Получение всех статусов здоровья
     */
    async referenceHealthStatusesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceHealthStatusesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные условия проживания для выбора на фронтенде
     * Получение всех условий проживания
     */
    async referenceLivingConditionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/living-conditions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные условия проживания для выбора на фронтенде
     * Получение всех условий проживания
     */
    async referenceLivingConditionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceLivingConditionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные роли питомцев для выбора на фронтенде
     * Получение всех ролей питомцев
     */
    async referencePetRolesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/pet-roles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные роли питомцев для выбора на фронтенде
     * Получение всех ролей питомцев
     */
    async referencePetRolesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referencePetRolesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные типы животных для выбора на фронтенде
     * Получение всех типов животных
     */
    async referencePetTypesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/pet-types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные типы животных для выбора на фронтенде
     * Получение всех типов животных
     */
    async referencePetTypesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referencePetTypesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Возвращает все доступные репродуктивные состояния для выбора на фронтенде
     * Получение всех репродуктивных состояний
     */
    async referenceReproductiveStatusesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersReferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/reference/reproductive-statuses`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersReferenceResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает все доступные репродуктивные состояния для выбора на фронтенде
     * Получение всех репродуктивных состояний
     */
    async referenceReproductiveStatusesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersReferenceResponse> {
        const response = await this.referenceReproductiveStatusesGetRaw(initOverrides);
        return await response.value();
    }

}
