/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.23.0
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppError,
  ConfirmUploadBody,
  ConfirmUploadResult,
  CreatePetBody,
  CreatePetResult,
  DeletePetResult,
  GetPetsByUserResult,
  PetDetail,
  UpdatePetBody,
  UpdatePetResult,
  UploadURLsResult,
} from '../models/index';
import {
    AppErrorFromJSON,
    AppErrorToJSON,
    ConfirmUploadBodyFromJSON,
    ConfirmUploadBodyToJSON,
    ConfirmUploadResultFromJSON,
    ConfirmUploadResultToJSON,
    CreatePetBodyFromJSON,
    CreatePetBodyToJSON,
    CreatePetResultFromJSON,
    CreatePetResultToJSON,
    DeletePetResultFromJSON,
    DeletePetResultToJSON,
    GetPetsByUserResultFromJSON,
    GetPetsByUserResultToJSON,
    PetDetailFromJSON,
    PetDetailToJSON,
    UpdatePetBodyFromJSON,
    UpdatePetBodyToJSON,
    UpdatePetResultFromJSON,
    UpdatePetResultToJSON,
    UploadURLsResultFromJSON,
    UploadURLsResultToJSON,
} from '../models/index';

export interface ConfirmUploadRequest {
    confirmUploadBody: Omit<ConfirmUploadBody, '$schema'>;
}

export interface CreatePetRequest {
    userId: string;
    createPetBody: Omit<CreatePetBody, '$schema'>;
}

export interface DeletePetRequest {
    petId: string;
}

export interface GetPetByIdRequest {
    petId: string;
    withHealth?: boolean;
    withTreatments?: boolean;
    withAnalysis?: boolean;
    withBonuses?: boolean;
    withAll?: boolean;
}

export interface GetPresignedUrlRequest {
    id: string;
    photosCount?: number;
    forPetAvatar?: boolean;
    forUserAvatar?: boolean;
    forBloodReq?: boolean;
}

export interface GetUserPetsRequest {
    userId: string;
    withHealth?: boolean;
    withTreatments?: boolean;
    withAnalysis?: boolean;
    withBonuses?: boolean;
    withAll?: boolean;
}

export interface UpdatePetRequest {
    petId: string;
    updatePetBody: Omit<UpdatePetBody, '$schema'>;
}

/**
 * 
 */
export class PetsV1Api extends runtime.BaseAPI {

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUploadRaw(requestParameters: ConfirmUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmUploadResult>> {
        if (requestParameters['confirmUploadBody'] == null) {
            throw new runtime.RequiredError(
                'confirmUploadBody',
                'Required parameter "confirmUploadBody" was null or undefined when calling confirmUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/uploads/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmUploadBodyToJSON(requestParameters['confirmUploadBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmUploadResultFromJSON(jsonValue));
    }

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUpload(requestParameters: ConfirmUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmUploadResult> {
        const response = await this.confirmUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создает нового питомца для пользователя
     * Создание нового питомца
     */
    async createPetRaw(requestParameters: CreatePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePetResult>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling createPet().'
            );
        }

        if (requestParameters['createPetBody'] == null) {
            throw new runtime.RequiredError(
                'createPetBody',
                'Required parameter "createPetBody" was null or undefined when calling createPet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/pet/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePetBodyToJSON(requestParameters['createPetBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePetResultFromJSON(jsonValue));
    }

    /**
     * Создает нового питомца для пользователя
     * Создание нового питомца
     */
    async createPet(requestParameters: CreatePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePetResult> {
        const response = await this.createPetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаляет питомца из системы
     * Удаление питомца по ID
     */
    async deletePetRaw(requestParameters: DeletePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletePetResult>> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling deletePet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pet/{pet_id}`;
        urlPath = urlPath.replace(`{${"pet_id"}}`, encodeURIComponent(String(requestParameters['petId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletePetResultFromJSON(jsonValue));
    }

    /**
     * Удаляет питомца из системы
     * Удаление питомца по ID
     */
    async deletePet(requestParameters: DeletePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletePetResult> {
        const response = await this.deletePetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает информацию о питомце по его идентификатору
     * Получение питомца по ID
     */
    async getPetByIdRaw(requestParameters: GetPetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PetDetail>> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling getPetById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withHealth'] != null) {
            queryParameters['with_health'] = requestParameters['withHealth'];
        }

        if (requestParameters['withTreatments'] != null) {
            queryParameters['with_treatments'] = requestParameters['withTreatments'];
        }

        if (requestParameters['withAnalysis'] != null) {
            queryParameters['with_analysis'] = requestParameters['withAnalysis'];
        }

        if (requestParameters['withBonuses'] != null) {
            queryParameters['with_bonuses'] = requestParameters['withBonuses'];
        }

        if (requestParameters['withAll'] != null) {
            queryParameters['with_all'] = requestParameters['withAll'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pet/{pet_id}`;
        urlPath = urlPath.replace(`{${"pet_id"}}`, encodeURIComponent(String(requestParameters['petId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetDetailFromJSON(jsonValue));
    }

    /**
     * Возвращает информацию о питомце по его идентификатору
     * Получение питомца по ID
     */
    async getPetById(requestParameters: GetPetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PetDetail> {
        const response = await this.getPetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrlRaw(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadURLsResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPresignedUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['photosCount'] != null) {
            queryParameters['photos_count'] = requestParameters['photosCount'];
        }

        if (requestParameters['forPetAvatar'] != null) {
            queryParameters['for_pet_avatar'] = requestParameters['forPetAvatar'];
        }

        if (requestParameters['forUserAvatar'] != null) {
            queryParameters['for_user_avatar'] = requestParameters['forUserAvatar'];
        }

        if (requestParameters['forBloodReq'] != null) {
            queryParameters['for_blood_req'] = requestParameters['forBloodReq'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/uploads/presign/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadURLsResultFromJSON(jsonValue));
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrl(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadURLsResult> {
        const response = await this.getPresignedUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает всех питомцев конкретного пользователя
     * Получение питомцев пользователя
     */
    async getUserPetsRaw(requestParameters: GetUserPetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPetsByUserResult>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserPets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withHealth'] != null) {
            queryParameters['with_health'] = requestParameters['withHealth'];
        }

        if (requestParameters['withTreatments'] != null) {
            queryParameters['with_treatments'] = requestParameters['withTreatments'];
        }

        if (requestParameters['withAnalysis'] != null) {
            queryParameters['with_analysis'] = requestParameters['withAnalysis'];
        }

        if (requestParameters['withBonuses'] != null) {
            queryParameters['with_bonuses'] = requestParameters['withBonuses'];
        }

        if (requestParameters['withAll'] != null) {
            queryParameters['with_all'] = requestParameters['withAll'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/pet/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPetsByUserResultFromJSON(jsonValue));
    }

    /**
     * Возвращает всех питомцев конкретного пользователя
     * Получение питомцев пользователя
     */
    async getUserPets(requestParameters: GetUserPetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPetsByUserResult> {
        const response = await this.getUserPetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновляет информацию о питомце
     * Обновление данных питомца
     */
    async updatePetRaw(requestParameters: UpdatePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdatePetResult>> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling updatePet().'
            );
        }

        if (requestParameters['updatePetBody'] == null) {
            throw new runtime.RequiredError(
                'updatePetBody',
                'Required parameter "updatePetBody" was null or undefined when calling updatePet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/pet/{pet_id}`;
        urlPath = urlPath.replace(`{${"pet_id"}}`, encodeURIComponent(String(requestParameters['petId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePetBodyToJSON(requestParameters['updatePetBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdatePetResultFromJSON(jsonValue));
    }

    /**
     * Обновляет информацию о питомце
     * Обновление данных питомца
     */
    async updatePet(requestParameters: UpdatePetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdatePetResult> {
        const response = await this.updatePetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
