/* tslint:disable */
/* eslint-disable */
/**
 * Одной Крови API
 * ### Описание платформы **Одной Крови** — это Telegram Mini App, который помогает находить донорскую кровь для животных и позволяет владельцам питомцев становиться донорами вместе со своими любимцами.  * **Поиск доноров**: Быстрый поиск доноров крови для животных в экстренных ситуациях. * **Регистрация доноров**: Возможность регистрации питомцев как потенциальных доноров. * **Геолокация**: Определение ближайших доноров через Telegram Web App. * **Уведомления**: Система оповещений через Telegram Bot API. * **Интеграция с Telegram**: Удобное общение между пользователями через Telegram.
 *
 * The version of the OpenAPI document: 3.4.8
 * Contact: support@odnoi-krovi.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppError,
  ConfirmUploadBody,
  ConfirmUploadResult,
  DeleteUserResult,
  UpdateUserBody,
  UpdateUserResult,
  UploadURLsResult,
  UserDetail,
} from '../models/index';
import {
    AppErrorFromJSON,
    AppErrorToJSON,
    ConfirmUploadBodyFromJSON,
    ConfirmUploadBodyToJSON,
    ConfirmUploadResultFromJSON,
    ConfirmUploadResultToJSON,
    DeleteUserResultFromJSON,
    DeleteUserResultToJSON,
    UpdateUserBodyFromJSON,
    UpdateUserBodyToJSON,
    UpdateUserResultFromJSON,
    UpdateUserResultToJSON,
    UploadURLsResultFromJSON,
    UploadURLsResultToJSON,
    UserDetailFromJSON,
    UserDetailToJSON,
} from '../models/index';

export interface ConfirmUploadRequest {
    confirmUploadBody: Omit<ConfirmUploadBody, '$schema'>;
}

export interface DeleteUserRequest {
    id: string;
}

export interface GetPresignedUrlRequest {
    id: string;
    photosCount?: number;
    forPetAvatar?: boolean;
    forUserAvatar?: boolean;
    forBloodReq?: boolean;
}

export interface GetUserByIdRequest {
    id: string;
    withPets?: boolean;
    withDonorPreference?: boolean;
}

export interface UpdateUserRequest {
    id: string;
    updateUserBody: Omit<UpdateUserBody, '$schema'>;
}

/**
 * 
 */
export class UsersV1Api extends runtime.BaseAPI {

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUploadRaw(requestParameters: ConfirmUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmUploadResult>> {
        if (requestParameters['confirmUploadBody'] == null) {
            throw new runtime.RequiredError(
                'confirmUploadBody',
                'Required parameter "confirmUploadBody" was null or undefined when calling confirmUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/uploads/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmUploadBodyToJSON(requestParameters['confirmUploadBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmUploadResultFromJSON(jsonValue));
    }

    /**
     * Подтверждает загрузку массива фотографий, делает их публичными и обновляет сущность
     * Подтверждение загрузки фото
     */
    async confirmUpload(requestParameters: ConfirmUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmUploadResult> {
        const response = await this.confirmUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удаляет пользователя из системы (soft delete)
     * Удаление пользователя по ID
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUserResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/user/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteUserResultFromJSON(jsonValue));
    }

    /**
     * Удаляет пользователя из системы (soft delete)
     * Удаление пользователя по ID
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUserResult> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrlRaw(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadURLsResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPresignedUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['photosCount'] != null) {
            queryParameters['photos_count'] = requestParameters['photosCount'];
        }

        if (requestParameters['forPetAvatar'] != null) {
            queryParameters['for_pet_avatar'] = requestParameters['forPetAvatar'];
        }

        if (requestParameters['forUserAvatar'] != null) {
            queryParameters['for_user_avatar'] = requestParameters['forUserAvatar'];
        }

        if (requestParameters['forBloodReq'] != null) {
            queryParameters['for_blood_req'] = requestParameters['forBloodReq'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/uploads/presign/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadURLsResultFromJSON(jsonValue));
    }

    /**
     * Возвращает временную ссылку для загрузки фотографии по ID
     * Получить ссылку для загрузки фотографии
     */
    async getPresignedUrl(requestParameters: GetPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadURLsResult> {
        const response = await this.getPresignedUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает информацию о пользователе по его идентификатору
     * Получение пользователя по ID
     */
    async getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUserById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withPets'] != null) {
            queryParameters['with_pets'] = requestParameters['withPets'];
        }

        if (requestParameters['withDonorPreference'] != null) {
            queryParameters['with_donor_preference'] = requestParameters['withDonorPreference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/user/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailFromJSON(jsonValue));
    }

    /**
     * Возвращает информацию о пользователе по его идентификатору
     * Получение пользователя по ID
     */
    async getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetail> {
        const response = await this.getUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновляет информацию о пользователе
     * Обновление данных пользователя
     */
    async updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateUserResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateUser().'
            );
        }

        if (requestParameters['updateUserBody'] == null) {
            throw new runtime.RequiredError(
                'updateUserBody',
                'Required parameter "updateUserBody" was null or undefined when calling updateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/user/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserBodyToJSON(requestParameters['updateUserBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateUserResultFromJSON(jsonValue));
    }

    /**
     * Обновляет информацию о пользователе
     * Обновление данных пользователя
     */
    async updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateUserResult> {
        const response = await this.updateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
