// Code generated by ent, DO NOT EDIT.

package donorresponse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/artesipov-alt/odnoi-krovi-app/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldDeletedAt, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldAmount, v))
}

// TaxiCompensation applies equality check predicate on the "taxi_compensation" field. It's identical to TaxiCompensationEQ.
func TaxiCompensation(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldTaxiCompensation, v))
}

// IsConfirmed applies equality check predicate on the "is_confirmed" field. It's identical to IsConfirmedEQ.
func IsConfirmed(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldIsConfirmed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotNull(FieldDeletedAt))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int32) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotNull(FieldAmount))
}

// CompensationTypeEQ applies the EQ predicate on the "compensation_type" field.
func CompensationTypeEQ(v CompensationType) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldCompensationType, v))
}

// CompensationTypeNEQ applies the NEQ predicate on the "compensation_type" field.
func CompensationTypeNEQ(v CompensationType) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldCompensationType, v))
}

// CompensationTypeIn applies the In predicate on the "compensation_type" field.
func CompensationTypeIn(vs ...CompensationType) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldCompensationType, vs...))
}

// CompensationTypeNotIn applies the NotIn predicate on the "compensation_type" field.
func CompensationTypeNotIn(vs ...CompensationType) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldCompensationType, vs...))
}

// CompensationTypeIsNil applies the IsNil predicate on the "compensation_type" field.
func CompensationTypeIsNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIsNull(FieldCompensationType))
}

// CompensationTypeNotNil applies the NotNil predicate on the "compensation_type" field.
func CompensationTypeNotNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotNull(FieldCompensationType))
}

// TaxiCompensationEQ applies the EQ predicate on the "taxi_compensation" field.
func TaxiCompensationEQ(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldTaxiCompensation, v))
}

// TaxiCompensationNEQ applies the NEQ predicate on the "taxi_compensation" field.
func TaxiCompensationNEQ(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldTaxiCompensation, v))
}

// TaxiCompensationIsNil applies the IsNil predicate on the "taxi_compensation" field.
func TaxiCompensationIsNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIsNull(FieldTaxiCompensation))
}

// TaxiCompensationNotNil applies the NotNil predicate on the "taxi_compensation" field.
func TaxiCompensationNotNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotNull(FieldTaxiCompensation))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotIn(FieldStatus, vs...))
}

// IsConfirmedEQ applies the EQ predicate on the "is_confirmed" field.
func IsConfirmedEQ(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldEQ(FieldIsConfirmed, v))
}

// IsConfirmedNEQ applies the NEQ predicate on the "is_confirmed" field.
func IsConfirmedNEQ(v bool) predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNEQ(FieldIsConfirmed, v))
}

// IsConfirmedIsNil applies the IsNil predicate on the "is_confirmed" field.
func IsConfirmedIsNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldIsNull(FieldIsConfirmed))
}

// IsConfirmedNotNil applies the NotNil predicate on the "is_confirmed" field.
func IsConfirmedNotNil() predicate.DonorResponse {
	return predicate.DonorResponse(sql.FieldNotNull(FieldIsConfirmed))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.DonorResponse {
	return predicate.DonorResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.BloodSearchRequest) predicate.DonorResponse {
	return predicate.DonorResponse(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDonor applies the HasEdge predicate on the "donor" edge.
func HasDonor() predicate.DonorResponse {
	return predicate.DonorResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DonorTable, DonorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDonorWith applies the HasEdge predicate on the "donor" edge with a given conditions (other predicates).
func HasDonorWith(preds ...predicate.Pet) predicate.DonorResponse {
	return predicate.DonorResponse(func(s *sql.Selector) {
		step := newDonorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DonorResponse) predicate.DonorResponse {
	return predicate.DonorResponse(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DonorResponse) predicate.DonorResponse {
	return predicate.DonorResponse(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DonorResponse) predicate.DonorResponse {
	return predicate.DonorResponse(sql.NotPredicates(p))
}
