name: Deploy Odnoikrovi

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            backend:
              - backend/**
            bot:
              - bot/**
            frontend:
              - frontend/**

      - name: Deploy with selective rebuild
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./odnoi-krovi-app
            git pull origin dev

            # Detect which services changed
            BACKEND_CHANGED="${{ steps.changed-files.outputs.backend_any_changed }}"
            BOT_CHANGED="${{ steps.changed-files.outputs.bot_any_changed }}"
            FRONTEND_CHANGED="${{ steps.changed-files.outputs.frontend_any_changed }}"

            echo "Backend changed: $BACKEND_CHANGED"
            echo "Bot changed: $BOT_CHANGED"
            echo "Frontend changed: $FRONTEND_CHANGED"

            # Build and restart only changed services
            if [[ "$BACKEND_CHANGED" == "true" ]]; then
              echo "Rebuilding backend"
              docker compose up -d --build backend
            fi

            if [[ "$BOT_CHANGED" == "true" ]]; then
              echo "Rebuilding bot"
              docker compose up -d --build bot
            fi

            if [[ "$FRONTEND_CHANGED" == "true" ]]; then
              echo "Rebuilding frontend"
              docker compose up -d --build frontend
            fi

            # If no specific changes detected, rebuild all
            if [[ "$BACKEND_CHANGED" != "true" && "$BOT_CHANGED" != "true" && "$FRONTEND_CHANGED" != "true" ]]; then
              echo "No specific service changes detected, rebuilding all"
              docker compose up -d --build
            fi
