name: Deploy Odnoikrovi

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
            bot/**
            frontend/**

      - name: Deploy with selective rebuild
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./odnoi-krovi-app
            git pull origin dev

            # Build and restart only changed services
            if [[ "${{ steps.changed-files.outputs.backend_any_changed }}" == "true" ]]; then
              echo "Rebuilding backend"
              docker compose up -d --build backend
            fi

            if [[ "${{ steps.changed-files.outputs.bot_any_changed }}" == "true" ]]; then
              echo "Rebuilding bot"
              docker compose up -d --build bot
            fi

            if [[ "${{ steps.changed-files.outputs.frontend_any_changed }}" == "true" ]]; then
              echo "Rebuilding frontend"
              docker compose up -d --build frontend
            fi

            # If no specific changes detected, rebuild all
            if [[ "${{ steps.changed-files.outputs.backend_any_changed }}" != "true" && \
                  "${{ steps.changed-files.outputs.bot_any_changed }}" != "true" && \
                  "${{ steps.changed-files.outputs.frontend_any_changed }}" != "true" ]]; then
              echo "No specific service changes detected, rebuilding all"
              docker compose up -d --build
            fi
